import Fuglede.CyclicCertificate

/-!
# Arithmetic meaning of the cyclotomic frequency index

The cyclotomic certificate uses `N / gcd N d.val` as its index.  This file
identifies that arithmetic expression with the intrinsic additive order of
the frequency `d : ZMod N`.  Consequently the index is independent of the
chosen arithmetic presentation and really is the order of the character
generated by `d`.
-/

namespace Fuglede

/-- For a finite cyclic group, the arithmetic frequency index used by the
certificate is exactly the additive order of the frequency. -/
theorem frequencyOrder_eq_addOrderOf {N : ℕ} (hN : N ≠ 0) (d : ZMod N) :
    frequencyOrder N d = addOrderOf d := by
  letI : NeZero N := ⟨hN⟩
  calc
    frequencyOrder N d = N / Nat.gcd N d.val := rfl
    _ = addOrderOf (d.val : ZMod N) := (ZMod.addOrderOf_coe d.val hN).symm
    _ = addOrderOf d := congrArg addOrderOf (ZMod.natCast_zmod_val d)

/-- At a positive modulus, frequency order one characterizes the zero
frequency exactly. -/
theorem frequencyOrder_eq_one_iff {N : ℕ} (hN : N ≠ 0) (d : ZMod N) :
    frequencyOrder N d = 1 ↔ d = 0 := by
  rw [frequencyOrder_eq_addOrderOf hN, AddMonoid.addOrderOf_eq_one_iff]

/-- Hence every nonzero difference uses a genuinely nontrivial cyclotomic
index. -/
theorem one_lt_frequencyOrder_of_ne_zero {N : ℕ} (hN : N ≠ 0) {d : ZMod N}
    (hd : d ≠ 0) : 1 < frequencyOrder N d := by
  letI : NeZero N := ⟨hN⟩
  have hne : frequencyOrder N d ≠ 1 :=
    (frequencyOrder_eq_one_iff hN d).not.mpr hd
  have hpos : 0 < frequencyOrder N d := by
    rw [frequencyOrder_eq_addOrderOf hN]
    exact addOrderOf_pos d
  omega

/-- Negating a frequency does not change its cyclotomic index. -/
theorem frequencyOrder_neg {N : ℕ} (hN : N ≠ 0) (d : ZMod N) :
    frequencyOrder N (-d) = frequencyOrder N d := by
  rw [frequencyOrder_eq_addOrderOf hN, frequencyOrder_eq_addOrderOf hN]
  exact addOrderOf_neg d

/-- The exact order associated with a difference is symmetric in its two
endpoints. -/
theorem frequencyOrder_sub_comm {N : ℕ} (hN : N ≠ 0) (x y : ZMod N) :
    frequencyOrder N (x - y) = frequencyOrder N (y - x) := by
  simpa only [neg_sub] using (frequencyOrder_neg hN (x - y)).symm

/-- Cyclotomic zero certificates are invariant under reversing a frequency
difference.  A search therefore needs to check only unordered pairs. -/
theorem cyclotomicZero_sub_comm {N : ℕ} (hN : N ≠ 0)
    (A : Finset (ZMod N)) (x y : ZMod N) :
    CyclotomicZero N A (x - y) ↔ CyclotomicZero N A (y - x) := by
  unfold CyclotomicZero
  rw [frequencyOrder_sub_comm hN x y]

end Fuglede
