import Fuglede.LabaMarshall

/-! Kernel-dependency audit for the Laba--Marshall endpoint layer. -/

#print axioms Fuglede.natAbs_weightedSignedEvaluation_le_totalWeight
#print axioms Fuglede.natAbs_crtCuboidSign_le_one
#print axioms Fuglede.sum_signedLevelEvaluation_eq_signedFinsetEvaluation
#print axioms Fuglede.fintypeCard_dvd_signedFinsetEvaluation_of_levels_eq
#print axioms Fuglede.crt2310Modulus_dvd_signedFinsetEvaluation_of_levels_eq
#print axioms Fuglede.prod_dvd_natAbs_of_pairwise_coprime
#print axioms Fuglede.labaMarshall_arithmetic_endpoint
#print axioms Fuglede.labaMarshall_of_axis_divisibility
#print axioms Fuglede.labaMarshall_2310_of_axis_divisibility
#print axioms Fuglede.labaMarshall_2310_finset_endpoint
#print axioms Fuglede.labaMarshall_2310_finset_of_levelwise_constant
#print axioms Fuglede.labaMarshall_2310_cuboid_of_levelwise_constant
