import Fuglede.MultiAxisBounds

open Fuglede

#print axioms supportValency_empty
#print axioms card_exactCRTSupportFinset
#print axioms innerDistribution_le_card_sq
#print axioms innerDistribution_le_card_mul_supportValency
#print axioms card_CRTProjection
#print axioms occupancyMass_projectionOccupancy
#print axioms projectionOccupancy_le_capacity
#print axioms projectionPairCount_lower_relaxation
#print axioms projectionPairCount_upper_relaxation
#print axioms projectionSupportSum_lower_divMod
#print axioms projectionSupportSum_upper_divMod
