-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsCore

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_x_020 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((20 : ZMod 180) - y) ↔
        if z180K18M6Fifth (20 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (20 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (20 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_020

theorem z180_k18_m6_allowed_iff_crt_x_021 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((21 : ZMod 180) - y) ↔
        if z180K18M6Fifth (21 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (21 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (21 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_021

theorem z180_k18_m6_allowed_iff_crt_x_022 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((22 : ZMod 180) - y) ↔
        if z180K18M6Fifth (22 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (22 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (22 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_022

theorem z180_k18_m6_allowed_iff_crt_x_023 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((23 : ZMod 180) - y) ↔
        if z180K18M6Fifth (23 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (23 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (23 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_023

theorem z180_k18_m6_allowed_iff_crt_x_024 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((24 : ZMod 180) - y) ↔
        if z180K18M6Fifth (24 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (24 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (24 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_024

theorem z180_k18_m6_allowed_iff_crt_x_025 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((25 : ZMod 180) - y) ↔
        if z180K18M6Fifth (25 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (25 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (25 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_025

theorem z180_k18_m6_allowed_iff_crt_x_026 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((26 : ZMod 180) - y) ↔
        if z180K18M6Fifth (26 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (26 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (26 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_026

theorem z180_k18_m6_allowed_iff_crt_x_027 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((27 : ZMod 180) - y) ↔
        if z180K18M6Fifth (27 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (27 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (27 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_027

theorem z180_k18_m6_allowed_iff_crt_x_028 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((28 : ZMod 180) - y) ↔
        if z180K18M6Fifth (28 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (28 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (28 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_028

theorem z180_k18_m6_allowed_iff_crt_x_029 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((29 : ZMod 180) - y) ↔
        if z180K18M6Fifth (29 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (29 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (29 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_029

end Fuglede
