import Fuglede.Z180K12Graph

/-!
Assumption audit for the `ZMod 180`, `k = 12` compatibility endpoint.
The output must contain no `sorryAx`.  It deliberately exposes the two named
axioms generated by the two `native_decide` leaves, in addition to Mathlib's
standard `propext`, `Classical.choice`, and `Quot.sound`; those native-decision
axioms are the complete extra trust boundary of this endpoint.
-/

#print axioms Fuglede.z180_k12_cross_triangle_endpoint
#print axioms Fuglede.z180_k12_color_shift_ne
#print axioms Fuglede.z180_k12_card_le_six_of_pairwise_allowed
#print axioms Fuglede.z180_k12_no_seven_clique
#print axioms Fuglede.z180_k12_spectrum_card_le_six
#print axioms Fuglede.z180_k12_no_twelve_point_spectrum
