-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsCore

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_x_160 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((160 : ZMod 180) - y) ↔
        if z180K18M6Fifth (160 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (160 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (160 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_160

theorem z180_k18_m6_allowed_iff_crt_x_161 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((161 : ZMod 180) - y) ↔
        if z180K18M6Fifth (161 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (161 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (161 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_161

theorem z180_k18_m6_allowed_iff_crt_x_162 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((162 : ZMod 180) - y) ↔
        if z180K18M6Fifth (162 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (162 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (162 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_162

theorem z180_k18_m6_allowed_iff_crt_x_163 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((163 : ZMod 180) - y) ↔
        if z180K18M6Fifth (163 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (163 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (163 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_163

theorem z180_k18_m6_allowed_iff_crt_x_164 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((164 : ZMod 180) - y) ↔
        if z180K18M6Fifth (164 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (164 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (164 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_164

theorem z180_k18_m6_allowed_iff_crt_x_165 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((165 : ZMod 180) - y) ↔
        if z180K18M6Fifth (165 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (165 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (165 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_165

theorem z180_k18_m6_allowed_iff_crt_x_166 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((166 : ZMod 180) - y) ↔
        if z180K18M6Fifth (166 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (166 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (166 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_166

theorem z180_k18_m6_allowed_iff_crt_x_167 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((167 : ZMod 180) - y) ↔
        if z180K18M6Fifth (167 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (167 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (167 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_167

theorem z180_k18_m6_allowed_iff_crt_x_168 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((168 : ZMod 180) - y) ↔
        if z180K18M6Fifth (168 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (168 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (168 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_168

theorem z180_k18_m6_allowed_iff_crt_x_169 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((169 : ZMod 180) - y) ↔
        if z180K18M6Fifth (169 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (169 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (169 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_169

end Fuglede
