-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsCore

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_x_170 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((170 : ZMod 180) - y) ↔
        if z180K18M6Fifth (170 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (170 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (170 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_170

theorem z180_k18_m6_allowed_iff_crt_x_171 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((171 : ZMod 180) - y) ↔
        if z180K18M6Fifth (171 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (171 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (171 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_171

theorem z180_k18_m6_allowed_iff_crt_x_172 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((172 : ZMod 180) - y) ↔
        if z180K18M6Fifth (172 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (172 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (172 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_172

theorem z180_k18_m6_allowed_iff_crt_x_173 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((173 : ZMod 180) - y) ↔
        if z180K18M6Fifth (173 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (173 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (173 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_173

theorem z180_k18_m6_allowed_iff_crt_x_174 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((174 : ZMod 180) - y) ↔
        if z180K18M6Fifth (174 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (174 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (174 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_174

theorem z180_k18_m6_allowed_iff_crt_x_175 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((175 : ZMod 180) - y) ↔
        if z180K18M6Fifth (175 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (175 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (175 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_175

theorem z180_k18_m6_allowed_iff_crt_x_176 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((176 : ZMod 180) - y) ↔
        if z180K18M6Fifth (176 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (176 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (176 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_176

theorem z180_k18_m6_allowed_iff_crt_x_177 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((177 : ZMod 180) - y) ↔
        if z180K18M6Fifth (177 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (177 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (177 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_177

theorem z180_k18_m6_allowed_iff_crt_x_178 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((178 : ZMod 180) - y) ↔
        if z180K18M6Fifth (178 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (178 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (178 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_178

theorem z180_k18_m6_allowed_iff_crt_x_179 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((179 : ZMod 180) - y) ↔
        if z180K18M6Fifth (179 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (179 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (179 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_179

end Fuglede
