-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsCore

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_x_060 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((60 : ZMod 180) - y) ↔
        if z180K18M6Fifth (60 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (60 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (60 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_060

theorem z180_k18_m6_allowed_iff_crt_x_061 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((61 : ZMod 180) - y) ↔
        if z180K18M6Fifth (61 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (61 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (61 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_061

theorem z180_k18_m6_allowed_iff_crt_x_062 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((62 : ZMod 180) - y) ↔
        if z180K18M6Fifth (62 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (62 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (62 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_062

theorem z180_k18_m6_allowed_iff_crt_x_063 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((63 : ZMod 180) - y) ↔
        if z180K18M6Fifth (63 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (63 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (63 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_063

theorem z180_k18_m6_allowed_iff_crt_x_064 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((64 : ZMod 180) - y) ↔
        if z180K18M6Fifth (64 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (64 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (64 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_064

theorem z180_k18_m6_allowed_iff_crt_x_065 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((65 : ZMod 180) - y) ↔
        if z180K18M6Fifth (65 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (65 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (65 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_065

theorem z180_k18_m6_allowed_iff_crt_x_066 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((66 : ZMod 180) - y) ↔
        if z180K18M6Fifth (66 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (66 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (66 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_066

theorem z180_k18_m6_allowed_iff_crt_x_067 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((67 : ZMod 180) - y) ↔
        if z180K18M6Fifth (67 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (67 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (67 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_067

theorem z180_k18_m6_allowed_iff_crt_x_068 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((68 : ZMod 180) - y) ↔
        if z180K18M6Fifth (68 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (68 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (68 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_068

theorem z180_k18_m6_allowed_iff_crt_x_069 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((69 : ZMod 180) - y) ↔
        if z180K18M6Fifth (69 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (69 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (69 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_069

end Fuglede
