import Fuglede.Z180K30QuadraticPhaseV72Fix2
import Mathlib.Tactic

/-!
# Rank-two unimodular matrices have a two-class projective side

If every row is generated by two fixed rows and every matrix entry has unit
modulus, then either all rows lie in two projective classes or all columns
do.  This is the analytic, census-free core of the K30 P36 reduction.
-/

namespace Fuglede

open scoped ComplexConjugate

def Z180K30RowsCoveredByTwoProjectiveV73Fix
    (M : Matrix (Fin 6) (Fin 6) Complex) (p q : Fin 6) : Prop :=
  ∀ i,
    (∃ c : Complex, ∀ j, M i j = c * M p j) ∨
      (∃ c : Complex, ∀ j, M i j = c * M q j)

def Z180K30ColumnsCoveredByTwoProjectiveV73Fix
    (M : Matrix (Fin 6) (Fin 6) Complex) (p q : Fin 6) : Prop :=
  ∀ j,
    (∃ c : Complex, ∀ i, M i j = c * M i p) ∨
      (∃ c : Complex, ∀ i, M i j = c * M i q)

theorem rows_span_two_unit_projective_dichotomy_v73Fix
    (M : Matrix (Fin 6) (Fin 6) Complex)
    (p q : Fin 6) (alpha beta : Fin 6 → Complex)
    (hunit : ∀ i j, star (M i j) * M i j = 1)
    (hspan : ∀ i j,
      M i j = alpha i * M p j + beta i * M q j) :
    Z180K30RowsCoveredByTwoProjectiveV73Fix M p q ∨
      ∃ c d : Fin 6, Z180K30ColumnsCoveredByTwoProjectiveV73Fix M c d := by
  classical
  by_cases hsingle : ∀ i, alpha i = 0 ∨ beta i = 0
  · left
    intro i
    rcases hsingle i with hai | hbi
    · right
      refine ⟨beta i, ?_⟩
      intro j
      rw [hspan i j, hai]
      ring
    · left
      refine ⟨alpha i, ?_⟩
      intro j
      rw [hspan i j, hbi]
      ring
  · obtain ⟨i, hi⟩ : ∃ i, ¬(alpha i = 0 ∨ beta i = 0) :=
      not_forall.mp hsingle
    have halpha : alpha i ≠ 0 := fun h => hi (Or.inl h)
    have hbeta : beta i ≠ 0 := fun h => hi (Or.inr h)
    let t : Fin 6 → Complex := fun j => M q j * star (M p j)
    let z : Fin 6 → Complex := fun j => M i j * star (M p j)
    have htUnit : ∀ j, star (t j) * t j = 1 := by
      intro j
      have hp := hunit p j
      have hq := hunit q j
      dsimp only [t]
      rw [star_mul, star_star]
      calc
        (M p j * star (M q j)) * (M q j * star (M p j)) =
          (star (M p j) * M p j) *
            (star (M q j) * M q j) := by ring
        _ = 1 := by rw [hp, hq]; ring
    have hzUnit : ∀ j, star (z j) * z j = 1 := by
      intro j
      have hp := hunit p j
      have hiunit := hunit i j
      dsimp only [z]
      rw [star_mul, star_star]
      calc
        (M p j * star (M i j)) * (M i j * star (M p j)) =
          (star (M p j) * M p j) *
            (star (M i j) * M i j) := by ring
        _ = 1 := by rw [hp, hiunit]; ring
    have hzAffine : ∀ j, z j = alpha i + beta i * t j := by
      intro j
      have hp := hunit p j
      dsimp only [z, t]
      rw [hspan i j]
      linear_combination (alpha i) * hp
    have hstarAlpha : star (alpha i) ≠ 0 := by
      intro h
      apply halpha
      have hs := congrArg star h
      simpa only [star_star, star_zero] using hs
    obtain ⟨c, d, htwo⟩ := unit_affine_phase_has_two_values_v72Fix2
      (alpha i) (beta i) t z (mul_ne_zero hstarAlpha hbeta)
      htUnit hzUnit hzAffine
    right
    refine ⟨c, d, ?_⟩
    intro j
    have hcolumn (e : Fin 6) (hte : t j = t e) :
        ∃ scale : Complex, ∀ k, M k j = scale * M k e := by
      let scale : Complex := M p j * star (M p e)
      refine ⟨scale, ?_⟩
      intro k
      have hpj : M p j * star (M p j) = 1 := by
        simpa only [mul_comm] using hunit p j
      have hpe : star (M p e) * M p e = 1 := hunit p e
      have hqRelation : M q j = scale * M q e := by
        calc
          M q j = (M p j * star (M p j)) * M q j := by
            rw [hpj, one_mul]
          _ = M p j * (M q j * star (M p j)) := by ring
          _ = M p j * (M q e * star (M p e)) := by
            simpa only [t] using congrArg (fun w => M p j * w) hte
          _ = scale * M q e := by simp only [scale]; ring
      have hpScale : scale * M p e = M p j := by
        calc
          scale * M p e = M p j * (star (M p e) * M p e) := by
            simp only [scale]
            ring
          _ = M p j := by rw [hpe, mul_one]
      rw [hspan k j, hspan k e, hqRelation]
      calc
        alpha k * M p j + beta k * (scale * M q e) =
            alpha k * (scale * M p e) + beta k * (scale * M q e) := by
          rw [hpScale]
        _ = scale *
            (alpha k * M p e + beta k * M q e) := by ring
    rcases htwo j with hj | hj
    · left
      exact hcolumn c hj
    · right
      exact hcolumn d hj

#print axioms rows_span_two_unit_projective_dichotomy_v73Fix

end Fuglede
