-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsCore

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_x_090 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((90 : ZMod 180) - y) ↔
        if z180K18M6Fifth (90 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (90 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (90 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_090

theorem z180_k18_m6_allowed_iff_crt_x_091 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((91 : ZMod 180) - y) ↔
        if z180K18M6Fifth (91 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (91 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (91 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_091

theorem z180_k18_m6_allowed_iff_crt_x_092 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((92 : ZMod 180) - y) ↔
        if z180K18M6Fifth (92 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (92 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (92 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_092

theorem z180_k18_m6_allowed_iff_crt_x_093 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((93 : ZMod 180) - y) ↔
        if z180K18M6Fifth (93 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (93 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (93 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_093

theorem z180_k18_m6_allowed_iff_crt_x_094 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((94 : ZMod 180) - y) ↔
        if z180K18M6Fifth (94 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (94 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (94 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_094

theorem z180_k18_m6_allowed_iff_crt_x_095 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((95 : ZMod 180) - y) ↔
        if z180K18M6Fifth (95 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (95 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (95 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_095

theorem z180_k18_m6_allowed_iff_crt_x_096 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((96 : ZMod 180) - y) ↔
        if z180K18M6Fifth (96 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (96 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (96 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_096

theorem z180_k18_m6_allowed_iff_crt_x_097 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((97 : ZMod 180) - y) ↔
        if z180K18M6Fifth (97 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (97 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (97 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_097

theorem z180_k18_m6_allowed_iff_crt_x_098 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((98 : ZMod 180) - y) ↔
        if z180K18M6Fifth (98 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (98 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (98 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_098

theorem z180_k18_m6_allowed_iff_crt_x_099 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((99 : ZMod 180) - y) ↔
        if z180K18M6Fifth (99 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (99 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (99 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_099

end Fuglede
