-- Generated by fuglede_search/generate_z180_k4_typed_adapter.py
-- Generator SHA-256: 4d0fa3b3048b1bd7f7fb0d83eadd4f23a8fc0c6cd52fd594217d785c99bb0b88
import Fuglede.Z180ExactOrderTransform
import Fuglede.Z180K4Dpll
import Fuglede.ProjectionTiling
import Mathlib.Tactic

set_option maxHeartbeats 0

/-!
# Typed adapter for the `ZMod 180`, cardinality-four DPLL certificate

The DPLL variables are instantiated with exact-order inner distributions of
a spectral pair.  Positivity at orders three and nine is proved here from
prime-power cyclotomic divisibility; no analytic or unformalized input enters
the adapter.
-/

namespace Fuglede

open Polynomial

private theorem z180_k4_transform_ne_zero_three
    {X : Finset (ZMod 180)}
    (hidentity : Z180RamanujanIdentity X) (hnot : ¬ 3 ∣ X.card) :
    z180ExactOrderTransform X 3 ≠ 0 := by
  intro hzero
  have henergy : exactOrderFourierEnergy X 3 = 0 := by
    have h := hidentity 3 (by norm_num)
    rw [hzero] at h
    norm_num at h
    exact h.symm
  have horbit :=
    (exactOrderFourierEnergy_eq_zero_iff_cyclotomicZero X 3).mp henergy
  have horder : frequencyOrder 180 (60 : ZMod 180) = 3 := by decide
  exact hnot (prime_dvd_card_of_cyclotomicZero (by norm_num) X 60 horder
    (horbit 60 horder))

private theorem z180_k4_transform_ne_zero_nine
    {X : Finset (ZMod 180)}
    (hidentity : Z180RamanujanIdentity X) (hnot : ¬ 3 ∣ X.card) :
    z180ExactOrderTransform X 9 ≠ 0 := by
  intro hzero
  have henergy : exactOrderFourierEnergy X 9 = 0 := by
    have h := hidentity 9 (by norm_num)
    rw [hzero] at h
    norm_num at h
    exact h.symm
  have horbit :=
    (exactOrderFourierEnergy_eq_zero_iff_cyclotomicZero X 9).mp henergy
  have horder : frequencyOrder 180 (20 : ZMod 180) = 9 := by decide
  have hcyclo := horbit 20 horder
  have hdiv : cyclotomic (3 ^ (1 + 1)) Int ∣ maskPolynomial 180 X := by
    simpa [CyclotomicZero, horder] using hcyclo
  exact hnot (prime_dvd_card_of_prime_pow_cyclotomic_dvd_mask
    (by norm_num) 1 X hdiv)

theorem z180K4ExactOrderTransform_pos_three
    {X : Finset (ZMod 180)}
    (hidentity : Z180RamanujanIdentity X) (hnot : ¬ 3 ∣ X.card) :
    0 < z180ExactOrderTransform X 3 := by
  exact lt_of_le_of_ne
    (z180ExactOrderTransform_nonneg hidentity (by norm_num))
    (Ne.symm (z180_k4_transform_ne_zero_three hidentity hnot))

theorem z180K4ExactOrderTransform_pos_nine
    {X : Finset (ZMod 180)}
    (hidentity : Z180RamanujanIdentity X) (hnot : ¬ 3 ∣ X.card) :
    0 < z180ExactOrderTransform X 9 := by
  exact lt_of_le_of_ne
    (z180ExactOrderTransform_nonneg hidentity (by norm_num))
    (Ne.symm (z180_k4_transform_ne_zero_nine hidentity hnot))

/-- A nonzero element in the kernel of `ZMod 180 → ZMod 4` has one of the
five nontrivial orders dividing forty-five. -/
theorem z180_frequencyOrder_mem_of_cast4_eq :
    ∀ x y : ZMod 180,
      x ≠ y →
      (ZMod.cast x : ZMod 4) = ZMod.cast y →
      frequencyOrder 180 (x - y) ∈ ({3, 5, 9, 15, 45} : Finset Nat) := by
  intro x y hxy hcast
  have hcastZero : (ZMod.cast (x - y) : ZMod 4) = 0 := by
    rw [ZMod.cast_sub (by norm_num : 4 ∣ 180), hcast, sub_self]
  have hnatCastZero : ((x - y).val : ZMod 4) = 0 := by
    simpa only [ZMod.cast_eq_val] using hcastZero
  have hdvd : 4 ∣ (x - y).val :=
    (ZMod.natCast_eq_zero_iff (x - y).val 4).1 hnatCastZero
  obtain ⟨k, hk⟩ := hdvd
  have hvalne : (x - y).val ≠ 0 := by
    intro hzero
    have hdiff : x - y = 0 := (ZMod.val_eq_zero (x - y)).1 hzero
    exact hxy (sub_eq_zero.mp hdiff)
  have hkpos : 0 < k := by omega
  have hklt : k < 45 := by
    have hvalLt := (x - y).val_lt
    omega
  unfold frequencyOrder
  rw [hk]
  interval_cases k <;> norm_num at hkpos ⊢

/-- A concrete collision modulo four gives the strict collision-mass row used
by the arithmetic certificate. -/
theorem z180_k4_collision_mass_pos
    (A : Finset (ZMod 180)) {x y : ZMod 180}
    (hx : x ∈ A) (hy : y ∈ A) (hxy : x ≠ y)
    (hcast : (ZMod.cast x : ZMod 4) = ZMod.cast y) :
    0 < exactOrderDistributionInt A 3 +
      exactOrderDistributionInt A 5 +
      exactOrderDistributionInt A 9 +
      exactOrderDistributionInt A 15 +
      exactOrderDistributionInt A 45 := by
  have he : frequencyOrder 180 (x - y) ∈
      ({3, 5, 9, 15, 45} : Finset Nat) :=
    z180_frequencyOrder_mem_of_cast4_eq x y hxy hcast
  have hpair : (x, y) ∈
      exactOrderPairs A (frequencyOrder 180 (x - y)) := by
    simp [exactOrderPairs, hx, hy]
  have hposNat : 0 <
      exactOrderDistribution A (frequencyOrder 180 (x - y)) :=
    Finset.card_pos.mpr ⟨(x, y), hpair⟩
  have hpos : 0 <
      exactOrderDistributionInt A (frequencyOrder 180 (x - y)) := by
    change 0 <
      (exactOrderDistribution A (frequencyOrder 180 (x - y)) : Int)
    exact_mod_cast hposNat
  have h3 := exactOrderDistributionInt_nonneg A 3
  have h5 := exactOrderDistributionInt_nonneg A 5
  have h9 := exactOrderDistributionInt_nonneg A 9
  have h15 := exactOrderDistributionInt_nonneg A 15
  have h45 := exactOrderDistributionInt_nonneg A 45
  simp only [Finset.mem_insert, Finset.mem_singleton] at he
  rcases he with he | he | he | he | he
  · rw [he] at hpos
    omega
  · rw [he] at hpos
    omega
  · rw [he] at hpos
    omega
  · rw [he] at hpos
    omega
  · rw [he] at hpos
    omega

/-- Fully typed instantiation of the sealed rational DPLL refutation. -/
theorem z180_k4_nontransversal_impossible_of_ramanujan
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L) (hcard : A.card = 4)
    (hidentityA : Z180RamanujanIdentity A)
    (hidentityL : Z180RamanujanIdentity L)
    (hcollision : 0 < exactOrderDistributionInt A 3 +
      exactOrderDistributionInt A 5 +
      exactOrderDistributionInt A 9 +
      exactOrderDistributionInt A 15 +
      exactOrderDistributionInt A 45) : False := by
  have hcardL : L.card = 4 := by
    calc
      L.card = A.card := hSpec.2.1.symm
      _ = 4 := hcard
  have hnot5A : ¬ 5 ∣ A.card := by norm_num [hcard]
  have hnot5L : ¬ 5 ∣ L.card := by norm_num [hcardL]
  have hnot3A : ¬ 3 ∣ A.card := by norm_num [hcard]
  have hnot3L : ¬ 3 ∣ L.card := by norm_num [hcardL]
  exact z180_k4_nontransversal_impossible
    (a_0_1 := exactOrderDistributionInt A 1)
    (a_0_2 := exactOrderDistributionInt A 2)
    (a_0_3 := exactOrderDistributionInt A 3)
    (a_0_4 := exactOrderDistributionInt A 4)
    (a_0_5 := exactOrderDistributionInt A 5)
    (a_0_6 := exactOrderDistributionInt A 6)
    (a_0_9 := exactOrderDistributionInt A 9)
    (a_0_10 := exactOrderDistributionInt A 10)
    (a_0_12 := exactOrderDistributionInt A 12)
    (a_0_15 := exactOrderDistributionInt A 15)
    (a_0_18 := exactOrderDistributionInt A 18)
    (a_0_20 := exactOrderDistributionInt A 20)
    (a_0_30 := exactOrderDistributionInt A 30)
    (a_0_36 := exactOrderDistributionInt A 36)
    (a_0_45 := exactOrderDistributionInt A 45)
    (a_0_60 := exactOrderDistributionInt A 60)
    (a_0_90 := exactOrderDistributionInt A 90)
    (a_0_180 := exactOrderDistributionInt A 180)
    (a_1_1 := exactOrderDistributionInt L 1)
    (a_1_2 := exactOrderDistributionInt L 2)
    (a_1_3 := exactOrderDistributionInt L 3)
    (a_1_4 := exactOrderDistributionInt L 4)
    (a_1_5 := exactOrderDistributionInt L 5)
    (a_1_6 := exactOrderDistributionInt L 6)
    (a_1_9 := exactOrderDistributionInt L 9)
    (a_1_10 := exactOrderDistributionInt L 10)
    (a_1_12 := exactOrderDistributionInt L 12)
    (a_1_15 := exactOrderDistributionInt L 15)
    (a_1_18 := exactOrderDistributionInt L 18)
    (a_1_20 := exactOrderDistributionInt L 20)
    (a_1_30 := exactOrderDistributionInt L 30)
    (a_1_36 := exactOrderDistributionInt L 36)
    (a_1_45 := exactOrderDistributionInt L 45)
    (a_1_60 := exactOrderDistributionInt L 60)
    (a_1_90 := exactOrderDistributionInt L 90)
    (a_1_180 := exactOrderDistributionInt L 180)
    (by
      rw [exactOrderDistributionInt_one]
      exact_mod_cast hcard)
    (by
      simpa [hcard] using
        (z180_sum_exactOrderDistributionInt A))
    (exactOrderDistributionInt_nonneg A 2)
    (exactOrderDistributionInt_nonneg A 3)
    (exactOrderDistributionInt_nonneg A 4)
    (exactOrderDistributionInt_nonneg A 5)
    (exactOrderDistributionInt_nonneg A 6)
    (exactOrderDistributionInt_nonneg A 9)
    (exactOrderDistributionInt_nonneg A 10)
    (exactOrderDistributionInt_nonneg A 12)
    (exactOrderDistributionInt_nonneg A 15)
    (exactOrderDistributionInt_nonneg A 18)
    (exactOrderDistributionInt_nonneg A 20)
    (exactOrderDistributionInt_nonneg A 30)
    (exactOrderDistributionInt_nonneg A 36)
    (exactOrderDistributionInt_nonneg A 45)
    (exactOrderDistributionInt_nonneg A 60)
    (exactOrderDistributionInt_nonneg A 90)
    (exactOrderDistributionInt_nonneg A 180)
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 2) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 3) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180K4ExactOrderTransform_pos_three (X := A) hidentityA hnot3A))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 4) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 5) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_pos_five (X := A) hidentityA hnot5A))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 6) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 9) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180K4ExactOrderTransform_pos_nine (X := A) hidentityA hnot3A))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 10) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 12) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 15) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 18) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 20) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 30) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 36) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 45) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 60) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 90) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 180) (by norm_num)))
    (by
      rw [exactOrderDistributionInt_one]
      exact_mod_cast hcardL)
    (by
      simpa [hcardL] using
        (z180_sum_exactOrderDistributionInt L))
    (exactOrderDistributionInt_nonneg L 2)
    (exactOrderDistributionInt_nonneg L 3)
    (exactOrderDistributionInt_nonneg L 4)
    (exactOrderDistributionInt_nonneg L 5)
    (exactOrderDistributionInt_nonneg L 6)
    (exactOrderDistributionInt_nonneg L 9)
    (exactOrderDistributionInt_nonneg L 10)
    (exactOrderDistributionInt_nonneg L 12)
    (exactOrderDistributionInt_nonneg L 15)
    (exactOrderDistributionInt_nonneg L 18)
    (exactOrderDistributionInt_nonneg L 20)
    (exactOrderDistributionInt_nonneg L 30)
    (exactOrderDistributionInt_nonneg L 36)
    (exactOrderDistributionInt_nonneg L 45)
    (exactOrderDistributionInt_nonneg L 60)
    (exactOrderDistributionInt_nonneg L 90)
    (exactOrderDistributionInt_nonneg L 180)
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 2) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 3) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180K4ExactOrderTransform_pos_three (X := L) hidentityL hnot3L))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 4) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 5) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_pos_five (X := L) hidentityL hnot5L))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 6) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 9) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180K4ExactOrderTransform_pos_nine (X := L) hidentityL hnot3L))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 10) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 12) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 15) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 18) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 20) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 30) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 36) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 45) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 60) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 90) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 180) (by norm_num)))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 2) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 2) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 3) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 3) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 4) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 4) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 5) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 5) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 6) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 6) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 9) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 9) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 10) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 10) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 12) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 12) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 15) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 15) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 18) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 18) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 20) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 20) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 30) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 30) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 36) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 36) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 45) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 45) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 60) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 60) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 90) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 90) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 180) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 180) (by norm_num) (by norm_num) hpos))
    hcollision

/-- Every cardinality-four spectral set is a complete transversal modulo
four, conditional only on the two Ramanujan identities. -/
theorem z180_k4_projection4_injOn_of_spectral_of_ramanujan
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L) (hcard : A.card = 4)
    (hidentityA : Z180RamanujanIdentity A)
    (hidentityL : Z180RamanujanIdentity L) :
    Set.InjOn (fun x : ZMod 180 => (ZMod.cast x : ZMod 4))
      (A : Set (ZMod 180)) := by
  intro x hx y hy hcast
  by_contra hxy
  apply z180_k4_nontransversal_impossible_of_ramanujan
    hSpec hcard hidentityA hidentityL
  exact z180_k4_collision_mass_pos A hx hy hxy hcast

/-- The injective projection makes `A` a complete transversal and hence a
tiling complement to the kernel of reduction modulo four. -/
theorem z180_k4_tiles_projection4_kernel_of_spectral_of_ramanujan
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L) (hcard : A.card = 4)
    (hidentityA : Z180RamanujanIdentity A)
    (hidentityL : Z180RamanujanIdentity L) :
    Tiles A (kernelFinset
      (ZMod.castHom (by norm_num : 4 ∣ 180) (ZMod 4)).toAddMonoidHom) := by
  let φ : ZMod 180 →+ ZMod 4 :=
    (ZMod.castHom (by norm_num : 4 ∣ 180) (ZMod 4)).toAddMonoidHom
  apply transversal_tiles_kernel φ A
  · apply (kernel_difference_free_iff_injOn φ A).2
    have hinj := z180_k4_projection4_injOn_of_spectral_of_ramanujan
      hSpec hcard hidentityA hidentityL
    intro x hx y hy hmap
    apply hinj hx hy
    simpa [φ, ZMod.castHom_apply] using hmap
  · simpa [ZMod.card] using hcard

/-- Existential finite-tiling endpoint for the cardinality-four branch. -/
theorem z180_k4_exists_tiling_of_spectral_of_ramanujan
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L) (hcard : A.card = 4)
    (hidentityA : Z180RamanujanIdentity A)
    (hidentityL : Z180RamanujanIdentity L) :
    ∃ B : Finset (ZMod 180), Tiles A B := by
  refine ⟨kernelFinset
    (ZMod.castHom (by norm_num : 4 ∣ 180) (ZMod 4)).toAddMonoidHom, ?_⟩
  exact z180_k4_tiles_projection4_kernel_of_spectral_of_ramanujan
    hSpec hcard hidentityA hidentityL

#print axioms z180_k4_projection4_injOn_of_spectral_of_ramanujan
#print axioms z180_k4_exists_tiling_of_spectral_of_ramanujan

end Fuglede
