-- Source: fuglede_search/z180_exact_order_evidence_20260808_v1/cores/k8.core.smt2
-- Source SHA-256: 091d2769568e1cd98181059173a903e684d2e0c58bccc965aaf7047d8b8c3e1e
-- Diagnostic single-leaf emission from the replayed exact tree.
-- Generated by fuglede_search/z180_nondivisor_omega_to_lean.py
import Mathlib.Tactic

set_option maxRecDepth 100000
set_option maxHeartbeats 0

theorem z180NondivisorK8Leaf3
    {a_0_1 a_0_2 a_0_3 a_0_4 a_0_5 a_0_6 a_0_9 a_0_10 a_0_12 a_0_15 a_0_18 a_0_20 a_0_30 a_0_36 a_0_45 a_0_60 a_0_90 a_0_180 a_1_5 : Int}
    (h19 : ((a_0_1 + a_0_2 + a_0_3 + a_0_4 + a_0_5 + a_0_6 + a_0_9 + a_0_10 + a_0_12 + a_0_15 + a_0_18 + a_0_20 + a_0_30 + a_0_36 + a_0_45 + a_0_60 + a_0_90 + a_0_180) = 64))
    (d3_pos : (a_1_5 > 0))
    (d3_zero : (((a_0_1 * 4) + (a_0_2 * 4) + (a_0_3 * 4) + (a_0_4 * 4) + (a_0_5 * (-1)) + (a_0_6 * 4) + (a_0_9 * 4) + (a_0_10 * (-1)) + (a_0_12 * 4) + (a_0_15 * (-1)) + (a_0_18 * 4) + (a_0_20 * (-1)) + (a_0_30 * (-1)) + (a_0_36 * 4) + (a_0_45 * (-1)) + (a_0_60 * (-1)) + (a_0_90 * (-1)) + (a_0_180 * (-1))) = 0))
    : False := by
  omega

#print axioms z180NondivisorK8Leaf3
