-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsCore

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_x_050 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((50 : ZMod 180) - y) ↔
        if z180K18M6Fifth (50 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (50 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (50 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_050

theorem z180_k18_m6_allowed_iff_crt_x_051 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((51 : ZMod 180) - y) ↔
        if z180K18M6Fifth (51 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (51 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (51 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_051

theorem z180_k18_m6_allowed_iff_crt_x_052 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((52 : ZMod 180) - y) ↔
        if z180K18M6Fifth (52 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (52 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (52 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_052

theorem z180_k18_m6_allowed_iff_crt_x_053 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((53 : ZMod 180) - y) ↔
        if z180K18M6Fifth (53 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (53 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (53 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_053

theorem z180_k18_m6_allowed_iff_crt_x_054 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((54 : ZMod 180) - y) ↔
        if z180K18M6Fifth (54 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (54 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (54 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_054

theorem z180_k18_m6_allowed_iff_crt_x_055 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((55 : ZMod 180) - y) ↔
        if z180K18M6Fifth (55 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (55 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (55 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_055

theorem z180_k18_m6_allowed_iff_crt_x_056 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((56 : ZMod 180) - y) ↔
        if z180K18M6Fifth (56 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (56 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (56 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_056

theorem z180_k18_m6_allowed_iff_crt_x_057 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((57 : ZMod 180) - y) ↔
        if z180K18M6Fifth (57 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (57 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (57 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_057

theorem z180_k18_m6_allowed_iff_crt_x_058 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((58 : ZMod 180) - y) ↔
        if z180K18M6Fifth (58 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (58 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (58 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_058

theorem z180_k18_m6_allowed_iff_crt_x_059 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((59 : ZMod 180) - y) ↔
        if z180K18M6Fifth (59 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (59 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (59 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_059

end Fuglede
