-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsCore

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_x_100 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((100 : ZMod 180) - y) ↔
        if z180K18M6Fifth (100 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (100 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (100 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_100

theorem z180_k18_m6_allowed_iff_crt_x_101 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((101 : ZMod 180) - y) ↔
        if z180K18M6Fifth (101 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (101 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (101 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_101

theorem z180_k18_m6_allowed_iff_crt_x_102 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((102 : ZMod 180) - y) ↔
        if z180K18M6Fifth (102 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (102 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (102 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_102

theorem z180_k18_m6_allowed_iff_crt_x_103 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((103 : ZMod 180) - y) ↔
        if z180K18M6Fifth (103 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (103 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (103 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_103

theorem z180_k18_m6_allowed_iff_crt_x_104 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((104 : ZMod 180) - y) ↔
        if z180K18M6Fifth (104 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (104 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (104 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_104

theorem z180_k18_m6_allowed_iff_crt_x_105 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((105 : ZMod 180) - y) ↔
        if z180K18M6Fifth (105 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (105 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (105 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_105

theorem z180_k18_m6_allowed_iff_crt_x_106 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((106 : ZMod 180) - y) ↔
        if z180K18M6Fifth (106 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (106 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (106 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_106

theorem z180_k18_m6_allowed_iff_crt_x_107 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((107 : ZMod 180) - y) ↔
        if z180K18M6Fifth (107 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (107 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (107 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_107

theorem z180_k18_m6_allowed_iff_crt_x_108 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((108 : ZMod 180) - y) ↔
        if z180K18M6Fifth (108 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (108 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (108 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_108

theorem z180_k18_m6_allowed_iff_crt_x_109 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((109 : ZMod 180) - y) ↔
        if z180K18M6Fifth (109 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (109 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (109 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_109

end Fuglede
