-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsCore

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_x_130 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((130 : ZMod 180) - y) ↔
        if z180K18M6Fifth (130 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (130 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (130 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_130

theorem z180_k18_m6_allowed_iff_crt_x_131 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((131 : ZMod 180) - y) ↔
        if z180K18M6Fifth (131 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (131 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (131 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_131

theorem z180_k18_m6_allowed_iff_crt_x_132 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((132 : ZMod 180) - y) ↔
        if z180K18M6Fifth (132 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (132 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (132 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_132

theorem z180_k18_m6_allowed_iff_crt_x_133 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((133 : ZMod 180) - y) ↔
        if z180K18M6Fifth (133 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (133 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (133 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_133

theorem z180_k18_m6_allowed_iff_crt_x_134 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((134 : ZMod 180) - y) ↔
        if z180K18M6Fifth (134 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (134 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (134 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_134

theorem z180_k18_m6_allowed_iff_crt_x_135 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((135 : ZMod 180) - y) ↔
        if z180K18M6Fifth (135 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (135 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (135 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_135

theorem z180_k18_m6_allowed_iff_crt_x_136 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((136 : ZMod 180) - y) ↔
        if z180K18M6Fifth (136 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (136 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (136 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_136

theorem z180_k18_m6_allowed_iff_crt_x_137 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((137 : ZMod 180) - y) ↔
        if z180K18M6Fifth (137 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (137 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (137 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_137

theorem z180_k18_m6_allowed_iff_crt_x_138 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((138 : ZMod 180) - y) ↔
        if z180K18M6Fifth (138 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (138 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (138 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_138

theorem z180_k18_m6_allowed_iff_crt_x_139 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((139 : ZMod 180) - y) ↔
        if z180K18M6Fifth (139 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (139 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (139 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_139

end Fuglede
