-- Source: fuglede_search/z180_exact_order_evidence_20260808_v1/cores/k8.core.smt2
-- Source SHA-256: 091d2769568e1cd98181059173a903e684d2e0c58bccc965aaf7047d8b8c3e1e
-- Diagnostic single-leaf emission from the replayed exact tree.
-- Generated by fuglede_search/z180_nondivisor_omega_to_lean.py
import Mathlib.Tactic

set_option maxRecDepth 100000
set_option maxHeartbeats 0

theorem z180NondivisorK8Leaf4
    {a_0_5 a_1_1 a_1_2 a_1_3 a_1_4 a_1_5 a_1_6 a_1_9 a_1_10 a_1_12 a_1_15 a_1_18 a_1_20 a_1_30 a_1_36 a_1_45 a_1_60 a_1_90 a_1_180 : Int}
    (h56 : ((a_1_1 + a_1_2 + a_1_3 + a_1_4 + a_1_5 + a_1_6 + a_1_9 + a_1_10 + a_1_12 + a_1_15 + a_1_18 + a_1_20 + a_1_30 + a_1_36 + a_1_45 + a_1_60 + a_1_90 + a_1_180) = 64))
    (d4_pos : (a_0_5 > 0))
    (d4_zero : (((a_1_1 * 4) + (a_1_2 * 4) + (a_1_3 * 4) + (a_1_4 * 4) + (a_1_5 * (-1)) + (a_1_6 * 4) + (a_1_9 * 4) + (a_1_10 * (-1)) + (a_1_12 * 4) + (a_1_15 * (-1)) + (a_1_18 * 4) + (a_1_20 * (-1)) + (a_1_30 * (-1)) + (a_1_36 * 4) + (a_1_45 * (-1)) + (a_1_60 * (-1)) + (a_1_90 * (-1)) + (a_1_180 * (-1))) = 0))
    : False := by
  omega

#print axioms z180NondivisorK8Leaf4
