-- Generated by fuglede_search/generate_z180_k30_m36_card30_leaf_pilot_v2.py
-- Generator SHA-256: be762b92d78356ff57c991e4274d2aa6313c1e2e55a99b9d886d154cfc9a1c97
-- Full SMT SHA-256: 400d3cf664e6ff4aa9e93d635a06af334a99761768e36658815454e023db7834
-- Base121 prefix SHA-256: 77ed1ac3a743e65ede7e153b9626546696d3b05a728a22a80b337fdf5863d61f
-- Pilot only: one closed QF_LRA leaf, not the complete m36 tree.
import Mathlib.Tactic

set_option maxHeartbeats 0

namespace Fuglede

theorem z180_k30_m36_card30_dpllt_leaf_pilot
    (a_1_36 : Int)
    (hpos36 : (a_1_36 > 0))
    (d112_nonpos : (a_1_36 ≤ 0))
    : False := by
  linarith only [hpos36, d112_nonpos]

#print axioms z180_k30_m36_card30_dpllt_leaf_pilot

end Fuglede
