import Fuglede.Z180K18M12PhaseCombinatorics
import Mathlib.NumberTheory.LegendreSymbol.AddCharacter
import Mathlib.Tactic

/-!
# The primitive-twelfth character attached to frequency fifteen

This module isolates the local root-of-unity algebra used by block B.  The
standard character at frequency `15` factors through the order-twelve phase.
After orienting an order-four pair, its two character values factor as

`phaseChar a * (1 + phaseChar 3)`.

The second factor is nonzero because the underlying root has exact order
twelve.
-/

namespace Fuglede

open scoped BigOperators

/-- The primitive twelfth root supplied by the standard `ZMod 180`
character at frequency fifteen. -/
noncomputable def z180K18M12Root : ℂ :=
  ZMod.stdAddChar (15 : ZMod 180)

theorem z180K18M12Root_isPrimitive :
    IsPrimitiveRoot z180K18M12Root 12 := by
  have h := isPrimitiveRoot_stdAddChar (15 : ZMod 180)
  have horder : frequencyOrder 180 (15 : ZMod 180) = 12 := by
    decide
  simpa only [z180K18M12Root, horder] using h

@[simp]
theorem z180K18M12Root_pow_twelve : z180K18M12Root ^ 12 = 1 :=
  z180K18M12Root_isPrimitive.pow_eq_one

/-- Additive character of `ZMod 12` generated by the same primitive root. -/
noncomputable def z180K18M12PhaseChar : AddChar (ZMod 12) ℂ :=
  AddChar.zmodChar 12 z180K18M12Root_pow_twelve

@[simp]
theorem z180K18M12PhaseChar_apply (q : ZMod 12) :
    z180K18M12PhaseChar q = z180K18M12Root ^ q.val := by
  exact AddChar.zmodChar_apply z180K18M12Root_pow_twelve q

private theorem z180K18M12PointPhase_val (x : ZMod 180) :
    (z180K18M12PointPhase x).val = x.val % 12 := by
  rw [z180K18M12PointPhase, ZMod.cast_eq_val, ZMod.val_natCast]

/-- The frequency-fifteen standard character depends only on the phase
modulo twelve. -/
theorem z180K18M12PhaseChar_pointPhase (x : ZMod 180) :
    z180K18M12PhaseChar (z180K18M12PointPhase x) =
      ZMod.stdAddChar (x * (15 : ZMod 180)) := by
  rw [z180K18M12PhaseChar_apply, z180K18M12PointPhase_val]
  rw [← pow_eq_pow_mod x.val z180K18M12Root_pow_twelve]
  rw [z180K18M12Root, ← AddChar.map_nsmul_eq_pow]
  congr 1
  simpa only [nsmul_eq_mul] using
    congrArg (fun z : ZMod 180 => z * (15 : ZMod 180))
      (ZMod.natCast_zmod_val x)

/-- CRT pairing at the order-twelve base frequency is the phase character. -/
theorem z180K18M12_basePairing_eq_phaseChar (x : ZMod 180) :
    z180StandardCRTCharacterPairing (toCRT180 x)
        z180K18M12OrderTwelveBaseFrequency =
      z180K18M12PhaseChar (z180K18M12PointPhase x) := by
  rw [z180StandardCRTCharacterPairing, fromCRT180_mul,
    fromCRT180_toCRT180,
    z180K18M12OrderTwelveBaseFrequency, fromCRT180_toCRT180]
  rw [mul_comm]
  exact (z180K18M12PhaseChar_pointPhase x).symm

/-- Common nonzero factor contributed by the `+3` mate in every oriented
pair. -/
noncomputable def z180K18M12PairRootFactor : ℂ :=
  1 + z180K18M12PhaseChar 3

/-- Character factorisation for one oriented pair. -/
theorem z180K18M12_orientedPair_factor
    {A : Finset (ZMod 180)} (p : Z180K18M12PairFibres A) (r : ZMod 9) :
    z180StandardCRTCharacterPairing
        (toCRT180 (z180K18M12OrientedFirst p r))
        z180K18M12OrderTwelveBaseFrequency +
      z180StandardCRTCharacterPairing
        (toCRT180 (z180K18M12OrientedSecond p r))
        z180K18M12OrderTwelveBaseFrequency =
      z180K18M12PairRootFactor *
        z180K18M12PhaseChar (z180K18M12PairPhase p r) := by
  rw [z180K18M12_basePairing_eq_phaseChar,
    z180K18M12_basePairing_eq_phaseChar,
    z180K18M12OrientedSecond_phase,
    AddChar.map_add_eq_mul]
  unfold z180K18M12PairRootFactor z180K18M12PairPhase
  ring

/-- The common pair factor cannot vanish: otherwise the primitive twelfth
root would have sixth power one. -/
theorem z180K18M12PairRootFactor_ne_zero :
    z180K18M12PairRootFactor ≠ 0 := by
  intro hzero
  have hthree : z180K18M12Root ^ 3 = -1 := by
    have hzero' : 1 + z180K18M12Root ^ 3 = 0 := by
      rw [z180K18M12PairRootFactor, z180K18M12PhaseChar_apply] at hzero
      norm_num at hzero
      exact hzero
    calc
      z180K18M12Root ^ 3 = (1 + z180K18M12Root ^ 3) - 1 := by ring
      _ = 0 - 1 := by rw [hzero']
      _ = -1 := by ring
  have hsix : z180K18M12Root ^ 6 = 1 := by
    calc
      z180K18M12Root ^ 6 = (z180K18M12Root ^ 3) ^ 2 := by ring
      _ = (-1 : ℂ) ^ 2 := by rw [hthree]
      _ = 1 := by norm_num
  have hdvd := (z180K18M12Root_isPrimitive.pow_eq_one_iff_dvd 6).mp hsix
  norm_num at hdvd

/-- Every value of the phase character is nonzero. -/
theorem z180K18M12PhaseChar_ne_zero (q : ZMod 12) :
    z180K18M12PhaseChar q ≠ 0 := by
  intro hzero
  have hunit :
      z180K18M12PhaseChar q * z180K18M12PhaseChar (-q) = 1 := by
    rw [← AddChar.map_add_eq_mul, add_neg_cancel,
      AddChar.map_zero_eq_one]
  rw [hzero, zero_mul] at hunit
  exact zero_ne_one hunit

/-- Multiplying a normalized phase by the common shift recovers its raw
pair phase. -/
theorem z180K18M12PhaseChar_shift_mul_normalized
    {A : Finset (ZMod 180)} (p : Z180K18M12PairFibres A)
    (shift : ZMod 12) (r : ZMod 9) :
    z180K18M12PhaseChar shift *
        z180K18M12PhaseChar
          (z180K18M12NormalizedPairPhase p shift r) =
      z180K18M12PhaseChar (z180K18M12PairPhase p r) := by
  rw [← AddChar.map_add_eq_mul]
  congr 1
  unfold z180K18M12NormalizedPairPhase
  abel

#print axioms z180K18M12Root_isPrimitive
#print axioms z180K18M12PhaseChar_pointPhase
#print axioms z180K18M12_orientedPair_factor
#print axioms z180K18M12PairRootFactor_ne_zero

end Fuglede
