import Mathlib.Tactic
import Fuglede.Z180K30CommonSpectrumInterface

/-!
# Honest boundary for the exceptional K30 fibre analysis

This file contains only interfaces and propositional adapters. In particular, it
does not assert that any external analytic lemma or the finite certificate has
been formalized.

The finite auditor is scripts/audit_z180_k30_exceptional_exact.mjs. It works
exactly in Z[x] / (x^12 - x^6 + 1), without floating-point arithmetic.
-/

namespace Fuglede

/-- Reduction modulo 30. Its kernel is the six-element subgroup of ZMod 180
generated by 30. -/
def z180K30Projection30 : ZMod 180 →+ ZMod 30 :=
  (ZMod.castHom (by norm_num : 30 ∣ 180) (ZMod 30)).toAddMonoidHom

/-- The s-th projected fifth fibre is a common spectrum for all five projected
fibres of A. -/
def Z180K30CommonSpectrumAt
    (A L : Finset (ZMod 180)) (s : Fin 5) : Prop :=
  Z180K30FiveFibresHaveCommonZ36Spectrum
    (z180K30FifthFibres36 A)
    (z180K30FifthFibres36 L s)

/-- The exact external analytic boundary.

ExceptionalColumn s, ProjectiveAlternative s, and ResidueCandidate s are
deliberately abstract propositions. A future formalization must instantiate
these with the actual rank-two Fourier-block statements; this file does not
manufacture such witnesses.

The three proof fields isolate:

1. block identities plus the scalar Gram dichotomy for a fixed fibre column;
2. the rank-two unimodular/projective-class lemma;
3. identification of Fourier projective classes with residue classes in
   ZMod 36.
-/
structure Z180K30ExceptionalExternalBoundary
    (A L : Finset (ZMod 180)) where
  ExceptionalColumn : Fin 5 → Prop
  ProjectiveAlternative : Fin 5 → Prop
  ResidueCandidate : Fin 5 → Prop
  columnDichotomy :
    ∀ s, Z180K30CommonSpectrumAt A L s ∨ ExceptionalColumn s
  rankTwoProjective :
    ∀ s, ExceptionalColumn s → ProjectiveAlternative s
  fourierProjectiveClasses :
    ∀ s, ProjectiveAlternative s → ResidueCandidate s

/-- Interface exposed by the exact finite certificate.

The certificate proves only the implication from a fully specified residue
candidate for one column to the unique surviving affine orbit. The meaning of
HCosetColumn stays explicit and abstract until the coset statement itself is
formalized in Lean. -/
structure Z180K30ExactExceptionalCertificate
    {A L : Finset (ZMod 180)}
    (boundary : Z180K30ExceptionalExternalBoundary A L) where
  HCosetColumn : Fin 5 → Prop
  certifiedOnlyH :
    ∀ s, boundary.ResidueCandidate s → HCosetColumn s

/-- The remaining mathematical bridge after the finite certificate.

Its intended proof expands HCosetColumn s as saying that the s-th fifth fibre
of L is an affine copy of 6ZMod 36, rewrites L as five cosets of 30ZMod 180,
and applies the sealed K5 closure through the asymmetric ZMod 30 to ZMod 180
lift. -/
structure Z180K30ExceptionalHCaseBridge
    {A L : Finset (ZMod 180)}
    {boundary : Z180K30ExceptionalExternalBoundary A L}
    (certificate : Z180K30ExactExceptionalCertificate boundary) where
  projection30_injOn :
    (∀ s, certificate.HCosetColumn s) →
      Set.InjOn z180K30Projection30 (A : Set (ZMod 180))

/-- Honest endpoint of the exceptional analysis.

If any fibre column is in the normal Gram branch, it supplies a common
six-point spectrum. Otherwise every column is exceptional; the projective
reduction and exact certificate put every column in the unique 6ZMod 36 orbit,
and the separate H-case bridge gives injectivity modulo 30. -/
theorem z180_k30_common_spectrum_or_projection30_injOn_of_boundary
    {A L : Finset (ZMod 180)}
    (boundary : Z180K30ExceptionalExternalBoundary A L)
    (certificate : Z180K30ExactExceptionalCertificate boundary)
    (hHCase : Z180K30ExceptionalHCaseBridge certificate) :
    (∃ s, Z180K30CommonSpectrumAt A L s) ∨
      Set.InjOn z180K30Projection30 (A : Set (ZMod 180)) := by
  by_cases hcommon : ∃ s, Z180K30CommonSpectrumAt A L s
  · exact Or.inl hcommon
  · right
    apply hHCase.projection30_injOn
    intro s
    have hexceptional : boundary.ExceptionalColumn s := by
      rcases boundary.columnDichotomy s with hnormal | hexceptional
      · exact False.elim (hcommon ⟨s, hnormal⟩)
      · exact hexceptional
    exact certificate.certifiedOnlyH s <|
      boundary.fourierProjectiveClasses s <|
        boundary.rankTwoProjective s hexceptional

end Fuglede

