-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsCore

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_x_030 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((30 : ZMod 180) - y) ↔
        if z180K18M6Fifth (30 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (30 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (30 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_030

theorem z180_k18_m6_allowed_iff_crt_x_031 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((31 : ZMod 180) - y) ↔
        if z180K18M6Fifth (31 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (31 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (31 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_031

theorem z180_k18_m6_allowed_iff_crt_x_032 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((32 : ZMod 180) - y) ↔
        if z180K18M6Fifth (32 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (32 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (32 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_032

theorem z180_k18_m6_allowed_iff_crt_x_033 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((33 : ZMod 180) - y) ↔
        if z180K18M6Fifth (33 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (33 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (33 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_033

theorem z180_k18_m6_allowed_iff_crt_x_034 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((34 : ZMod 180) - y) ↔
        if z180K18M6Fifth (34 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (34 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (34 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_034

theorem z180_k18_m6_allowed_iff_crt_x_035 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((35 : ZMod 180) - y) ↔
        if z180K18M6Fifth (35 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (35 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (35 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_035

theorem z180_k18_m6_allowed_iff_crt_x_036 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((36 : ZMod 180) - y) ↔
        if z180K18M6Fifth (36 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (36 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (36 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_036

theorem z180_k18_m6_allowed_iff_crt_x_037 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((37 : ZMod 180) - y) ↔
        if z180K18M6Fifth (37 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (37 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (37 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_037

theorem z180_k18_m6_allowed_iff_crt_x_038 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((38 : ZMod 180) - y) ↔
        if z180K18M6Fifth (38 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (38 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (38 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_038

theorem z180_k18_m6_allowed_iff_crt_x_039 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((39 : ZMod 180) - y) ↔
        if z180K18M6Fifth (39 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (39 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (39 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_039

end Fuglede
