-- Generated by fuglede_search/z180_nondivisor_k24_side1c_compact_to_lean.py
-- Exact-order source SHA-256: f3725f042801cf4050bc34be20d8de185730a0bf5884708daf2c74fff37ef837
import Mathlib.Tactic
import Fuglede.Z180NondivisorSplit

set_option maxRecDepth 100000
set_option maxHeartbeats 0

/-! Compact interval-and-residue certificate for a hard side-one k=24 leaf. -/

private theorem z180NondivisorK24Side1CResidue28
    {z : Int} (h : 112 * z = -29652) : False := by
  omega

private theorem z180NondivisorK24Side1CResidue42
    {z : Int} (h : 112 * z = -34902) : False := by
  omega

private theorem z180NondivisorK24Side1CResidue56
    {z : Int} (h : 112 * z = -40152) : False := by
  omega

private theorem z180NondivisorK24Side1CArithmeticCore
    {E a45 a6 a9 a15 : Int}
    (lower : 1152 <= E)
    (upper : E <= 2304)
    (eq6 : 112 * a6 = 17856 - 5 * E - 70 * a45)
    (eq9 : 56 * a9 = 11520 - 3 * E - 21 * a45)
    (eq15 : 350 * a15 = 96192 - 31 * E - 350 * a45)
    : False := by
  let q : Int := a45 + a15
  have eq31 : 31 * E + 350 * q = 96192 := by
    dsimp [q]
    linarith only [eq15]
  let r : Int := 21720 - 7 * E - 79 * q
  have qform : q = 31 * r + 24 := by
    dsimp [r]
    linarith only [eq31]
  have Eform : E = 2832 - 350 * r := by
    linarith only [eq31, qform]
  have rlower : 2 <= r := by
    have split : r <= 1 ∨ 2 <= r := by
      exact Fuglede.z180IntSuccSplit r 1
    rcases split with low | high
    · exfalso
      linarith only [upper, Eform, low]
    · exact high
  have rupper : r <= 4 := by
    have split : r <= 4 ∨ 5 <= r := by
      exact Fuglede.z180IntSuccSplit r 4
    rcases split with low | high
    · exact low
    · exfalso
      linarith only [lower, Eform, high]
  have combined : 112 * (3 * a6 - 5 * a9) = 15 * E - 61632 := by
    linarith only [eq6, eq9]
  have split2 : r <= 2 ∨ 3 <= r := by
    exact Fuglede.z180IntSuccSplit r 2
  rcases split2 with atMost2 | atLeast3
  · have er : r = 2 := by linarith only [rlower, atMost2]
    have ee : E = 2132 := by linarith only [Eform, er]
    have residue : 112 * (3 * a6 - 5 * a9) = -29652 := by
      linarith only [combined, ee]
    exact z180NondivisorK24Side1CResidue28 residue
  · have split3 : r <= 3 ∨ 4 <= r := by
      exact Fuglede.z180IntSuccSplit r 3
    rcases split3 with atMost3 | atLeast4
    · have er : r = 3 := by linarith only [atLeast3, atMost3]
      have ee : E = 1782 := by linarith only [Eform, er]
      have residue : 112 * (3 * a6 - 5 * a9) = -34902 := by
        linarith only [combined, ee]
      exact z180NondivisorK24Side1CResidue42 residue
    · have er : r = 4 := by linarith only [atLeast4, rupper]
      have ee : E = 1432 := by linarith only [Eform, er]
      have residue : 112 * (3 * a6 - 5 * a9) = -40152 := by
        linarith only [combined, ee]
      exact z180NondivisorK24Side1CResidue56 residue

theorem z180NondivisorK24Side1CCore
    {a_1_1 a_1_2 a_1_3 a_1_4 a_1_5 a_1_6 a_1_9 a_1_10 a_1_12 a_1_15 a_1_18 a_1_20 a_1_30 a_1_36 a_1_45 a_1_60 a_1_90 a_1_180 : Int}
    (h37 : (a_1_1 = 24))
    (h38 : (a_1_2 ≥ 0))
    (h41 : (a_1_5 ≥ 0))
    (h43 : (a_1_10 ≥ 0))
    (h48 : (a_1_30 ≥ 0))
    (h51 : (a_1_90 ≥ 0))
    (h53 : ((a_1_1 + a_1_2 + a_1_3 + a_1_4 + a_1_5 + a_1_6 + a_1_9 + a_1_10 + a_1_12 + a_1_15 + a_1_18 + a_1_20 + a_1_30 + a_1_36 + a_1_45 + a_1_60 + a_1_90 + a_1_180) = 576))
    (h54 : ((a_1_1 + a_1_2 + a_1_3 + ((-1) * a_1_4) + a_1_5 + a_1_6 + a_1_9 + a_1_10 + ((-1) * a_1_12) + a_1_15 + a_1_18 + ((-1) * a_1_20) + a_1_30 + ((-1) * a_1_36) + a_1_45 + ((-1) * a_1_60) + a_1_90 + ((-1) * a_1_180)) ≥ 0))
    (d2_nonpos : (a_1_2 ≤ 0))
    (d5_nonpos : (a_1_5 ≤ 0))
    (e12 : (((a_1_1 * 4) + (a_1_2 * (-4)) + (a_1_3 * 4) + (a_1_4 * 0) + (a_1_5 * 4) + (a_1_6 * (-4)) + (a_1_9 * (-2)) + (a_1_10 * (-4)) + (a_1_12 * 0) + (a_1_15 * 4) + (a_1_18 * 2) + (a_1_20 * 0) + (a_1_30 * (-4)) + (a_1_36 * 0) + (a_1_45 * (-2)) + (a_1_60 * 0) + (a_1_90 * 2) + (a_1_180 * 0)) = 0))
    (e15 : (((a_1_1 * 8) + (a_1_2 * 8) + (a_1_3 * 8) + (a_1_4 * 8) + (a_1_5 * (-2)) + (a_1_6 * 8) + (a_1_9 * (-4)) + (a_1_10 * (-2)) + (a_1_12 * 8) + (a_1_15 * (-2)) + (a_1_18 * (-4)) + (a_1_20 * (-2)) + (a_1_30 * (-2)) + (a_1_36 * (-4)) + (a_1_45 * 1) + (a_1_60 * (-2)) + (a_1_90 * 1) + (a_1_180 * 1)) = 0))
    (e20 : (((a_1_1 * 8) + (a_1_2 * (-8)) + (a_1_3 * 8) + (a_1_4 * 0) + (a_1_5 * (-2)) + (a_1_6 * (-8)) + (a_1_9 * 8) + (a_1_10 * 2) + (a_1_12 * 0) + (a_1_15 * (-2)) + (a_1_18 * (-8)) + (a_1_20 * 0) + (a_1_30 * 2) + (a_1_36 * 0) + (a_1_45 * (-2)) + (a_1_60 * 0) + (a_1_90 * 2) + (a_1_180 * 0)) = 0))
    (e30 : (((a_1_1 * 8) + (a_1_2 * 8) + (a_1_3 * 8) + (a_1_4 * (-8)) + (a_1_5 * (-2)) + (a_1_6 * 8) + (a_1_9 * (-4)) + (a_1_10 * (-2)) + (a_1_12 * (-8)) + (a_1_15 * (-2)) + (a_1_18 * (-4)) + (a_1_20 * 2) + (a_1_30 * (-2)) + (a_1_36 * 4) + (a_1_45 * 1) + (a_1_60 * 2) + (a_1_90 * 1) + (a_1_180 * (-1))) = 0))
    (d30_nonpos : (a_1_30 ≤ 0))
    (e36 : (((a_1_1 * 12) + (a_1_2 * (-12)) + (a_1_3 * (-6)) + (a_1_4 * 0) + (a_1_5 * 12) + (a_1_6 * 6) + (a_1_9 * 0) + (a_1_10 * (-12)) + (a_1_12 * 0) + (a_1_15 * (-6)) + (a_1_18 * 0) + (a_1_20 * 0) + (a_1_30 * 6) + (a_1_36 * 0) + (a_1_45 * 0) + (a_1_60 * 0) + (a_1_90 * 0) + (a_1_180 * 0)) = 0))
    (e45 : (((a_1_1 * 24) + (a_1_2 * 24) + (a_1_3 * (-12)) + (a_1_4 * 24) + (a_1_5 * (-6)) + (a_1_6 * (-12)) + (a_1_9 * 0) + (a_1_10 * (-6)) + (a_1_12 * (-12)) + (a_1_15 * 3) + (a_1_18 * 0) + (a_1_20 * (-6)) + (a_1_30 * 3) + (a_1_36 * 0) + (a_1_45 * 0) + (a_1_60 * 3) + (a_1_90 * 0) + (a_1_180 * 0)) = 0))
    (e90 : (((a_1_1 * 24) + (a_1_2 * 24) + (a_1_3 * (-12)) + (a_1_4 * (-24)) + (a_1_5 * (-6)) + (a_1_6 * (-12)) + (a_1_9 * 0) + (a_1_10 * (-6)) + (a_1_12 * 12) + (a_1_15 * 3) + (a_1_18 * 0) + (a_1_20 * 6) + (a_1_30 * 3) + (a_1_36 * 0) + (a_1_45 * 0) + (a_1_60 * (-3)) + (a_1_90 * 0) + (a_1_180 * 0)) = 0))
    (d90_nonpos : (a_1_90 ≤ 0))
    : False := by
  have z2 : a_1_2 = 0 := by linarith only [h38, d2_nonpos]
  have z5 : a_1_5 = 0 := by linarith only [h41, d5_nonpos]
  have z30 : a_1_30 = 0 := by linarith only [h48, d30_nonpos]
  have z90 : a_1_90 = 0 := by linarith only [h51, d90_nonpos]
  let E : Int := 10 * a_1_20 + 12 * a_1_36 + 10 * a_1_60 + 7 * a_1_180
  have lower : 1152 <= E := by
    dsimp [E]
    linarith only [h37, h53, z2, z5, z30, z90, e12, e15, e20, e30, e36, e45, e90, h43]
  have upper : E <= 2304 := by
    dsimp [E]
    linarith only [h37, h53, z2, z5, z30, z90, e12, e15, e20, e30, e36, e45, e90, h54]
  have eq6 : 112 * a_1_6 = 17856 - 5 * E - 70 * a_1_45 := by
    dsimp [E]
    linarith only [h37, h53, z2, z5, z30, z90, e12, e15, e20, e30, e36, e45, e90]
  have eq9 : 56 * a_1_9 = 11520 - 3 * E - 21 * a_1_45 := by
    dsimp [E]
    linarith only [h37, h53, z2, z5, z30, z90, e12, e15, e20, e30, e36, e45, e90]
  have eq15 : 350 * a_1_15 = 96192 - 31 * E - 350 * a_1_45 := by
    dsimp [E]
    linarith only [h37, h53, z2, z5, z30, z90, e12, e15, e20, e30, e36, e45, e90]
  exact z180NondivisorK24Side1CArithmeticCore lower upper eq6 eq9 eq15

#print axioms z180NondivisorK24Side1CCore
