-- Generated by fuglede_search/generate_z180_k12_forced_typed_adapter.py
-- Generator SHA-256: 9ef46d704c8c10cee2c9fead10139a635c6649ab75e43c04635ac42b1ec12bee
import Fuglede.Z180ExactOrderTransform
import Fuglede.Z180K12ForcedDpll2
import Fuglede.Z180K12ForcedDpll4
import Mathlib.Tactic

set_option maxHeartbeats 0

/-!
# Typed forced-transform adapter for `ZMod 180`, cardinality twelve

The two sharded rational certificates exclude strict positivity of the
order-two and order-four transform rows.  Ramanujan nonnegativity therefore
forces both rows to vanish.  Spectral duality gives the same conclusion on
the spectrum side.
-/

namespace Fuglede

/-- Typed reconstruction of the contradiction to strict positivity at
order 2 on the first side of a cardinality-twelve spectral pair. -/
theorem z180_k12_side0_e2_pos_impossible_of_ramanujan
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L) (hcard : A.card = 12)
    (hidentityA : Z180RamanujanIdentity A)
    (hidentityL : Z180RamanujanIdentity L)
    (hpos : 0 < z180ExactOrderTransform A 2) : False := by
  have hcardL : L.card = 12 := by
    calc
      L.card = A.card := hSpec.2.1.symm
      _ = 12 := hcard
  have hnot5A : ¬ 5 ∣ A.card := by norm_num [hcard]
  have hnot5L : ¬ 5 ∣ L.card := by norm_num [hcardL]
  exact z180_k12_side0_e2_pos_impossible
    (cardinality := 12)
    (a_0_1 := exactOrderDistributionInt A 1)
    (a_0_2 := exactOrderDistributionInt A 2)
    (a_0_3 := exactOrderDistributionInt A 3)
    (a_0_4 := exactOrderDistributionInt A 4)
    (a_0_5 := exactOrderDistributionInt A 5)
    (a_0_6 := exactOrderDistributionInt A 6)
    (a_0_9 := exactOrderDistributionInt A 9)
    (a_0_10 := exactOrderDistributionInt A 10)
    (a_0_12 := exactOrderDistributionInt A 12)
    (a_0_15 := exactOrderDistributionInt A 15)
    (a_0_18 := exactOrderDistributionInt A 18)
    (a_0_20 := exactOrderDistributionInt A 20)
    (a_0_30 := exactOrderDistributionInt A 30)
    (a_0_36 := exactOrderDistributionInt A 36)
    (a_0_45 := exactOrderDistributionInt A 45)
    (a_0_60 := exactOrderDistributionInt A 60)
    (a_0_90 := exactOrderDistributionInt A 90)
    (a_0_180 := exactOrderDistributionInt A 180)
    (a_1_1 := exactOrderDistributionInt L 1)
    (a_1_2 := exactOrderDistributionInt L 2)
    (a_1_3 := exactOrderDistributionInt L 3)
    (a_1_4 := exactOrderDistributionInt L 4)
    (a_1_5 := exactOrderDistributionInt L 5)
    (a_1_6 := exactOrderDistributionInt L 6)
    (a_1_9 := exactOrderDistributionInt L 9)
    (a_1_10 := exactOrderDistributionInt L 10)
    (a_1_12 := exactOrderDistributionInt L 12)
    (a_1_15 := exactOrderDistributionInt L 15)
    (a_1_18 := exactOrderDistributionInt L 18)
    (a_1_20 := exactOrderDistributionInt L 20)
    (a_1_30 := exactOrderDistributionInt L 30)
    (a_1_36 := exactOrderDistributionInt L 36)
    (a_1_45 := exactOrderDistributionInt L 45)
    (a_1_60 := exactOrderDistributionInt L 60)
    (a_1_90 := exactOrderDistributionInt L 90)
    (a_1_180 := exactOrderDistributionInt L 180)
    (h1 := (by
      rw [exactOrderDistributionInt_one]
      exact_mod_cast hcard))
    (h2 := (exactOrderDistributionInt_nonneg A 2))
    (h3 := (exactOrderDistributionInt_nonneg A 3))
    (h4 := (exactOrderDistributionInt_nonneg A 4))
    (h5 := (exactOrderDistributionInt_nonneg A 5))
    (h6 := (exactOrderDistributionInt_nonneg A 6))
    (h7 := (exactOrderDistributionInt_nonneg A 9))
    (h8 := (exactOrderDistributionInt_nonneg A 10))
    (h9 := (exactOrderDistributionInt_nonneg A 12))
    (h10 := (exactOrderDistributionInt_nonneg A 15))
    (h11 := (exactOrderDistributionInt_nonneg A 18))
    (h12 := (exactOrderDistributionInt_nonneg A 20))
    (h13 := (exactOrderDistributionInt_nonneg A 30))
    (h14 := (exactOrderDistributionInt_nonneg A 36))
    (h15 := (exactOrderDistributionInt_nonneg A 45))
    (h16 := (exactOrderDistributionInt_nonneg A 60))
    (h17 := (exactOrderDistributionInt_nonneg A 90))
    (h18 := (exactOrderDistributionInt_nonneg A 180))
    (h19 := (by
      simpa [hcard] using
        (z180_sum_exactOrderDistributionInt A)))
    (h20 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 2) (by norm_num))))
    (h22 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 3) (by norm_num))))
    (h24 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 4) (by norm_num))))
    (h26 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 5) (by norm_num))))
    (h27 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_pos_five (X := A) hidentityA hnot5A)))
    (h28 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 6) (by norm_num))))
    (h29 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 9) (by norm_num))))
    (h31 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 10) (by norm_num))))
    (h32 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 12) (by norm_num))))
    (h33 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 15) (by norm_num))))
    (h34 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 18) (by norm_num))))
    (h35 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 20) (by norm_num))))
    (h36 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 30) (by norm_num))))
    (h37 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 36) (by norm_num))))
    (h38 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 45) (by norm_num))))
    (h39 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 60) (by norm_num))))
    (h40 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 90) (by norm_num))))
    (h41 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 180) (by norm_num))))
    (h42 := (by
      rw [exactOrderDistributionInt_one]
      exact_mod_cast hcardL))
    (h43 := (exactOrderDistributionInt_nonneg L 2))
    (h44 := (exactOrderDistributionInt_nonneg L 3))
    (h45 := (exactOrderDistributionInt_nonneg L 4))
    (h46 := (exactOrderDistributionInt_nonneg L 5))
    (h47 := (exactOrderDistributionInt_nonneg L 6))
    (h48 := (exactOrderDistributionInt_nonneg L 9))
    (h49 := (exactOrderDistributionInt_nonneg L 10))
    (h50 := (exactOrderDistributionInt_nonneg L 12))
    (h51 := (exactOrderDistributionInt_nonneg L 15))
    (h52 := (exactOrderDistributionInt_nonneg L 18))
    (h53 := (exactOrderDistributionInt_nonneg L 20))
    (h54 := (exactOrderDistributionInt_nonneg L 30))
    (h55 := (exactOrderDistributionInt_nonneg L 36))
    (h56 := (exactOrderDistributionInt_nonneg L 45))
    (h57 := (exactOrderDistributionInt_nonneg L 60))
    (h58 := (exactOrderDistributionInt_nonneg L 90))
    (h59 := (exactOrderDistributionInt_nonneg L 180))
    (h60 := (by
      simpa [hcardL] using
        (z180_sum_exactOrderDistributionInt L)))
    (h61 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 2) (by norm_num))))
    (h63 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 3) (by norm_num))))
    (h65 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 4) (by norm_num))))
    (h67 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 5) (by norm_num))))
    (h68 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_pos_five (X := L) hidentityL hnot5L)))
    (h69 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 6) (by norm_num))))
    (h70 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 9) (by norm_num))))
    (h72 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 10) (by norm_num))))
    (h73 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 12) (by norm_num))))
    (h74 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 15) (by norm_num))))
    (h75 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 18) (by norm_num))))
    (h76 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 20) (by norm_num))))
    (h77 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 30) (by norm_num))))
    (h78 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 36) (by norm_num))))
    (h79 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 45) (by norm_num))))
    (h80 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 60) (by norm_num))))
    (h81 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 90) (by norm_num))))
    (h82 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 180) (by norm_num))))
    (h83 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 2) (by norm_num) (by norm_num) hdistribution)))
    (h84 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 2) (by norm_num) (by norm_num) hdistribution)))
    (h85 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 3) (by norm_num) (by norm_num) hdistribution)))
    (h86 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 3) (by norm_num) (by norm_num) hdistribution)))
    (h87 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 4) (by norm_num) (by norm_num) hdistribution)))
    (h88 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 4) (by norm_num) (by norm_num) hdistribution)))
    (h89 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 5) (by norm_num) (by norm_num) hdistribution)))
    (h90 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 5) (by norm_num) (by norm_num) hdistribution)))
    (h91 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 6) (by norm_num) (by norm_num) hdistribution)))
    (h92 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 6) (by norm_num) (by norm_num) hdistribution)))
    (h93 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 9) (by norm_num) (by norm_num) hdistribution)))
    (h94 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 9) (by norm_num) (by norm_num) hdistribution)))
    (h95 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 10) (by norm_num) (by norm_num) hdistribution)))
    (h96 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 10) (by norm_num) (by norm_num) hdistribution)))
    (h97 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 12) (by norm_num) (by norm_num) hdistribution)))
    (h98 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 12) (by norm_num) (by norm_num) hdistribution)))
    (h99 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 15) (by norm_num) (by norm_num) hdistribution)))
    (h100 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 15) (by norm_num) (by norm_num) hdistribution)))
    (h101 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 18) (by norm_num) (by norm_num) hdistribution)))
    (h102 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 18) (by norm_num) (by norm_num) hdistribution)))
    (h103 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 20) (by norm_num) (by norm_num) hdistribution)))
    (h104 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 20) (by norm_num) (by norm_num) hdistribution)))
    (h105 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 30) (by norm_num) (by norm_num) hdistribution)))
    (h106 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 30) (by norm_num) (by norm_num) hdistribution)))
    (h107 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 36) (by norm_num) (by norm_num) hdistribution)))
    (h108 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 36) (by norm_num) (by norm_num) hdistribution)))
    (h109 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 45) (by norm_num) (by norm_num) hdistribution)))
    (h110 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 45) (by norm_num) (by norm_num) hdistribution)))
    (h111 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 60) (by norm_num) (by norm_num) hdistribution)))
    (h112 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 60) (by norm_num) (by norm_num) hdistribution)))
    (h113 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 90) (by norm_num) (by norm_num) hdistribution)))
    (h114 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 90) (by norm_num) (by norm_num) hdistribution)))
    (h115 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 180) (by norm_num) (by norm_num) hdistribution)))
    (h116 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 180) (by norm_num) (by norm_num) hdistribution)))
    (h117 := (by simpa [z180ExactOrderTransform, mul_comm] using hpos))

/-- Typed reconstruction of the contradiction to strict positivity at
order 4 on the first side of a cardinality-twelve spectral pair. -/
theorem z180_k12_side0_e4_pos_impossible_of_ramanujan
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L) (hcard : A.card = 12)
    (hidentityA : Z180RamanujanIdentity A)
    (hidentityL : Z180RamanujanIdentity L)
    (hpos : 0 < z180ExactOrderTransform A 4) : False := by
  have hcardL : L.card = 12 := by
    calc
      L.card = A.card := hSpec.2.1.symm
      _ = 12 := hcard
  have hnot5A : ¬ 5 ∣ A.card := by norm_num [hcard]
  have hnot5L : ¬ 5 ∣ L.card := by norm_num [hcardL]
  exact z180_k12_side0_e4_pos_impossible
    (cardinality := 12)
    (a_0_1 := exactOrderDistributionInt A 1)
    (a_0_2 := exactOrderDistributionInt A 2)
    (a_0_3 := exactOrderDistributionInt A 3)
    (a_0_4 := exactOrderDistributionInt A 4)
    (a_0_5 := exactOrderDistributionInt A 5)
    (a_0_6 := exactOrderDistributionInt A 6)
    (a_0_9 := exactOrderDistributionInt A 9)
    (a_0_10 := exactOrderDistributionInt A 10)
    (a_0_12 := exactOrderDistributionInt A 12)
    (a_0_15 := exactOrderDistributionInt A 15)
    (a_0_18 := exactOrderDistributionInt A 18)
    (a_0_20 := exactOrderDistributionInt A 20)
    (a_0_30 := exactOrderDistributionInt A 30)
    (a_0_36 := exactOrderDistributionInt A 36)
    (a_0_45 := exactOrderDistributionInt A 45)
    (a_0_60 := exactOrderDistributionInt A 60)
    (a_0_90 := exactOrderDistributionInt A 90)
    (a_0_180 := exactOrderDistributionInt A 180)
    (a_1_1 := exactOrderDistributionInt L 1)
    (a_1_2 := exactOrderDistributionInt L 2)
    (a_1_3 := exactOrderDistributionInt L 3)
    (a_1_4 := exactOrderDistributionInt L 4)
    (a_1_5 := exactOrderDistributionInt L 5)
    (a_1_6 := exactOrderDistributionInt L 6)
    (a_1_9 := exactOrderDistributionInt L 9)
    (a_1_10 := exactOrderDistributionInt L 10)
    (a_1_12 := exactOrderDistributionInt L 12)
    (a_1_15 := exactOrderDistributionInt L 15)
    (a_1_18 := exactOrderDistributionInt L 18)
    (a_1_20 := exactOrderDistributionInt L 20)
    (a_1_30 := exactOrderDistributionInt L 30)
    (a_1_36 := exactOrderDistributionInt L 36)
    (a_1_45 := exactOrderDistributionInt L 45)
    (a_1_60 := exactOrderDistributionInt L 60)
    (a_1_90 := exactOrderDistributionInt L 90)
    (a_1_180 := exactOrderDistributionInt L 180)
    (h1 := (by
      rw [exactOrderDistributionInt_one]
      exact_mod_cast hcard))
    (h2 := (exactOrderDistributionInt_nonneg A 2))
    (h3 := (exactOrderDistributionInt_nonneg A 3))
    (h4 := (exactOrderDistributionInt_nonneg A 4))
    (h5 := (exactOrderDistributionInt_nonneg A 5))
    (h6 := (exactOrderDistributionInt_nonneg A 6))
    (h7 := (exactOrderDistributionInt_nonneg A 9))
    (h8 := (exactOrderDistributionInt_nonneg A 10))
    (h9 := (exactOrderDistributionInt_nonneg A 12))
    (h10 := (exactOrderDistributionInt_nonneg A 15))
    (h11 := (exactOrderDistributionInt_nonneg A 18))
    (h12 := (exactOrderDistributionInt_nonneg A 20))
    (h13 := (exactOrderDistributionInt_nonneg A 30))
    (h14 := (exactOrderDistributionInt_nonneg A 36))
    (h15 := (exactOrderDistributionInt_nonneg A 45))
    (h16 := (exactOrderDistributionInt_nonneg A 60))
    (h17 := (exactOrderDistributionInt_nonneg A 90))
    (h18 := (exactOrderDistributionInt_nonneg A 180))
    (h19 := (by
      simpa [hcard] using
        (z180_sum_exactOrderDistributionInt A)))
    (h20 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 2) (by norm_num))))
    (h22 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 3) (by norm_num))))
    (h24 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 4) (by norm_num))))
    (h26 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 5) (by norm_num))))
    (h27 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_pos_five (X := A) hidentityA hnot5A)))
    (h28 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 6) (by norm_num))))
    (h29 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 9) (by norm_num))))
    (h31 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 10) (by norm_num))))
    (h32 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 12) (by norm_num))))
    (h33 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 15) (by norm_num))))
    (h34 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 18) (by norm_num))))
    (h35 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 20) (by norm_num))))
    (h36 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 30) (by norm_num))))
    (h37 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 36) (by norm_num))))
    (h38 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 45) (by norm_num))))
    (h39 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 60) (by norm_num))))
    (h40 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 90) (by norm_num))))
    (h41 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 180) (by norm_num))))
    (h42 := (by
      rw [exactOrderDistributionInt_one]
      exact_mod_cast hcardL))
    (h43 := (exactOrderDistributionInt_nonneg L 2))
    (h44 := (exactOrderDistributionInt_nonneg L 3))
    (h45 := (exactOrderDistributionInt_nonneg L 4))
    (h46 := (exactOrderDistributionInt_nonneg L 5))
    (h47 := (exactOrderDistributionInt_nonneg L 6))
    (h48 := (exactOrderDistributionInt_nonneg L 9))
    (h49 := (exactOrderDistributionInt_nonneg L 10))
    (h50 := (exactOrderDistributionInt_nonneg L 12))
    (h51 := (exactOrderDistributionInt_nonneg L 15))
    (h52 := (exactOrderDistributionInt_nonneg L 18))
    (h53 := (exactOrderDistributionInt_nonneg L 20))
    (h54 := (exactOrderDistributionInt_nonneg L 30))
    (h55 := (exactOrderDistributionInt_nonneg L 36))
    (h56 := (exactOrderDistributionInt_nonneg L 45))
    (h57 := (exactOrderDistributionInt_nonneg L 60))
    (h58 := (exactOrderDistributionInt_nonneg L 90))
    (h59 := (exactOrderDistributionInt_nonneg L 180))
    (h60 := (by
      simpa [hcardL] using
        (z180_sum_exactOrderDistributionInt L)))
    (h61 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 2) (by norm_num))))
    (h63 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 3) (by norm_num))))
    (h65 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 4) (by norm_num))))
    (h67 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 5) (by norm_num))))
    (h68 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_pos_five (X := L) hidentityL hnot5L)))
    (h69 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 6) (by norm_num))))
    (h70 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 9) (by norm_num))))
    (h72 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 10) (by norm_num))))
    (h73 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 12) (by norm_num))))
    (h74 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 15) (by norm_num))))
    (h75 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 18) (by norm_num))))
    (h76 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 20) (by norm_num))))
    (h77 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 30) (by norm_num))))
    (h78 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 36) (by norm_num))))
    (h79 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 45) (by norm_num))))
    (h80 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 60) (by norm_num))))
    (h81 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 90) (by norm_num))))
    (h82 := (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 180) (by norm_num))))
    (h83 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 2) (by norm_num) (by norm_num) hdistribution)))
    (h84 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 2) (by norm_num) (by norm_num) hdistribution)))
    (h85 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 3) (by norm_num) (by norm_num) hdistribution)))
    (h86 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 3) (by norm_num) (by norm_num) hdistribution)))
    (h87 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 4) (by norm_num) (by norm_num) hdistribution)))
    (h88 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 4) (by norm_num) (by norm_num) hdistribution)))
    (h89 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 5) (by norm_num) (by norm_num) hdistribution)))
    (h90 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 5) (by norm_num) (by norm_num) hdistribution)))
    (h91 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 6) (by norm_num) (by norm_num) hdistribution)))
    (h92 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 6) (by norm_num) (by norm_num) hdistribution)))
    (h93 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 9) (by norm_num) (by norm_num) hdistribution)))
    (h94 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 9) (by norm_num) (by norm_num) hdistribution)))
    (h95 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 10) (by norm_num) (by norm_num) hdistribution)))
    (h96 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 10) (by norm_num) (by norm_num) hdistribution)))
    (h97 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 12) (by norm_num) (by norm_num) hdistribution)))
    (h98 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 12) (by norm_num) (by norm_num) hdistribution)))
    (h99 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 15) (by norm_num) (by norm_num) hdistribution)))
    (h100 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 15) (by norm_num) (by norm_num) hdistribution)))
    (h101 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 18) (by norm_num) (by norm_num) hdistribution)))
    (h102 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 18) (by norm_num) (by norm_num) hdistribution)))
    (h103 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 20) (by norm_num) (by norm_num) hdistribution)))
    (h104 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 20) (by norm_num) (by norm_num) hdistribution)))
    (h105 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 30) (by norm_num) (by norm_num) hdistribution)))
    (h106 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 30) (by norm_num) (by norm_num) hdistribution)))
    (h107 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 36) (by norm_num) (by norm_num) hdistribution)))
    (h108 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 36) (by norm_num) (by norm_num) hdistribution)))
    (h109 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 45) (by norm_num) (by norm_num) hdistribution)))
    (h110 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 45) (by norm_num) (by norm_num) hdistribution)))
    (h111 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 60) (by norm_num) (by norm_num) hdistribution)))
    (h112 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 60) (by norm_num) (by norm_num) hdistribution)))
    (h113 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 90) (by norm_num) (by norm_num) hdistribution)))
    (h114 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 90) (by norm_num) (by norm_num) hdistribution)))
    (h115 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 180) (by norm_num) (by norm_num) hdistribution)))
    (h116 := (by
      intro hdistribution
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 180) (by norm_num) (by norm_num) hdistribution)))
    (h117 := (by simpa [z180ExactOrderTransform, mul_comm] using hpos))

/-- The four transform zeros forced at cardinality twelve, conditional only on
the two Ramanujan identities. -/
theorem z180_k12_forced_transform_zeros_of_spectral_of_ramanujan
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L) (hcard : A.card = 12)
    (hidentityA : Z180RamanujanIdentity A)
    (hidentityL : Z180RamanujanIdentity L) :
    z180ExactOrderTransform A 2 = 0 ∧
      z180ExactOrderTransform A 4 = 0 ∧
      z180ExactOrderTransform L 2 = 0 ∧
      z180ExactOrderTransform L 4 = 0 := by
  have hcardL : L.card = 12 := by
    calc
      L.card = A.card := hSpec.2.1.symm
      _ = 12 := hcard
  have hA2 : z180ExactOrderTransform A 2 = 0 := by
    have hnonneg := z180ExactOrderTransform_nonneg hidentityA
      (e := 2) (by norm_num)
    by_contra hne
    apply z180_k12_side0_e2_pos_impossible_of_ramanujan
      hSpec hcard hidentityA hidentityL
    omega
  have hA4 : z180ExactOrderTransform A 4 = 0 := by
    have hnonneg := z180ExactOrderTransform_nonneg hidentityA
      (e := 4) (by norm_num)
    by_contra hne
    apply z180_k12_side0_e4_pos_impossible_of_ramanujan
      hSpec hcard hidentityA hidentityL
    omega
  have hL2 : z180ExactOrderTransform L 2 = 0 := by
    have hnonneg := z180ExactOrderTransform_nonneg hidentityL
      (e := 2) (by norm_num)
    by_contra hne
    apply z180_k12_side0_e2_pos_impossible_of_ramanujan
      (cyclotomicSpectrum_dual hSpec) hcardL hidentityL hidentityA
    omega
  have hL4 : z180ExactOrderTransform L 4 = 0 := by
    have hnonneg := z180ExactOrderTransform_nonneg hidentityL
      (e := 4) (by norm_num)
    by_contra hne
    apply z180_k12_side0_e4_pos_impossible_of_ramanujan
      (cyclotomicSpectrum_dual hSpec) hcardL hidentityL hidentityA
    omega
  exact ⟨hA2, hA4, hL2, hL4⟩

#print axioms z180_k12_side0_e2_pos_impossible_of_ramanujan
#print axioms z180_k12_side0_e4_pos_impossible_of_ramanujan
#print axioms z180_k12_forced_transform_zeros_of_spectral_of_ramanujan

end Fuglede
