-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsCore

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_x_110 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((110 : ZMod 180) - y) ↔
        if z180K18M6Fifth (110 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (110 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (110 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_110

theorem z180_k18_m6_allowed_iff_crt_x_111 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((111 : ZMod 180) - y) ↔
        if z180K18M6Fifth (111 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (111 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (111 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_111

theorem z180_k18_m6_allowed_iff_crt_x_112 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((112 : ZMod 180) - y) ↔
        if z180K18M6Fifth (112 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (112 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (112 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_112

theorem z180_k18_m6_allowed_iff_crt_x_113 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((113 : ZMod 180) - y) ↔
        if z180K18M6Fifth (113 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (113 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (113 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_113

theorem z180_k18_m6_allowed_iff_crt_x_114 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((114 : ZMod 180) - y) ↔
        if z180K18M6Fifth (114 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (114 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (114 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_114

theorem z180_k18_m6_allowed_iff_crt_x_115 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((115 : ZMod 180) - y) ↔
        if z180K18M6Fifth (115 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (115 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (115 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_115

theorem z180_k18_m6_allowed_iff_crt_x_116 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((116 : ZMod 180) - y) ↔
        if z180K18M6Fifth (116 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (116 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (116 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_116

theorem z180_k18_m6_allowed_iff_crt_x_117 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((117 : ZMod 180) - y) ↔
        if z180K18M6Fifth (117 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (117 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (117 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_117

theorem z180_k18_m6_allowed_iff_crt_x_118 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((118 : ZMod 180) - y) ↔
        if z180K18M6Fifth (118 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (118 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (118 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_118

theorem z180_k18_m6_allowed_iff_crt_x_119 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((119 : ZMod 180) - y) ↔
        if z180K18M6Fifth (119 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (119 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (119 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_119

end Fuglede
