-- Generated by fuglede_search/generate_z180_k9_typed_adapter.py
-- Generator SHA-256: a46b2b58d95061a877e28b80c47944556b0092d664d716cb97ee1bc9a841b501
import Fuglede.Z180ExactOrderTransform
import Fuglede.Z180K9Dpll
import Fuglede.ProjectionTiling
import Mathlib.Tactic

set_option maxHeartbeats 0

/-!
# Typed adapter for the `ZMod 180`, cardinality-nine DPLL certificate

This module instantiates every arithmetic variable with the exact-order inner
distribution of a genuine spectral pair.  The only explicit hypotheses not
already derived from `CyclotomicSpectrum` are `Z180RamanujanIdentity A` and
`Z180RamanujanIdentity L`, the isolated transform identity named in
`Z180ExactOrderTransform`.
-/

namespace Fuglede

/-- A nonzero element in the kernel of `ZMod 180 -> ZMod 9` has one of the
five nontrivial orders dividing twenty. -/
theorem z180_frequencyOrder_mem_of_cast9_eq :
    ∀ x y : ZMod 180,
      x ≠ y →
      (ZMod.cast x : ZMod 9) = ZMod.cast y →
      frequencyOrder 180 (x - y) ∈ ({2, 4, 5, 10, 20} : Finset Nat) := by
  intro x y hxy hcast
  have hcastZero : (ZMod.cast (x - y) : ZMod 9) = 0 := by
    rw [ZMod.cast_sub (by norm_num : 9 ∣ 180), hcast, sub_self]
  have hnatCastZero : ((x - y).val : ZMod 9) = 0 := by
    simpa only [ZMod.cast_eq_val] using hcastZero
  have hdvd : 9 ∣ (x - y).val :=
    (ZMod.natCast_eq_zero_iff (x - y).val 9).1 hnatCastZero
  obtain ⟨k, hk⟩ := hdvd
  have hvalne : (x - y).val ≠ 0 := by
    intro hzero
    have hdiff : x - y = 0 := (ZMod.val_eq_zero (x - y)).1 hzero
    exact hxy (sub_eq_zero.mp hdiff)
  have hkpos : 0 < k := by omega
  have hklt : k < 20 := by
    have hvalLt := (x - y).val_lt
    omega
  unfold frequencyOrder
  rw [hk]
  interval_cases k <;> norm_num at hkpos ⊢

/-- A concrete collision modulo nine gives the strict collision-mass row used
by the arithmetic certificate. -/
theorem z180_k9_collision_mass_pos
    (A : Finset (ZMod 180)) {x y : ZMod 180}
    (hx : x ∈ A) (hy : y ∈ A) (hxy : x ≠ y)
    (hcast : (ZMod.cast x : ZMod 9) = ZMod.cast y) :
    0 < exactOrderDistributionInt A 2 +
      exactOrderDistributionInt A 4 +
      exactOrderDistributionInt A 5 +
      exactOrderDistributionInt A 10 +
      exactOrderDistributionInt A 20 := by
  have he : frequencyOrder 180 (x - y) ∈
      ({2, 4, 5, 10, 20} : Finset Nat) :=
    z180_frequencyOrder_mem_of_cast9_eq x y hxy hcast
  have hpair : (x, y) ∈
      exactOrderPairs A (frequencyOrder 180 (x - y)) := by
    simp [exactOrderPairs, hx, hy]
  have hposNat : 0 <
      exactOrderDistribution A (frequencyOrder 180 (x - y)) :=
    Finset.card_pos.mpr ⟨(x, y), hpair⟩
  have hpos : 0 <
      exactOrderDistributionInt A (frequencyOrder 180 (x - y)) := by
    change 0 <
      (exactOrderDistribution A (frequencyOrder 180 (x - y)) : Int)
    exact_mod_cast hposNat
  have h2 := exactOrderDistributionInt_nonneg A 2
  have h4 := exactOrderDistributionInt_nonneg A 4
  have h5 := exactOrderDistributionInt_nonneg A 5
  have h10 := exactOrderDistributionInt_nonneg A 10
  have h20 := exactOrderDistributionInt_nonneg A 20
  simp only [Finset.mem_insert, Finset.mem_singleton] at he
  rcases he with he | he | he | he | he
  · rw [he] at hpos
    omega
  · rw [he] at hpos
    omega
  · rw [he] at hpos
    omega
  · rw [he] at hpos
    omega
  · rw [he] at hpos
    omega

/-- The fully typed instantiation of the sealed rational DPLL refutation. -/
theorem z180_k9_nontransversal_impossible_of_ramanujan
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L) (hcard : A.card = 9)
    (hidentityA : Z180RamanujanIdentity A)
    (hidentityL : Z180RamanujanIdentity L)
    (hcollision : 0 < exactOrderDistributionInt A 2 +
      exactOrderDistributionInt A 4 +
      exactOrderDistributionInt A 5 +
      exactOrderDistributionInt A 10 +
      exactOrderDistributionInt A 20) : False := by
  have hcardL : L.card = 9 := by
    calc
      L.card = A.card := hSpec.2.1.symm
      _ = 9 := hcard
  have hnot2A : ¬ 2 ∣ A.card := by norm_num [hcard]
  have hnot2L : ¬ 2 ∣ L.card := by norm_num [hcardL]
  have hnot5A : ¬ 5 ∣ A.card := by norm_num [hcard]
  have hnot5L : ¬ 5 ∣ L.card := by norm_num [hcardL]
  exact z180_k9_nontransversal_impossible
    (a_0_1 := exactOrderDistributionInt A 1)
    (a_0_2 := exactOrderDistributionInt A 2)
    (a_0_3 := exactOrderDistributionInt A 3)
    (a_0_4 := exactOrderDistributionInt A 4)
    (a_0_5 := exactOrderDistributionInt A 5)
    (a_0_6 := exactOrderDistributionInt A 6)
    (a_0_9 := exactOrderDistributionInt A 9)
    (a_0_10 := exactOrderDistributionInt A 10)
    (a_0_12 := exactOrderDistributionInt A 12)
    (a_0_15 := exactOrderDistributionInt A 15)
    (a_0_18 := exactOrderDistributionInt A 18)
    (a_0_20 := exactOrderDistributionInt A 20)
    (a_0_30 := exactOrderDistributionInt A 30)
    (a_0_36 := exactOrderDistributionInt A 36)
    (a_0_45 := exactOrderDistributionInt A 45)
    (a_0_60 := exactOrderDistributionInt A 60)
    (a_0_90 := exactOrderDistributionInt A 90)
    (a_0_180 := exactOrderDistributionInt A 180)
    (a_1_1 := exactOrderDistributionInt L 1)
    (a_1_2 := exactOrderDistributionInt L 2)
    (a_1_3 := exactOrderDistributionInt L 3)
    (a_1_4 := exactOrderDistributionInt L 4)
    (a_1_5 := exactOrderDistributionInt L 5)
    (a_1_6 := exactOrderDistributionInt L 6)
    (a_1_9 := exactOrderDistributionInt L 9)
    (a_1_10 := exactOrderDistributionInt L 10)
    (a_1_12 := exactOrderDistributionInt L 12)
    (a_1_15 := exactOrderDistributionInt L 15)
    (a_1_18 := exactOrderDistributionInt L 18)
    (a_1_20 := exactOrderDistributionInt L 20)
    (a_1_30 := exactOrderDistributionInt L 30)
    (a_1_36 := exactOrderDistributionInt L 36)
    (a_1_45 := exactOrderDistributionInt L 45)
    (a_1_60 := exactOrderDistributionInt L 60)
    (a_1_90 := exactOrderDistributionInt L 90)
    (a_1_180 := exactOrderDistributionInt L 180)
    (by
      rw [exactOrderDistributionInt_one]
      exact_mod_cast hcard)
    (by
      simpa [hcard] using
        (z180_sum_exactOrderDistributionInt A))
    (exactOrderDistributionInt_nonneg A 2)
    (exactOrderDistributionInt_nonneg A 3)
    (exactOrderDistributionInt_nonneg A 4)
    (exactOrderDistributionInt_nonneg A 5)
    (exactOrderDistributionInt_nonneg A 6)
    (exactOrderDistributionInt_nonneg A 9)
    (exactOrderDistributionInt_nonneg A 10)
    (exactOrderDistributionInt_nonneg A 12)
    (exactOrderDistributionInt_nonneg A 15)
    (exactOrderDistributionInt_nonneg A 18)
    (exactOrderDistributionInt_nonneg A 20)
    (exactOrderDistributionInt_nonneg A 30)
    (exactOrderDistributionInt_nonneg A 36)
    (exactOrderDistributionInt_nonneg A 45)
    (exactOrderDistributionInt_nonneg A 60)
    (exactOrderDistributionInt_nonneg A 90)
    (exactOrderDistributionInt_nonneg A 180)
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 2) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_pos_two (X := A) hidentityA hnot2A))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 3) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 4) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_pos_four (X := A) hidentityA hnot2A))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 5) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_pos_five (X := A) hidentityA hnot5A))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 6) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 9) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 10) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 12) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 15) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 18) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 20) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 30) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 36) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 45) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 60) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 90) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := A) hidentityA (e := 180) (by norm_num)))
    (by
      rw [exactOrderDistributionInt_one]
      exact_mod_cast hcardL)
    (by
      simpa [hcardL] using
        (z180_sum_exactOrderDistributionInt L))
    (exactOrderDistributionInt_nonneg L 2)
    (exactOrderDistributionInt_nonneg L 3)
    (exactOrderDistributionInt_nonneg L 4)
    (exactOrderDistributionInt_nonneg L 5)
    (exactOrderDistributionInt_nonneg L 6)
    (exactOrderDistributionInt_nonneg L 9)
    (exactOrderDistributionInt_nonneg L 10)
    (exactOrderDistributionInt_nonneg L 12)
    (exactOrderDistributionInt_nonneg L 15)
    (exactOrderDistributionInt_nonneg L 18)
    (exactOrderDistributionInt_nonneg L 20)
    (exactOrderDistributionInt_nonneg L 30)
    (exactOrderDistributionInt_nonneg L 36)
    (exactOrderDistributionInt_nonneg L 45)
    (exactOrderDistributionInt_nonneg L 60)
    (exactOrderDistributionInt_nonneg L 90)
    (exactOrderDistributionInt_nonneg L 180)
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 2) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_pos_two (X := L) hidentityL hnot2L))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 3) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 4) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_pos_four (X := L) hidentityL hnot2L))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 5) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_pos_five (X := L) hidentityL hnot5L))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 6) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 9) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 10) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 12) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 15) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 18) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 20) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 30) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 36) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 45) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 60) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 90) (by norm_num)))
    (by simpa [z180ExactOrderTransform] using
      (z180ExactOrderTransform_nonneg (X := L) hidentityL (e := 180) (by norm_num)))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 2) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 2) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 3) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 3) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 4) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 4) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 5) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 5) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 6) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 6) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 9) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 9) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 10) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 10) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 12) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 12) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 15) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 15) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 18) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 18) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 20) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 20) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 30) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 30) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 36) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 36) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 45) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 45) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 60) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 60) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 90) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 90) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec hidentityL
          (e := 180) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec hidentityA
          (e := 180) (by norm_num) (by norm_num) hpos))
    hcollision

/-- Every cardinality-nine spectral set in `ZMod 180` is a complete
transversal modulo nine, conditional only on the two Ramanujan identities. -/
theorem z180_k9_projection9_injOn_of_spectral_of_ramanujan
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L) (hcard : A.card = 9)
    (hidentityA : Z180RamanujanIdentity A)
    (hidentityL : Z180RamanujanIdentity L) :
    Set.InjOn (fun x : ZMod 180 ↦ (ZMod.cast x : ZMod 9))
      (A : Set (ZMod 180)) := by
  intro x hx y hy hcast
  by_contra hxy
  apply z180_k9_nontransversal_impossible_of_ramanujan
    hSpec hcard hidentityA hidentityL
  exact z180_k9_collision_mass_pos A hx hy hxy hcast

/-- The injective projection makes `A` a complete transversal and hence a
tiling complement to the kernel of reduction modulo nine. -/
theorem z180_k9_tiles_projection9_kernel_of_spectral_of_ramanujan
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L) (hcard : A.card = 9)
    (hidentityA : Z180RamanujanIdentity A)
    (hidentityL : Z180RamanujanIdentity L) :
    Tiles A (kernelFinset
      (ZMod.castHom (by norm_num : 9 ∣ 180) (ZMod 9)).toAddMonoidHom) := by
  let φ : ZMod 180 →+ ZMod 9 :=
    (ZMod.castHom (by norm_num : 9 ∣ 180) (ZMod 9)).toAddMonoidHom
  apply transversal_tiles_kernel φ A
  · apply (kernel_difference_free_iff_injOn φ A).2
    have hinj := z180_k9_projection9_injOn_of_spectral_of_ramanujan
      hSpec hcard hidentityA hidentityL
    intro x hx y hy hmap
    apply hinj hx hy
    simpa [φ, ZMod.castHom_apply] using hmap
  · simpa [ZMod.card] using hcard

/-- Existential finite-tiling endpoint for the cardinality-nine branch. -/
theorem z180_k9_exists_tiling_of_spectral_of_ramanujan
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L) (hcard : A.card = 9)
    (hidentityA : Z180RamanujanIdentity A)
    (hidentityL : Z180RamanujanIdentity L) :
    ∃ B : Finset (ZMod 180), Tiles A B := by
  refine ⟨kernelFinset
    (ZMod.castHom (by norm_num : 9 ∣ 180) (ZMod 9)).toAddMonoidHom, ?_⟩
  exact z180_k9_tiles_projection9_kernel_of_spectral_of_ramanujan
    hSpec hcard hidentityA hidentityL

#print axioms z180_k9_projection9_injOn_of_spectral_of_ramanujan
#print axioms z180_k9_exists_tiling_of_spectral_of_ramanujan

end Fuglede
