-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsCore

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_x_070 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((70 : ZMod 180) - y) ↔
        if z180K18M6Fifth (70 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (70 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (70 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_070

theorem z180_k18_m6_allowed_iff_crt_x_071 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((71 : ZMod 180) - y) ↔
        if z180K18M6Fifth (71 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (71 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (71 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_071

theorem z180_k18_m6_allowed_iff_crt_x_072 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((72 : ZMod 180) - y) ↔
        if z180K18M6Fifth (72 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (72 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (72 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_072

theorem z180_k18_m6_allowed_iff_crt_x_073 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((73 : ZMod 180) - y) ↔
        if z180K18M6Fifth (73 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (73 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (73 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_073

theorem z180_k18_m6_allowed_iff_crt_x_074 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((74 : ZMod 180) - y) ↔
        if z180K18M6Fifth (74 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (74 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (74 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_074

theorem z180_k18_m6_allowed_iff_crt_x_075 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((75 : ZMod 180) - y) ↔
        if z180K18M6Fifth (75 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (75 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (75 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_075

theorem z180_k18_m6_allowed_iff_crt_x_076 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((76 : ZMod 180) - y) ↔
        if z180K18M6Fifth (76 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (76 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (76 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_076

theorem z180_k18_m6_allowed_iff_crt_x_077 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((77 : ZMod 180) - y) ↔
        if z180K18M6Fifth (77 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (77 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (77 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_077

theorem z180_k18_m6_allowed_iff_crt_x_078 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((78 : ZMod 180) - y) ↔
        if z180K18M6Fifth (78 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (78 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (78 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_078

theorem z180_k18_m6_allowed_iff_crt_x_079 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((79 : ZMod 180) - y) ↔
        if z180K18M6Fifth (79 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (79 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (79 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_079

end Fuglede
