-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsShard00
import Fuglede.Z180K18M6GraphDefsShard01
import Fuglede.Z180K18M6GraphDefsShard02
import Fuglede.Z180K18M6GraphDefsShard03
import Fuglede.Z180K18M6GraphDefsShard04
import Fuglede.Z180K18M6GraphDefsShard05
import Fuglede.Z180K18M6GraphDefsShard06
import Fuglede.Z180K18M6GraphDefsShard07
import Fuglede.Z180K18M6GraphDefsShard08
import Fuglede.Z180K18M6GraphDefsShard09
import Fuglede.Z180K18M6GraphDefsShard10
import Fuglede.Z180K18M6GraphDefsShard11
import Fuglede.Z180K18M6GraphDefsShard12
import Fuglede.Z180K18M6GraphDefsShard13
import Fuglede.Z180K18M6GraphDefsShard14
import Fuglede.Z180K18M6GraphDefsShard15
import Fuglede.Z180K18M6GraphDefsShard16
import Fuglede.Z180K18M6GraphDefsShard17

/-! Fail-closed assembly of the 180 fixed-first-coordinate CRT leaves. -/

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_relation :
    ∀ x y : ZMod 180,
      Z180K18M6AllowedDifference (x - y) ↔
        if z180K18M6Fifth x = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord x) (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord x) (z180K18M6BaseCoord y) := by
  intro x
  fin_cases x
  · exact z180_k18_m6_allowed_iff_crt_x_000
  · exact z180_k18_m6_allowed_iff_crt_x_001
  · exact z180_k18_m6_allowed_iff_crt_x_002
  · exact z180_k18_m6_allowed_iff_crt_x_003
  · exact z180_k18_m6_allowed_iff_crt_x_004
  · exact z180_k18_m6_allowed_iff_crt_x_005
  · exact z180_k18_m6_allowed_iff_crt_x_006
  · exact z180_k18_m6_allowed_iff_crt_x_007
  · exact z180_k18_m6_allowed_iff_crt_x_008
  · exact z180_k18_m6_allowed_iff_crt_x_009
  · exact z180_k18_m6_allowed_iff_crt_x_010
  · exact z180_k18_m6_allowed_iff_crt_x_011
  · exact z180_k18_m6_allowed_iff_crt_x_012
  · exact z180_k18_m6_allowed_iff_crt_x_013
  · exact z180_k18_m6_allowed_iff_crt_x_014
  · exact z180_k18_m6_allowed_iff_crt_x_015
  · exact z180_k18_m6_allowed_iff_crt_x_016
  · exact z180_k18_m6_allowed_iff_crt_x_017
  · exact z180_k18_m6_allowed_iff_crt_x_018
  · exact z180_k18_m6_allowed_iff_crt_x_019
  · exact z180_k18_m6_allowed_iff_crt_x_020
  · exact z180_k18_m6_allowed_iff_crt_x_021
  · exact z180_k18_m6_allowed_iff_crt_x_022
  · exact z180_k18_m6_allowed_iff_crt_x_023
  · exact z180_k18_m6_allowed_iff_crt_x_024
  · exact z180_k18_m6_allowed_iff_crt_x_025
  · exact z180_k18_m6_allowed_iff_crt_x_026
  · exact z180_k18_m6_allowed_iff_crt_x_027
  · exact z180_k18_m6_allowed_iff_crt_x_028
  · exact z180_k18_m6_allowed_iff_crt_x_029
  · exact z180_k18_m6_allowed_iff_crt_x_030
  · exact z180_k18_m6_allowed_iff_crt_x_031
  · exact z180_k18_m6_allowed_iff_crt_x_032
  · exact z180_k18_m6_allowed_iff_crt_x_033
  · exact z180_k18_m6_allowed_iff_crt_x_034
  · exact z180_k18_m6_allowed_iff_crt_x_035
  · exact z180_k18_m6_allowed_iff_crt_x_036
  · exact z180_k18_m6_allowed_iff_crt_x_037
  · exact z180_k18_m6_allowed_iff_crt_x_038
  · exact z180_k18_m6_allowed_iff_crt_x_039
  · exact z180_k18_m6_allowed_iff_crt_x_040
  · exact z180_k18_m6_allowed_iff_crt_x_041
  · exact z180_k18_m6_allowed_iff_crt_x_042
  · exact z180_k18_m6_allowed_iff_crt_x_043
  · exact z180_k18_m6_allowed_iff_crt_x_044
  · exact z180_k18_m6_allowed_iff_crt_x_045
  · exact z180_k18_m6_allowed_iff_crt_x_046
  · exact z180_k18_m6_allowed_iff_crt_x_047
  · exact z180_k18_m6_allowed_iff_crt_x_048
  · exact z180_k18_m6_allowed_iff_crt_x_049
  · exact z180_k18_m6_allowed_iff_crt_x_050
  · exact z180_k18_m6_allowed_iff_crt_x_051
  · exact z180_k18_m6_allowed_iff_crt_x_052
  · exact z180_k18_m6_allowed_iff_crt_x_053
  · exact z180_k18_m6_allowed_iff_crt_x_054
  · exact z180_k18_m6_allowed_iff_crt_x_055
  · exact z180_k18_m6_allowed_iff_crt_x_056
  · exact z180_k18_m6_allowed_iff_crt_x_057
  · exact z180_k18_m6_allowed_iff_crt_x_058
  · exact z180_k18_m6_allowed_iff_crt_x_059
  · exact z180_k18_m6_allowed_iff_crt_x_060
  · exact z180_k18_m6_allowed_iff_crt_x_061
  · exact z180_k18_m6_allowed_iff_crt_x_062
  · exact z180_k18_m6_allowed_iff_crt_x_063
  · exact z180_k18_m6_allowed_iff_crt_x_064
  · exact z180_k18_m6_allowed_iff_crt_x_065
  · exact z180_k18_m6_allowed_iff_crt_x_066
  · exact z180_k18_m6_allowed_iff_crt_x_067
  · exact z180_k18_m6_allowed_iff_crt_x_068
  · exact z180_k18_m6_allowed_iff_crt_x_069
  · exact z180_k18_m6_allowed_iff_crt_x_070
  · exact z180_k18_m6_allowed_iff_crt_x_071
  · exact z180_k18_m6_allowed_iff_crt_x_072
  · exact z180_k18_m6_allowed_iff_crt_x_073
  · exact z180_k18_m6_allowed_iff_crt_x_074
  · exact z180_k18_m6_allowed_iff_crt_x_075
  · exact z180_k18_m6_allowed_iff_crt_x_076
  · exact z180_k18_m6_allowed_iff_crt_x_077
  · exact z180_k18_m6_allowed_iff_crt_x_078
  · exact z180_k18_m6_allowed_iff_crt_x_079
  · exact z180_k18_m6_allowed_iff_crt_x_080
  · exact z180_k18_m6_allowed_iff_crt_x_081
  · exact z180_k18_m6_allowed_iff_crt_x_082
  · exact z180_k18_m6_allowed_iff_crt_x_083
  · exact z180_k18_m6_allowed_iff_crt_x_084
  · exact z180_k18_m6_allowed_iff_crt_x_085
  · exact z180_k18_m6_allowed_iff_crt_x_086
  · exact z180_k18_m6_allowed_iff_crt_x_087
  · exact z180_k18_m6_allowed_iff_crt_x_088
  · exact z180_k18_m6_allowed_iff_crt_x_089
  · exact z180_k18_m6_allowed_iff_crt_x_090
  · exact z180_k18_m6_allowed_iff_crt_x_091
  · exact z180_k18_m6_allowed_iff_crt_x_092
  · exact z180_k18_m6_allowed_iff_crt_x_093
  · exact z180_k18_m6_allowed_iff_crt_x_094
  · exact z180_k18_m6_allowed_iff_crt_x_095
  · exact z180_k18_m6_allowed_iff_crt_x_096
  · exact z180_k18_m6_allowed_iff_crt_x_097
  · exact z180_k18_m6_allowed_iff_crt_x_098
  · exact z180_k18_m6_allowed_iff_crt_x_099
  · exact z180_k18_m6_allowed_iff_crt_x_100
  · exact z180_k18_m6_allowed_iff_crt_x_101
  · exact z180_k18_m6_allowed_iff_crt_x_102
  · exact z180_k18_m6_allowed_iff_crt_x_103
  · exact z180_k18_m6_allowed_iff_crt_x_104
  · exact z180_k18_m6_allowed_iff_crt_x_105
  · exact z180_k18_m6_allowed_iff_crt_x_106
  · exact z180_k18_m6_allowed_iff_crt_x_107
  · exact z180_k18_m6_allowed_iff_crt_x_108
  · exact z180_k18_m6_allowed_iff_crt_x_109
  · exact z180_k18_m6_allowed_iff_crt_x_110
  · exact z180_k18_m6_allowed_iff_crt_x_111
  · exact z180_k18_m6_allowed_iff_crt_x_112
  · exact z180_k18_m6_allowed_iff_crt_x_113
  · exact z180_k18_m6_allowed_iff_crt_x_114
  · exact z180_k18_m6_allowed_iff_crt_x_115
  · exact z180_k18_m6_allowed_iff_crt_x_116
  · exact z180_k18_m6_allowed_iff_crt_x_117
  · exact z180_k18_m6_allowed_iff_crt_x_118
  · exact z180_k18_m6_allowed_iff_crt_x_119
  · exact z180_k18_m6_allowed_iff_crt_x_120
  · exact z180_k18_m6_allowed_iff_crt_x_121
  · exact z180_k18_m6_allowed_iff_crt_x_122
  · exact z180_k18_m6_allowed_iff_crt_x_123
  · exact z180_k18_m6_allowed_iff_crt_x_124
  · exact z180_k18_m6_allowed_iff_crt_x_125
  · exact z180_k18_m6_allowed_iff_crt_x_126
  · exact z180_k18_m6_allowed_iff_crt_x_127
  · exact z180_k18_m6_allowed_iff_crt_x_128
  · exact z180_k18_m6_allowed_iff_crt_x_129
  · exact z180_k18_m6_allowed_iff_crt_x_130
  · exact z180_k18_m6_allowed_iff_crt_x_131
  · exact z180_k18_m6_allowed_iff_crt_x_132
  · exact z180_k18_m6_allowed_iff_crt_x_133
  · exact z180_k18_m6_allowed_iff_crt_x_134
  · exact z180_k18_m6_allowed_iff_crt_x_135
  · exact z180_k18_m6_allowed_iff_crt_x_136
  · exact z180_k18_m6_allowed_iff_crt_x_137
  · exact z180_k18_m6_allowed_iff_crt_x_138
  · exact z180_k18_m6_allowed_iff_crt_x_139
  · exact z180_k18_m6_allowed_iff_crt_x_140
  · exact z180_k18_m6_allowed_iff_crt_x_141
  · exact z180_k18_m6_allowed_iff_crt_x_142
  · exact z180_k18_m6_allowed_iff_crt_x_143
  · exact z180_k18_m6_allowed_iff_crt_x_144
  · exact z180_k18_m6_allowed_iff_crt_x_145
  · exact z180_k18_m6_allowed_iff_crt_x_146
  · exact z180_k18_m6_allowed_iff_crt_x_147
  · exact z180_k18_m6_allowed_iff_crt_x_148
  · exact z180_k18_m6_allowed_iff_crt_x_149
  · exact z180_k18_m6_allowed_iff_crt_x_150
  · exact z180_k18_m6_allowed_iff_crt_x_151
  · exact z180_k18_m6_allowed_iff_crt_x_152
  · exact z180_k18_m6_allowed_iff_crt_x_153
  · exact z180_k18_m6_allowed_iff_crt_x_154
  · exact z180_k18_m6_allowed_iff_crt_x_155
  · exact z180_k18_m6_allowed_iff_crt_x_156
  · exact z180_k18_m6_allowed_iff_crt_x_157
  · exact z180_k18_m6_allowed_iff_crt_x_158
  · exact z180_k18_m6_allowed_iff_crt_x_159
  · exact z180_k18_m6_allowed_iff_crt_x_160
  · exact z180_k18_m6_allowed_iff_crt_x_161
  · exact z180_k18_m6_allowed_iff_crt_x_162
  · exact z180_k18_m6_allowed_iff_crt_x_163
  · exact z180_k18_m6_allowed_iff_crt_x_164
  · exact z180_k18_m6_allowed_iff_crt_x_165
  · exact z180_k18_m6_allowed_iff_crt_x_166
  · exact z180_k18_m6_allowed_iff_crt_x_167
  · exact z180_k18_m6_allowed_iff_crt_x_168
  · exact z180_k18_m6_allowed_iff_crt_x_169
  · exact z180_k18_m6_allowed_iff_crt_x_170
  · exact z180_k18_m6_allowed_iff_crt_x_171
  · exact z180_k18_m6_allowed_iff_crt_x_172
  · exact z180_k18_m6_allowed_iff_crt_x_173
  · exact z180_k18_m6_allowed_iff_crt_x_174
  · exact z180_k18_m6_allowed_iff_crt_x_175
  · exact z180_k18_m6_allowed_iff_crt_x_176
  · exact z180_k18_m6_allowed_iff_crt_x_177
  · exact z180_k18_m6_allowed_iff_crt_x_178
  · exact z180_k18_m6_allowed_iff_crt_x_179

#print axioms z180_k18_m6_allowed_iff_crt_relation

end Fuglede
