-- Generated by fuglede_search/z180_nondivisor_single_typed_to_lean.py
-- Generator SHA-256: 5a20b6856a64b79ac4b54b32b318db58e348ef59b788e43a3a7dca8a97190103
-- Cardinality: 13
import Fuglede.Z180ExactOrderTransformThree
import Fuglede.Z180NondivisorK13Omega
import Mathlib.Tactic

set_option maxHeartbeats 0

/-!
# Typed closure of the `k = 13` nondivisor core

Every untyped integer is instantiated by an exact-order distribution of a
genuine spectral pair.  Classification of every retained assertion is
fail-closed in the shared typed renderer.
-/

namespace Fuglede

/-- A genuine spectral pair in `ZMod 180` cannot have cardinality
`13`.  All Ramanujan identities are supplied unconditionally by
`z180RamanujanIdentity_all`. -/
theorem z180_nondivisor_k13_card_ne_of_spectral
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L) : A.card ≠ 13 := by
  intro hcard
  have hcardL : L.card = 13 := by
    calc
      L.card = A.card := hSpec.2.1.symm
      _ = 13 := hcard
  have hnot3A : ¬ 3 ∣ A.card := by norm_num [hcard]
  have hnot3L : ¬ 3 ∣ L.card := by norm_num [hcardL]
  exact z180_nondivisor_k13_impossible
    (a_0_1 := exactOrderDistributionInt A 1)
    (a_0_2 := exactOrderDistributionInt A 2)
    (a_0_3 := exactOrderDistributionInt A 3)
    (a_0_4 := exactOrderDistributionInt A 4)
    (a_0_5 := exactOrderDistributionInt A 5)
    (a_0_6 := exactOrderDistributionInt A 6)
    (a_0_9 := exactOrderDistributionInt A 9)
    (a_0_10 := exactOrderDistributionInt A 10)
    (a_0_12 := exactOrderDistributionInt A 12)
    (a_0_15 := exactOrderDistributionInt A 15)
    (a_0_18 := exactOrderDistributionInt A 18)
    (a_0_20 := exactOrderDistributionInt A 20)
    (a_0_30 := exactOrderDistributionInt A 30)
    (a_0_36 := exactOrderDistributionInt A 36)
    (a_0_45 := exactOrderDistributionInt A 45)
    (a_0_60 := exactOrderDistributionInt A 60)
    (a_0_90 := exactOrderDistributionInt A 90)
    (a_0_180 := exactOrderDistributionInt A 180)
    (a_1_1 := exactOrderDistributionInt L 1)
    (a_1_2 := exactOrderDistributionInt L 2)
    (a_1_3 := exactOrderDistributionInt L 3)
    (a_1_4 := exactOrderDistributionInt L 4)
    (a_1_5 := exactOrderDistributionInt L 5)
    (a_1_6 := exactOrderDistributionInt L 6)
    (a_1_9 := exactOrderDistributionInt L 9)
    (a_1_10 := exactOrderDistributionInt L 10)
    (a_1_12 := exactOrderDistributionInt L 12)
    (a_1_15 := exactOrderDistributionInt L 15)
    (a_1_18 := exactOrderDistributionInt L 18)
    (a_1_20 := exactOrderDistributionInt L 20)
    (a_1_30 := exactOrderDistributionInt L 30)
    (a_1_36 := exactOrderDistributionInt L 36)
    (a_1_45 := exactOrderDistributionInt L 45)
    (a_1_60 := exactOrderDistributionInt L 60)
    (a_1_90 := exactOrderDistributionInt L 90)
    (a_1_180 := exactOrderDistributionInt L 180)
    (by
      rw [exactOrderDistributionInt_one]
      exact_mod_cast hcard)
    (exactOrderDistributionInt_nonneg A 2)
    (exactOrderDistributionInt_nonneg A 3)
    (exactOrderDistributionInt_nonneg A 4)
    (exactOrderDistributionInt_nonneg A 5)
    (exactOrderDistributionInt_nonneg A 6)
    (exactOrderDistributionInt_nonneg A 9)
    (exactOrderDistributionInt_nonneg A 10)
    (exactOrderDistributionInt_nonneg A 12)
    (exactOrderDistributionInt_nonneg A 15)
    (exactOrderDistributionInt_nonneg A 18)
    (exactOrderDistributionInt_nonneg A 20)
    (exactOrderDistributionInt_nonneg A 30)
    (exactOrderDistributionInt_nonneg A 36)
    (exactOrderDistributionInt_nonneg A 45)
    (exactOrderDistributionInt_nonneg A 60)
    (exactOrderDistributionInt_nonneg A 90)
    (exactOrderDistributionInt_nonneg A 180)
    (by
      simpa [hcard] using z180_sum_exactOrderDistributionInt A)
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 2) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 3) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_pos_three (X := A) hnot3A))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 4) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 5) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 6) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 9) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_pos_nine (X := A) hnot3A))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 10) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 12) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 15) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 18) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 20) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 30) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 36) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 45) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 60) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 90) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 180) (by norm_num)))
    (by
      rw [exactOrderDistributionInt_one]
      exact_mod_cast hcardL)
    (exactOrderDistributionInt_nonneg L 2)
    (exactOrderDistributionInt_nonneg L 3)
    (exactOrderDistributionInt_nonneg L 4)
    (exactOrderDistributionInt_nonneg L 5)
    (exactOrderDistributionInt_nonneg L 6)
    (exactOrderDistributionInt_nonneg L 9)
    (exactOrderDistributionInt_nonneg L 10)
    (exactOrderDistributionInt_nonneg L 12)
    (exactOrderDistributionInt_nonneg L 15)
    (exactOrderDistributionInt_nonneg L 18)
    (exactOrderDistributionInt_nonneg L 20)
    (exactOrderDistributionInt_nonneg L 30)
    (exactOrderDistributionInt_nonneg L 36)
    (exactOrderDistributionInt_nonneg L 45)
    (exactOrderDistributionInt_nonneg L 60)
    (exactOrderDistributionInt_nonneg L 90)
    (exactOrderDistributionInt_nonneg L 180)
    (by
      simpa [hcardL] using z180_sum_exactOrderDistributionInt L)
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 2) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_pos_three (X := L) hnot3L))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 4) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 5) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 6) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_pos_nine (X := L) hnot3L))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 10) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 12) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 15) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 18) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 20) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 30) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 36) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 45) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 60) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 90) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 180) (by norm_num)))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 2) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 2) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 3) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 3) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 4) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 4) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 5) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 5) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 6) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 6) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 9) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 9) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 10) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 10) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 12) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 12) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 15) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 15) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 18) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 18) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 20) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 20) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 30) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 30) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 36) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 36) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 45) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 45) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 60) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 60) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 90) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 90) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 180) (by norm_num) (by norm_num) hpos))
    (by
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 180) (by norm_num) (by norm_num) hpos))

#print axioms z180_nondivisor_k13_card_ne_of_spectral

end Fuglede
