-- Generated by fuglede_search/z180_nondivisor_k24_side0b_compact_to_lean.py
-- Exact-order source SHA-256: f3725f042801cf4050bc34be20d8de185730a0bf5884708daf2c74fff37ef837
import Mathlib.Tactic

set_option maxRecDepth 100000
set_option maxHeartbeats 0

/-! Four-candidate congruence certificate replacing cut leaf 99. -/

private theorem z180NondivisorK24Side0BZeroCutLeaf0
    {f : Int}
    (pf : 0 < f)
    (c0_low : (f ≤ 0))
    : False := by
  linarith only [pf, c0_low]
private theorem z180NondivisorK24Side0BZeroCutLeaf1
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (ne : 0 <= e)
    (d180 : t <= 0)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (c0_high : (1 ≤ f))
    (c1_low : (a ≤ 0))
    (c2_low : (c ≤ 43))
    : False := by
  linarith only [q18, nv, nb, ne, d180, i24, i32, c0_high, c1_low, c2_low]
private theorem z180NondivisorK24Side0BZeroCutLeaf2
    {a b c d e f g t : Int}
    (d180 : t <= 0)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (c1_low : (a ≤ 0))
    (c3_low : (d ≤ 109))
    (c4_low : (c ≤ 44))
    (c5_low : (b ≤ 0))
    (c6_low : (f ≤ 1))
    : False := by
  linarith only [d180, i24, i32, c1_low, c3_low, c4_low, c5_low, c6_low]
private theorem z180NondivisorK24Side0BZeroCutLeaf3
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (ne : 0 <= e)
    (d180 : t <= 0)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (c1_low : (a ≤ 0))
    (c4_low : (c ≤ 44))
    (c6_high : (2 ≤ f))
    : False := by
  linarith only [q18, nv, nb, ne, d180, i24, i32, c1_low, c4_low, c6_high]
private theorem z180NondivisorK24Side0BZeroCutLeaf4
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (na : 0 <= a)
    (nv : 0 <= v)
    (ne : 0 <= e)
    (d180 : t <= 0)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (c4_low : (c ≤ 44))
    (c5_high : (1 ≤ b))
    : False := by
  linarith only [q18, na, nv, ne, d180, i24, i29, i32, c4_low, c5_high]
private theorem z180NondivisorK24Side0BZeroCutLeaf5
    {a b c d e f g t : Int}
    (d180 : t <= 0)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (c1_low : (a ≤ 0))
    (c7_low : (f ≤ 1))
    (c8_low : (d ≤ 107))
    (c9_low : (c ≤ 45))
    (c10_low : (b ≤ 0))
    : False := by
  linarith only [d180, i24, i32, c1_low, c7_low, c8_low, c9_low, c10_low]
private theorem z180NondivisorK24Side0BZeroCutLeaf6
    {a b c e f g t : Int}
    (na : 0 <= a)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (c7_low : (f ≤ 1))
    (c10_high : (1 ≤ b))
    : False := by
  linarith only [na, i29, i32, c7_low, c10_high]
private theorem z180NondivisorK24Side0BZeroCutLeaf7
    {u a v b c d e f g t : Int}
    (q12 : 24 * u = -9 * t + 12 * c + 16 * d - 5 * e + 6 * f - 5 * g - 768)
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i27 : 0 <= 4 * a - t + 2 * b - 2 * e + 2 * f)
    (ht : t = 0)
    (c1_low : (a ≤ 0))
    (c7_low : (f ≤ 1))
    (c9_high : (46 ≤ c))
    (c11_low : (b ≤ 0))
    (c12_low : (u ≤ 32))
    : False := by
  linarith only [q12, q18, nv, i21, i27, ht, c1_low, c7_low, c9_high, c11_low, c12_low]
private theorem z180NondivisorK24Side0BZeroCutLeaf8
    {u a b c d e f g t : Int}
    (q12 : 24 * u = -9 * t + 12 * c + 16 * d - 5 * e + 6 * f - 5 * g - 768)
    (na : 0 <= a)
    (nb : 0 <= b)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (ht : t = 0)
    (c7_low : (f ≤ 1))
    (c9_high : (46 ≤ c))
    (c12_high : (33 ≤ u))
    (c13_low : (d ≤ 106))
    : False := by
  linarith only [q12, na, nb, i29, ht, c7_low, c9_high, c12_high, c13_low]
private theorem z180NondivisorK24Side0BZeroCutLeaf9
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (na : 0 <= a)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (ne : 0 <= e)
    (d180 : t <= 0)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (c0_high : (1 ≤ f))
    (c9_high : (46 ≤ c))
    (c13_high : (107 ≤ d))
    : False := by
  linarith only [q18, na, nv, nb, ne, d180, i29, c0_high, c9_high, c13_high]
private theorem z180NondivisorK24Side0BZeroCutLeaf10
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (na : 0 <= a)
    (nv : 0 <= v)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i27 : 0 <= 4 * a - t + 2 * b - 2 * e + 2 * f)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (ht : t = 0)
    (c7_low : (f ≤ 1))
    (c9_high : (46 ≤ c))
    (c11_high : (1 ≤ b))
    : False := by
  linarith only [q18, na, nv, i21, i27, i29, ht, c7_low, c9_high, c11_high]
private theorem z180NondivisorK24Side0BZeroCutLeaf11
    {u v c d e f g t : Int}
    (q12 : 24 * u = -9 * t + 12 * c + 16 * d - 5 * e + 6 * f - 5 * g - 768)
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (ne : 0 <= e)
    (d180 : t <= 0)
    (c0_high : (1 ≤ f))
    (c4_high : (45 ≤ c))
    (c8_high : (108 ≤ d))
    (c14_low : (u ≤ 34))
    : False := by
  linarith only [q12, q18, nv, ne, d180, c0_high, c4_high, c8_high, c14_low]
private theorem z180NondivisorK24Side0BZeroCutLeaf12
    {u v b c d e f g t : Int}
    (q12 : 24 * u = -9 * t + 12 * c + 16 * d - 5 * e + 6 * f - 5 * g - 768)
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (ne : 0 <= e)
    (d180 : t <= 0)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (c0_high : (1 ≤ f))
    (c4_high : (45 ≤ c))
    (c14_high : (35 ≤ u))
    : False := by
  linarith only [q12, q18, nv, nb, ne, d180, i24, c0_high, c4_high, c14_high]
private theorem z180NondivisorK24Side0BZeroCutLeaf13
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (ne : 0 <= e)
    (d180 : t <= 0)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (c1_low : (a ≤ 0))
    (c15_low : (c ≤ 45))
    (c16_low : (d ≤ 106))
    : False := by
  linarith only [q18, nv, ne, d180, i24, i32, c1_low, c15_low, c16_low]
private theorem z180NondivisorK24Side0BZeroCutLeaf14
    {v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (d180 : t <= 0)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (c4_high : (45 ≤ c))
    (c7_high : (2 ≤ f))
    (c16_high : (107 ≤ d))
    (c17_low : (g ≤ 138))
    : False := by
  linarith only [q18, nv, nb, d180, i24, c4_high, c7_high, c16_high, c17_low]
private theorem z180NondivisorK24Side0BZeroCutLeaf15
    {v c d e g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (ne : 0 <= e)
    (ht : t = 0)
    (c4_high : (45 ≤ c))
    (c16_high : (107 ≤ d))
    (c17_high : (139 ≤ g))
    : False := by
  linarith only [q18, nv, ne, ht, c4_high, c16_high, c17_high]
private theorem z180NondivisorK24Side0BZeroCutLeaf16
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (d180 : t <= 0)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i27 : 0 <= 4 * a - t + 2 * b - 2 * e + 2 * f)
    (c1_low : (a ≤ 0))
    (c7_high : (2 ≤ f))
    (c18_low : (d ≤ 105))
    : False := by
  linarith only [q18, nv, nb, d180, i21, i24, i27, c1_low, c7_high, c18_low]
private theorem z180NondivisorK24Side0BZeroCutLeaf17
    {v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (ne : 0 <= e)
    (d180 : t <= 0)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (c7_high : (2 ≤ f))
    (c15_high : (46 ≤ c))
    (c18_high : (106 ≤ d))
    : False := by
  linarith only [q18, nv, nb, ne, d180, i24, c7_high, c15_high, c18_high]
private theorem z180NondivisorK24Side0BZeroCutLeaf18
    {v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (ne : 0 <= e)
    (d180 : t <= 0)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (c0_high : (1 ≤ f))
    (c2_high : (44 ≤ c))
    (c3_high : (110 ≤ d))
    : False := by
  linarith only [q18, nv, nb, ne, d180, i24, c0_high, c2_high, c3_high]
private theorem z180NondivisorK24Side0BZeroCutLeaf19
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (ne : 0 <= e)
    (d180 : t <= 0)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (c0_high : (1 ≤ f))
    (c19_low : (c ≤ 43))
    : False := by
  linarith only [q18, nv, nb, ne, d180, i24, i29, i32, c0_high, c19_low]
private theorem z180NondivisorK24Side0BZeroCutLeaf20
    {a b c d e f g t : Int}
    (nb : 0 <= b)
    (d180 : t <= 0)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (c20_low : (d ≤ 108))
    (c21_low : (c ≤ 44))
    (c22_low : (f ≤ 2))
    : False := by
  linarith only [nb, d180, i24, i29, i32, c20_low, c21_low, c22_low]
private theorem z180NondivisorK24Side0BZeroCutLeaf21
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (ne : 0 <= e)
    (d180 : t <= 0)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (c21_low : (c ≤ 44))
    (c22_high : (3 ≤ f))
    : False := by
  linarith only [q18, nv, nb, ne, d180, i24, i29, i32, c21_low, c22_high]
private theorem z180NondivisorK24Side0BZeroCutLeaf22
    {a b c d e f g t : Int}
    (d180 : t <= 0)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (c23_low : (a ≤ 1))
    (c24_low : (f ≤ 2))
    (c25_low : (d ≤ 106))
    (c26_low : (c ≤ 45))
    : False := by
  linarith only [d180, i24, i29, i32, c23_low, c24_low, c25_low, c26_low]
private theorem z180NondivisorK24Side0BZeroCutLeaf23
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i27 : 0 <= 4 * a - t + 2 * b - 2 * e + 2 * f)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (ht : t = 0)
    (c23_low : (a ≤ 1))
    (c24_low : (f ≤ 2))
    (c26_high : (46 ≤ c))
    (c27_low : (d ≤ 104))
    : False := by
  linarith only [q18, nv, i21, i27, i29, ht, c23_low, c24_low, c26_high, c27_low]
private theorem z180NondivisorK24Side0BZeroCutLeaf24
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (d180 : t <= 0)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (c1_high : (1 ≤ a))
    (c26_high : (46 ≤ c))
    (c27_high : (105 ≤ d))
    : False := by
  linarith only [q18, nv, nb, d180, i21, i29, i32, c1_high, c26_high, c27_high]
private theorem z180NondivisorK24Side0BZeroCutLeaf25
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (ne : 0 <= e)
    (d180 : t <= 0)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (c0_high : (1 ≤ f))
    (c1_high : (1 ≤ a))
    (c21_high : (45 ≤ c))
    (c25_high : (107 ≤ d))
    : False := by
  linarith only [q18, nv, nb, ne, d180, i29, c0_high, c1_high, c21_high, c25_high]
private theorem z180NondivisorK24Side0BZeroCutLeaf26
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (d180 : t <= 0)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i27 : 0 <= 4 * a - t + 2 * b - 2 * e + 2 * f)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (c23_low : (a ≤ 1))
    (c24_high : (3 ≤ f))
    : False := by
  linarith only [q18, nv, nb, d180, i21, i24, i27, i32, c23_low, c24_high]
private theorem z180NondivisorK24Side0BZeroCutLeaf27
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (d180 : t <= 0)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i27 : 0 <= 4 * a - t + 2 * b - 2 * e + 2 * f)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (c23_high : (2 ≤ a))
    : False := by
  linarith only [q18, nv, nb, d180, i21, i24, i27, i29, i32, c23_high]
private theorem z180NondivisorK24Side0BZeroCutLeaf28
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (ne : 0 <= e)
    (d180 : t <= 0)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (c0_high : (1 ≤ f))
    (c1_high : (1 ≤ a))
    (c19_high : (44 ≤ c))
    (c20_high : (109 ≤ d))
    : False := by
  linarith only [q18, nv, nb, ne, d180, i29, c0_high, c1_high, c19_high, c20_high]

private theorem z180NondivisorK24Side0BZero
    {u a v b c d e f g t : Int}
    (q12 : 24 * u = -9 * t + 12 * c + 16 * d - 5 * e + 6 * f - 5 * g - 768)
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (n12 : 0 <= u)
    (na : 0 <= a)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (nc : 0 <= c)
    (nd : 0 <= d)
    (ne : 0 <= e)
    (ng : 0 <= g)
    (pf : 0 < f)
    (d180 : t <= 0)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i27 : 0 <= 4 * a - t + 2 * b - 2 * e + 2 * f)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (ht : t = 0)
    : False := by
  have c0 : (f ≤ 0) ∨ (1 ≤ f) := by omega
  rcases c0 with c0_low | c0_high
  · exact z180NondivisorK24Side0BZeroCutLeaf0 pf c0_low
  · have c1 : (a ≤ 0) ∨ (1 ≤ a) := by omega
    rcases c1 with c1_low | c1_high
    · have c2 : (c ≤ 43) ∨ (44 ≤ c) := by omega
      rcases c2 with c2_low | c2_high
      · exact z180NondivisorK24Side0BZeroCutLeaf1 q18 nv nb ne d180 i24 i32 c0_high c1_low c2_low
      · have c3 : (d ≤ 109) ∨ (110 ≤ d) := by omega
        rcases c3 with c3_low | c3_high
        · have c4 : (c ≤ 44) ∨ (45 ≤ c) := by omega
          rcases c4 with c4_low | c4_high
          · have c5 : (b ≤ 0) ∨ (1 ≤ b) := by omega
            rcases c5 with c5_low | c5_high
            · have c6 : (f ≤ 1) ∨ (2 ≤ f) := by omega
              rcases c6 with c6_low | c6_high
              · exact z180NondivisorK24Side0BZeroCutLeaf2 d180 i24 i32 c1_low c3_low c4_low c5_low c6_low
              · exact z180NondivisorK24Side0BZeroCutLeaf3 q18 nv nb ne d180 i24 i32 c1_low c4_low c6_high
            · exact z180NondivisorK24Side0BZeroCutLeaf4 q18 na nv ne d180 i24 i29 i32 c4_low c5_high
          · have c7 : (f ≤ 1) ∨ (2 ≤ f) := by omega
            rcases c7 with c7_low | c7_high
            · have c8 : (d ≤ 107) ∨ (108 ≤ d) := by omega
              rcases c8 with c8_low | c8_high
              · have c9 : (c ≤ 45) ∨ (46 ≤ c) := by omega
                rcases c9 with c9_low | c9_high
                · have c10 : (b ≤ 0) ∨ (1 ≤ b) := by omega
                  rcases c10 with c10_low | c10_high
                  · exact z180NondivisorK24Side0BZeroCutLeaf5 d180 i24 i32 c1_low c7_low c8_low c9_low c10_low
                  · exact z180NondivisorK24Side0BZeroCutLeaf6 na i29 i32 c7_low c10_high
                · have c11 : (b ≤ 0) ∨ (1 ≤ b) := by omega
                  rcases c11 with c11_low | c11_high
                  · have c12 : (u ≤ 32) ∨ (33 ≤ u) := by omega
                    rcases c12 with c12_low | c12_high
                    · exact z180NondivisorK24Side0BZeroCutLeaf7 q12 q18 nv i21 i27 ht c1_low c7_low c9_high c11_low c12_low
                    · have c13 : (d ≤ 106) ∨ (107 ≤ d) := by omega
                      rcases c13 with c13_low | c13_high
                      · exact z180NondivisorK24Side0BZeroCutLeaf8 q12 na nb i29 ht c7_low c9_high c12_high c13_low
                      · exact z180NondivisorK24Side0BZeroCutLeaf9 q18 na nv nb ne d180 i29 c0_high c9_high c13_high
                  · exact z180NondivisorK24Side0BZeroCutLeaf10 q18 na nv i21 i27 i29 ht c7_low c9_high c11_high
              · have c14 : (u ≤ 34) ∨ (35 ≤ u) := by omega
                rcases c14 with c14_low | c14_high
                · exact z180NondivisorK24Side0BZeroCutLeaf11 q12 q18 nv ne d180 c0_high c4_high c8_high c14_low
                · exact z180NondivisorK24Side0BZeroCutLeaf12 q12 q18 nv nb ne d180 i24 c0_high c4_high c14_high
            · have c15 : (c ≤ 45) ∨ (46 ≤ c) := by omega
              rcases c15 with c15_low | c15_high
              · have c16 : (d ≤ 106) ∨ (107 ≤ d) := by omega
                rcases c16 with c16_low | c16_high
                · exact z180NondivisorK24Side0BZeroCutLeaf13 q18 nv ne d180 i24 i32 c1_low c15_low c16_low
                · have c17 : (g ≤ 138) ∨ (139 ≤ g) := by omega
                  rcases c17 with c17_low | c17_high
                  · exact z180NondivisorK24Side0BZeroCutLeaf14 q18 nv nb d180 i24 c4_high c7_high c16_high c17_low
                  · exact z180NondivisorK24Side0BZeroCutLeaf15 q18 nv ne ht c4_high c16_high c17_high
              · have c18 : (d ≤ 105) ∨ (106 ≤ d) := by omega
                rcases c18 with c18_low | c18_high
                · exact z180NondivisorK24Side0BZeroCutLeaf16 q18 nv nb d180 i21 i24 i27 c1_low c7_high c18_low
                · exact z180NondivisorK24Side0BZeroCutLeaf17 q18 nv nb ne d180 i24 c7_high c15_high c18_high
        · exact z180NondivisorK24Side0BZeroCutLeaf18 q18 nv nb ne d180 i24 c0_high c2_high c3_high
    · have c19 : (c ≤ 43) ∨ (44 ≤ c) := by omega
      rcases c19 with c19_low | c19_high
      · exact z180NondivisorK24Side0BZeroCutLeaf19 q18 nv nb ne d180 i24 i29 i32 c0_high c19_low
      · have c20 : (d ≤ 108) ∨ (109 ≤ d) := by omega
        rcases c20 with c20_low | c20_high
        · have c21 : (c ≤ 44) ∨ (45 ≤ c) := by omega
          rcases c21 with c21_low | c21_high
          · have c22 : (f ≤ 2) ∨ (3 ≤ f) := by omega
            rcases c22 with c22_low | c22_high
            · exact z180NondivisorK24Side0BZeroCutLeaf20 nb d180 i24 i29 i32 c20_low c21_low c22_low
            · exact z180NondivisorK24Side0BZeroCutLeaf21 q18 nv nb ne d180 i24 i29 i32 c21_low c22_high
          · have c23 : (a ≤ 1) ∨ (2 ≤ a) := by omega
            rcases c23 with c23_low | c23_high
            · have c24 : (f ≤ 2) ∨ (3 ≤ f) := by omega
              rcases c24 with c24_low | c24_high
              · have c25 : (d ≤ 106) ∨ (107 ≤ d) := by omega
                rcases c25 with c25_low | c25_high
                · have c26 : (c ≤ 45) ∨ (46 ≤ c) := by omega
                  rcases c26 with c26_low | c26_high
                  · exact z180NondivisorK24Side0BZeroCutLeaf22 d180 i24 i29 i32 c23_low c24_low c25_low c26_low
                  · have c27 : (d ≤ 104) ∨ (105 ≤ d) := by omega
                    rcases c27 with c27_low | c27_high
                    · exact z180NondivisorK24Side0BZeroCutLeaf23 q18 nv i21 i27 i29 ht c23_low c24_low c26_high c27_low
                    · exact z180NondivisorK24Side0BZeroCutLeaf24 q18 nv nb d180 i21 i29 i32 c1_high c26_high c27_high
                · exact z180NondivisorK24Side0BZeroCutLeaf25 q18 nv nb ne d180 i29 c0_high c1_high c21_high c25_high
              · exact z180NondivisorK24Side0BZeroCutLeaf26 q18 nv nb d180 i21 i24 i27 i32 c23_low c24_high
            · exact z180NondivisorK24Side0BZeroCutLeaf27 q18 nv nb d180 i21 i24 i27 i29 i32 c23_high
        · exact z180NondivisorK24Side0BZeroCutLeaf28 q18 nv nb ne d180 i29 c0_high c1_high c19_high c20_high

private theorem z180NondivisorK24Side0BNegThreeCutLeaf0
    {f : Int}
    (pf : 0 < f)
    (c0_low : (f ≤ 0))
    : False := by
  linarith only [pf, c0_low]
private theorem z180NondivisorK24Side0BNegThreeCutLeaf1
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i27 : 0 <= 4 * a - t + 2 * b - 2 * e + 2 * f)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (ht : t = -3)
    (c0_high : (1 ≤ f))
    : False := by
  linarith only [q18, nv, nb, i21, i24, i27, i29, i32, ht, c0_high]

private theorem z180NondivisorK24Side0BNegThree
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (na : 0 <= a)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (nc : 0 <= c)
    (nd : 0 <= d)
    (ne : 0 <= e)
    (ng : 0 <= g)
    (pf : 0 < f)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i27 : 0 <= 4 * a - t + 2 * b - 2 * e + 2 * f)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (ht : t = -3)
    : False := by
  have c0 : (f ≤ 0) ∨ (1 ≤ f) := by omega
  rcases c0 with c0_low | c0_high
  · exact z180NondivisorK24Side0BNegThreeCutLeaf0 pf c0_low
  · exact z180NondivisorK24Side0BNegThreeCutLeaf1 q18 nv nb i21 i24 i27 i29 i32 ht c0_high

private theorem z180NondivisorK24Side0BNegTwoCutLeaf0
    {f : Int}
    (pf : 0 < f)
    (c0_low : (f ≤ 0))
    : False := by
  linarith only [pf, c0_low]
private theorem z180NondivisorK24Side0BNegTwoCutLeaf1
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i27 : 0 <= 4 * a - t + 2 * b - 2 * e + 2 * f)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (ht : t = -2)
    (c0_high : (1 ≤ f))
    (c1_low : (a ≤ 0))
    : False := by
  linarith only [q18, nv, nb, i21, i24, i27, i32, ht, c0_high, c1_low]
private theorem z180NondivisorK24Side0BNegTwoCutLeaf2
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i27 : 0 <= 4 * a - t + 2 * b - 2 * e + 2 * f)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (ht : t = -2)
    (c1_high : (1 ≤ a))
    : False := by
  linarith only [q18, nv, nb, i21, i24, i27, i29, i32, ht, c1_high]

private theorem z180NondivisorK24Side0BNegTwo
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (na : 0 <= a)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (nc : 0 <= c)
    (nd : 0 <= d)
    (ne : 0 <= e)
    (ng : 0 <= g)
    (pf : 0 < f)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i27 : 0 <= 4 * a - t + 2 * b - 2 * e + 2 * f)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (ht : t = -2)
    : False := by
  have c0 : (f ≤ 0) ∨ (1 ≤ f) := by omega
  rcases c0 with c0_low | c0_high
  · exact z180NondivisorK24Side0BNegTwoCutLeaf0 pf c0_low
  · have c1 : (a ≤ 0) ∨ (1 ≤ a) := by omega
    rcases c1 with c1_low | c1_high
    · exact z180NondivisorK24Side0BNegTwoCutLeaf1 q18 nv nb i21 i24 i27 i32 ht c0_high c1_low
    · exact z180NondivisorK24Side0BNegTwoCutLeaf2 q18 nv nb i21 i24 i27 i29 i32 ht c1_high

private theorem z180NondivisorK24Side0BNegOneCutLeaf0
    {f : Int}
    (pf : 0 < f)
    (c0_low : (f ≤ 0))
    : False := by
  linarith only [pf, c0_low]
private theorem z180NondivisorK24Side0BNegOneCutLeaf1
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (ne : 0 <= e)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (ht : t = -1)
    (c1_low : (a ≤ 0))
    (c2_low : (c ≤ 45))
    (c3_low : (d ≤ 107))
    : False := by
  linarith only [q18, nv, ne, i24, i32, ht, c1_low, c2_low, c3_low]
private theorem z180NondivisorK24Side0BNegOneCutLeaf2
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (ne : 0 <= e)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (ht : t = -1)
    (c0_high : (1 ≤ f))
    (c1_low : (a ≤ 0))
    (c3_high : (108 ≤ d))
    : False := by
  linarith only [q18, nv, nb, ne, i24, i32, ht, c0_high, c1_low, c3_high]
private theorem z180NondivisorK24Side0BNegOneCutLeaf3
    {b d e f g t : Int}
    (nb : 0 <= b)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (ht : t = -1)
    (c0_high : (1 ≤ f))
    (c4_low : (d ≤ 106))
    (c6_low : (e ≤ 1))
    (c7_low : (g ≤ 139))
    : False := by
  linarith only [nb, i24, ht, c0_high, c4_low, c6_low, c7_low]
private theorem z180NondivisorK24Side0BNegOneCutLeaf4
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (ht : t = -1)
    (c1_low : (a ≤ 0))
    (c2_high : (46 ≤ c))
    (c4_low : (d ≤ 106))
    (c7_high : (140 ≤ g))
    (c8_low : (f ≤ 1))
    : False := by
  linarith only [q18, nv, i21, i29, ht, c1_low, c2_high, c4_low, c7_high, c8_low]
private theorem z180NondivisorK24Side0BNegOneCutLeaf5
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (ht : t = -1)
    (c1_low : (a ≤ 0))
    (c2_high : (46 ≤ c))
    (c7_high : (140 ≤ g))
    (c8_high : (2 ≤ f))
    : False := by
  linarith only [q18, nv, nb, i21, i24, ht, c1_low, c2_high, c7_high, c8_high]
private theorem z180NondivisorK24Side0BNegOneCutLeaf6
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i27 : 0 <= 4 * a - t + 2 * b - 2 * e + 2 * f)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (ht : t = -1)
    (c1_low : (a ≤ 0))
    (c2_high : (46 ≤ c))
    (c6_high : (2 ≤ e))
    (c9_low : (f ≤ 1))
    : False := by
  linarith only [q18, nv, i21, i27, i29, ht, c1_low, c2_high, c6_high, c9_low]
private theorem z180NondivisorK24Side0BNegOneCutLeaf7
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i27 : 0 <= 4 * a - t + 2 * b - 2 * e + 2 * f)
    (ht : t = -1)
    (c1_low : (a ≤ 0))
    (c2_high : (46 ≤ c))
    (c9_high : (2 ≤ f))
    : False := by
  linarith only [q18, nv, nb, i21, i24, i27, ht, c1_low, c2_high, c9_high]
private theorem z180NondivisorK24Side0BNegOneCutLeaf8
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i27 : 0 <= 4 * a - t + 2 * b - 2 * e + 2 * f)
    (ht : t = -1)
    (c0_high : (1 ≤ f))
    (c1_low : (a ≤ 0))
    (c5_high : (47 ≤ c))
    : False := by
  linarith only [q18, nv, nb, i21, i24, i27, ht, c0_high, c1_low, c5_high]
private theorem z180NondivisorK24Side0BNegOneCutLeaf9
    {v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (ne : 0 <= e)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (ht : t = -1)
    (c0_high : (1 ≤ f))
    (c2_high : (46 ≤ c))
    (c4_high : (107 ≤ d))
    : False := by
  linarith only [q18, nv, nb, ne, i24, ht, c0_high, c2_high, c4_high]
private theorem z180NondivisorK24Side0BNegOneCutLeaf10
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (ne : 0 <= e)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (ht : t = -1)
    (c1_high : (1 ≤ a))
    (c10_low : (c ≤ 45))
    : False := by
  linarith only [q18, nv, nb, ne, i24, i29, i32, ht, c1_high, c10_low]
private theorem z180NondivisorK24Side0BNegOneCutLeaf11
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (ht : t = -1)
    (c11_low : (d ≤ 104))
    (c12_low : (c ≤ 46))
    : False := by
  linarith only [q18, nv, nb, i21, i24, i29, i32, ht, c11_low, c12_low]
private theorem z180NondivisorK24Side0BNegOneCutLeaf12
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i27 : 0 <= 4 * a - t + 2 * b - 2 * e + 2 * f)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (ht : t = -1)
    (c1_high : (1 ≤ a))
    (c12_high : (47 ≤ c))
    : False := by
  linarith only [q18, nv, nb, i21, i24, i27, i29, ht, c1_high, c12_high]
private theorem z180NondivisorK24Side0BNegOneCutLeaf13
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (ht : t = -1)
    (c0_high : (1 ≤ f))
    (c1_high : (1 ≤ a))
    (c10_high : (46 ≤ c))
    (c11_high : (105 ≤ d))
    : False := by
  linarith only [q18, nv, nb, i21, i29, ht, c0_high, c1_high, c10_high, c11_high]

private theorem z180NondivisorK24Side0BNegOne
    {a v b c d e f g t : Int}
    (q18 : 16 * v = -11 * t - 24 * c - 56 * d - 25 * e - 21 * g + 9984)
    (na : 0 <= a)
    (nv : 0 <= v)
    (nb : 0 <= b)
    (nc : 0 <= c)
    (nd : 0 <= d)
    (ne : 0 <= e)
    (ng : 0 <= g)
    (pf : 0 < f)
    (i21 : 20736 <= 40 * a - t + 20 * b + 72 * c + 144 * d + 55 * e + 20 * f + 15 * g)
    (i24 : -19 * t + 20 * b - 24 * d - 15 * e + 20 * f - 15 * g + 4608 <= 0)
    (i27 : 0 <= 4 * a - t + 2 * b - 2 * e + 2 * f)
    (i29 : 3 * a - t + 4 * b + 3 * c - e + f - g <= 0)
    (i32 : 0 <= a - t + 2 * b + 3 * c - e + 2 * f - g)
    (ht : t = -1)
    : False := by
  have c0 : (f ≤ 0) ∨ (1 ≤ f) := by omega
  rcases c0 with c0_low | c0_high
  · exact z180NondivisorK24Side0BNegOneCutLeaf0 pf c0_low
  · have c1 : (a ≤ 0) ∨ (1 ≤ a) := by omega
    rcases c1 with c1_low | c1_high
    · have c2 : (c ≤ 45) ∨ (46 ≤ c) := by omega
      rcases c2 with c2_low | c2_high
      · have c3 : (d ≤ 107) ∨ (108 ≤ d) := by omega
        rcases c3 with c3_low | c3_high
        · exact z180NondivisorK24Side0BNegOneCutLeaf1 q18 nv ne i24 i32 ht c1_low c2_low c3_low
        · exact z180NondivisorK24Side0BNegOneCutLeaf2 q18 nv nb ne i24 i32 ht c0_high c1_low c3_high
      · have c4 : (d ≤ 106) ∨ (107 ≤ d) := by omega
        rcases c4 with c4_low | c4_high
        · have c5 : (c ≤ 46) ∨ (47 ≤ c) := by omega
          rcases c5 with c5_low | c5_high
          · have c6 : (e ≤ 1) ∨ (2 ≤ e) := by omega
            rcases c6 with c6_low | c6_high
            · have c7 : (g ≤ 139) ∨ (140 ≤ g) := by omega
              rcases c7 with c7_low | c7_high
              · exact z180NondivisorK24Side0BNegOneCutLeaf3 nb i24 ht c0_high c4_low c6_low c7_low
              · have c8 : (f ≤ 1) ∨ (2 ≤ f) := by omega
                rcases c8 with c8_low | c8_high
                · exact z180NondivisorK24Side0BNegOneCutLeaf4 q18 nv i21 i29 ht c1_low c2_high c4_low c7_high c8_low
                · exact z180NondivisorK24Side0BNegOneCutLeaf5 q18 nv nb i21 i24 ht c1_low c2_high c7_high c8_high
            · have c9 : (f ≤ 1) ∨ (2 ≤ f) := by omega
              rcases c9 with c9_low | c9_high
              · exact z180NondivisorK24Side0BNegOneCutLeaf6 q18 nv i21 i27 i29 ht c1_low c2_high c6_high c9_low
              · exact z180NondivisorK24Side0BNegOneCutLeaf7 q18 nv nb i21 i24 i27 ht c1_low c2_high c9_high
          · exact z180NondivisorK24Side0BNegOneCutLeaf8 q18 nv nb i21 i24 i27 ht c0_high c1_low c5_high
        · exact z180NondivisorK24Side0BNegOneCutLeaf9 q18 nv nb ne i24 ht c0_high c2_high c4_high
    · have c10 : (c ≤ 45) ∨ (46 ≤ c) := by omega
      rcases c10 with c10_low | c10_high
      · exact z180NondivisorK24Side0BNegOneCutLeaf10 q18 nv nb ne i24 i29 i32 ht c1_high c10_low
      · have c11 : (d ≤ 104) ∨ (105 ≤ d) := by omega
        rcases c11 with c11_low | c11_high
        · have c12 : (c ≤ 46) ∨ (47 ≤ c) := by omega
          rcases c12 with c12_low | c12_high
          · exact z180NondivisorK24Side0BNegOneCutLeaf11 q18 nv nb i21 i24 i29 i32 ht c11_low c12_low
          · exact z180NondivisorK24Side0BNegOneCutLeaf12 q18 nv nb i21 i24 i27 i29 ht c1_high c12_high
        · exact z180NondivisorK24Side0BNegOneCutLeaf13 q18 nv nb i21 i29 ht c0_high c1_high c10_high c11_high

private theorem z180NondivisorK24Side0BCeilLower
    {t : Int} (h : -4 < t) : -3 <= t := by
  omega

private theorem z180NondivisorK24Side0BPinZero
    {t : Int}
    (lower : -3 <= t) (upper : t <= 0)
    (ne3 : t ≠ -3) (ne2 : t ≠ -2) (ne1 : t ≠ -1)
    : t = 0 := by
  omega

private theorem z180NondivisorK24Side0BArithmeticCore
    {a_0_12 a_0_15 a_0_18 a_0_20 a_0_30 a_0_36 a_0_45 a_0_60 a_0_90 a_0_180 : Int}
    (q12 : 24 * a_0_12 = -9 * a_0_180 + 12 * a_0_30 + 16 * a_0_36 - 5 * a_0_45 + 6 * a_0_60 - 5 * a_0_90 - 768)
    (q18 : 16 * a_0_18 = -11 * a_0_180 - 24 * a_0_30 - 56 * a_0_36 - 25 * a_0_45 - 21 * a_0_90 + 9984)
    (n12 : 0 <= a_0_12)
    (n15 : 0 <= a_0_15)
    (n18 : 0 <= a_0_18)
    (n20 : 0 <= a_0_20)
    (n30 : 0 <= a_0_30)
    (n36 : 0 <= a_0_36)
    (n45 : 0 <= a_0_45)
    (n90 : 0 <= a_0_90)
    (p60 : 0 < a_0_60)
    (d180 : a_0_180 <= 0)
    (i21 : 20736 <= 40 * a_0_15 - a_0_180 + 20 * a_0_20 + 72 * a_0_30 + 144 * a_0_36 + 55 * a_0_45 + 20 * a_0_60 + 15 * a_0_90)
    (i24 : -19 * a_0_180 + 20 * a_0_20 - 24 * a_0_36 - 15 * a_0_45 + 20 * a_0_60 - 15 * a_0_90 + 4608 <= 0)
    (i27 : 0 <= 4 * a_0_15 - a_0_180 + 2 * a_0_20 - 2 * a_0_45 + 2 * a_0_60)
    (i29 : 3 * a_0_15 - a_0_180 + 4 * a_0_20 + 3 * a_0_30 - a_0_45 + a_0_60 - a_0_90 <= 0)
    (i32 : 0 <= a_0_15 - a_0_180 + 2 * a_0_20 + 3 * a_0_30 - a_0_45 + 2 * a_0_60 - a_0_90)
    : False := by
  have lowerReal : -4 < a_0_180 := by
    linarith only [q18, n18, n20, p60, i21, i24, i27, i29, i32]
  have lower180 : -3 <= a_0_180 :=
    z180NondivisorK24Side0BCeilLower lowerReal
  have ne3 : a_0_180 ≠ -3 := by
    intro ht
    exact z180NondivisorK24Side0BNegThree q18 n15 n18 n20 n30 n36 n45 n90 p60 i21 i24 i27 i29 i32 ht
  have ne2 : a_0_180 ≠ -2 := by
    intro ht
    exact z180NondivisorK24Side0BNegTwo q18 n15 n18 n20 n30 n36 n45 n90 p60 i21 i24 i27 i29 i32 ht
  have ne1 : a_0_180 ≠ -1 := by
    intro ht
    exact z180NondivisorK24Side0BNegOne q18 n15 n18 n20 n30 n36 n45 n90 p60 i21 i24 i27 i29 i32 ht
  have z180 : a_0_180 = 0 :=
    z180NondivisorK24Side0BPinZero lower180 d180 ne3 ne2 ne1
  exact z180NondivisorK24Side0BZero q12 q18 n12 n15 n18 n20 n30 n36 n45 n90 p60 d180 i21 i24 i27 i29 i32 z180

theorem z180NondivisorK24Side0BCore
    {a_0_1 a_0_2 a_0_3 a_0_4 a_0_5 a_0_6 a_0_9 a_0_10 a_0_12 a_0_15 a_0_18 a_0_20 a_0_30 a_0_36 a_0_45 a_0_60 a_0_90 a_0_180 : Int}
    (h1 : (a_0_1 = 24))
    (h5 : (a_0_5 ≥ 0))
    (h6 : (a_0_6 ≥ 0))
    (h9 : (a_0_12 ≥ 0))
    (h10 : (a_0_15 ≥ 0))
    (h11 : (a_0_18 ≥ 0))
    (h12 : (a_0_20 ≥ 0))
    (h13 : (a_0_30 ≥ 0))
    (h14 : (a_0_36 ≥ 0))
    (h15 : (a_0_45 ≥ 0))
    (h17 : (a_0_90 ≥ 0))
    (h18 : ((a_0_1 + a_0_2 + a_0_3 + a_0_4 + a_0_5 + a_0_6 + a_0_9 + a_0_10 + a_0_12 + a_0_15 + a_0_18 + a_0_20 + a_0_30 + a_0_36 + a_0_45 + a_0_60 + a_0_90 + a_0_180) = 576))
    (h21 : (((2 * a_0_1) + ((-2) * a_0_2) + (2 * a_0_3) + (2 * a_0_5) + ((-2) * a_0_6) + (2 * a_0_9) + ((-2) * a_0_10) + (2 * a_0_15) + ((-2) * a_0_18) + ((-2) * a_0_30) + (2 * a_0_45) + ((-2) * a_0_90)) ≥ 0))
    (h24 : (((2 * a_0_1) + (2 * a_0_2) + (2 * a_0_3) + ((-2) * a_0_4) + (2 * a_0_5) + (2 * a_0_6) + ((-1) * a_0_9) + (2 * a_0_10) + ((-2) * a_0_12) + (2 * a_0_15) + ((-1) * a_0_18) + ((-2) * a_0_20) + (2 * a_0_30) + a_0_36 + ((-1) * a_0_45) + ((-2) * a_0_60) + ((-1) * a_0_90) + a_0_180) ≥ 0))
    (h27 : (((4 * a_0_1) + ((-4) * a_0_2) + (4 * a_0_3) + (4 * a_0_5) + ((-4) * a_0_6) + ((-2) * a_0_9) + ((-4) * a_0_10) + (4 * a_0_15) + (2 * a_0_18) + ((-4) * a_0_30) + ((-2) * a_0_45) + (2 * a_0_90)) ≥ 0))
    (h29 : (((6 * a_0_1) + (6 * a_0_2) + ((-3) * a_0_3) + ((-6) * a_0_4) + (6 * a_0_5) + ((-3) * a_0_6) + (6 * a_0_10) + (3 * a_0_12) + ((-3) * a_0_15) + ((-6) * a_0_20) + ((-3) * a_0_30) + (3 * a_0_60)) ≥ 0))
    (h32 : (((12 * a_0_1) + ((-12) * a_0_2) + ((-6) * a_0_3) + (12 * a_0_5) + (6 * a_0_6) + ((-12) * a_0_10) + ((-6) * a_0_15) + (6 * a_0_30)) ≥ 0))
    (e3 : (((a_0_1 * 2) + (a_0_2 * 2) + (a_0_3 * 2) + (a_0_4 * 2) + (a_0_5 * 2) + (a_0_6 * 2) + (a_0_9 * (-1)) + (a_0_10 * 2) + (a_0_12 * 2) + (a_0_15 * 2) + (a_0_18 * (-1)) + (a_0_20 * 2) + (a_0_30 * 2) + (a_0_36 * (-1)) + (a_0_45 * (-1)) + (a_0_60 * 2) + (a_0_90 * (-1)) + (a_0_180 * (-1))) = 0))
    (d5_nonpos : (a_0_5 ≤ 0))
    (d6_nonpos : (a_0_6 ≤ 0))
    (e10 : (((a_0_1 * 4) + (a_0_2 * 4) + (a_0_3 * 4) + (a_0_4 * (-4)) + (a_0_5 * (-1)) + (a_0_6 * 4) + (a_0_9 * 4) + (a_0_10 * (-1)) + (a_0_12 * (-4)) + (a_0_15 * (-1)) + (a_0_18 * 4) + (a_0_20 * 1) + (a_0_30 * (-1)) + (a_0_36 * (-4)) + (a_0_45 * (-1)) + (a_0_60 * 1) + (a_0_90 * (-1)) + (a_0_180 * 1)) = 0))
    (e15 : (((a_0_1 * 8) + (a_0_2 * 8) + (a_0_3 * 8) + (a_0_4 * 8) + (a_0_5 * (-2)) + (a_0_6 * 8) + (a_0_9 * (-4)) + (a_0_10 * (-2)) + (a_0_12 * 8) + (a_0_15 * (-2)) + (a_0_18 * (-4)) + (a_0_20 * (-2)) + (a_0_30 * (-2)) + (a_0_36 * (-4)) + (a_0_45 * 1) + (a_0_60 * (-2)) + (a_0_90 * 1) + (a_0_180 * 1)) = 0))
    (p60 : (a_0_60 > 0))
    (e60 : (((a_0_1 * 16) + (a_0_2 * (-16)) + (a_0_3 * 16) + (a_0_4 * 0) + (a_0_5 * (-4)) + (a_0_6 * (-16)) + (a_0_9 * (-8)) + (a_0_10 * 4) + (a_0_12 * 0) + (a_0_15 * (-4)) + (a_0_18 * 8) + (a_0_20 * 0) + (a_0_30 * 4) + (a_0_36 * 0) + (a_0_45 * 2) + (a_0_60 * 0) + (a_0_90 * (-2)) + (a_0_180 * 0)) = 0))
    (e90 : (((a_0_1 * 24) + (a_0_2 * 24) + (a_0_3 * (-12)) + (a_0_4 * (-24)) + (a_0_5 * (-6)) + (a_0_6 * (-12)) + (a_0_9 * 0) + (a_0_10 * (-6)) + (a_0_12 * 12) + (a_0_15 * 3) + (a_0_18 * 0) + (a_0_20 * 6) + (a_0_30 * 3) + (a_0_36 * 0) + (a_0_45 * 0) + (a_0_60 * (-3)) + (a_0_90 * 0) + (a_0_180 * 0)) = 0))
    (d180_nonpos : (a_0_180 ≤ 0))
    (e180 : (((a_0_1 * 48) + (a_0_2 * (-48)) + (a_0_3 * (-24)) + (a_0_4 * 0) + (a_0_5 * (-12)) + (a_0_6 * 24) + (a_0_9 * 0) + (a_0_10 * 12) + (a_0_12 * 0) + (a_0_15 * 6) + (a_0_18 * 0) + (a_0_20 * 0) + (a_0_30 * (-6)) + (a_0_36 * 0) + (a_0_45 * 0) + (a_0_60 * 0) + (a_0_90 * 0) + (a_0_180 * 0)) = 0))
    : False := by
  have z5 : a_0_5 = 0 := by linarith only [h5, d5_nonpos]
  have z6 : a_0_6 = 0 := by linarith only [h6, d6_nonpos]
  have q12 : 24 * a_0_12 = -9 * a_0_180 + 12 * a_0_30 + 16 * a_0_36 - 5 * a_0_45 + 6 * a_0_60 - 5 * a_0_90 - 768 := by
    linarith only [h1, h18, z5, z6, e3, e10, e15, e60, e90, e180]
  have q18 : 16 * a_0_18 = -11 * a_0_180 - 24 * a_0_30 - 56 * a_0_36 - 25 * a_0_45 - 21 * a_0_90 + 9984 := by
    linarith only [h1, h18, z5, z6, e3, e10, e15, e60, e90, e180]
  have i21 : 20736 <= 40 * a_0_15 - a_0_180 + 20 * a_0_20 + 72 * a_0_30 + 144 * a_0_36 + 55 * a_0_45 + 20 * a_0_60 + 15 * a_0_90 := by
    linarith only [h1, h18, z5, z6, e3, e10, e15, e60, e90, e180, h21]
  have i24 : -19 * a_0_180 + 20 * a_0_20 - 24 * a_0_36 - 15 * a_0_45 + 20 * a_0_60 - 15 * a_0_90 + 4608 <= 0 := by
    linarith only [h1, h18, z5, z6, e3, e10, e15, e60, e90, e180, h24]
  have i27 : 0 <= 4 * a_0_15 - a_0_180 + 2 * a_0_20 - 2 * a_0_45 + 2 * a_0_60 := by
    linarith only [h1, h18, z5, z6, e3, e10, e15, e60, e90, e180, h27]
  have i29 : 3 * a_0_15 - a_0_180 + 4 * a_0_20 + 3 * a_0_30 - a_0_45 + a_0_60 - a_0_90 <= 0 := by
    linarith only [h1, h18, z5, z6, e3, e10, e15, e60, e90, e180, h29]
  have i32 : 0 <= a_0_15 - a_0_180 + 2 * a_0_20 + 3 * a_0_30 - a_0_45 + 2 * a_0_60 - a_0_90 := by
    linarith only [h1, h18, z5, z6, e3, e10, e15, e60, e90, e180, h32]
  exact z180NondivisorK24Side0BArithmeticCore q12 q18 h9 h10 h11 h12 h13 h14 h15 h17 p60 d180_nonpos i21 i24 i27 i29 i32

#print axioms z180NondivisorK24Side0BCore
