-- Source: fuglede_search/z180_exact_order_evidence_20260808_v1/cores/k11.core.smt2
-- Source SHA-256: 8f4c3ac21dba8f378a9514941b94617ce9d33ba80d1824c85f251af013005938
-- Diagnostic single-leaf emission from the replayed exact tree.
-- Generated by fuglede_search/z180_nondivisor_omega_to_lean.py
import Mathlib.Tactic

set_option maxRecDepth 100000
set_option maxHeartbeats 0

theorem z180NondivisorK11Leaf9
    {a_0_4 a_1_1 a_1_2 a_1_3 a_1_4 a_1_5 a_1_6 a_1_9 a_1_10 a_1_12 a_1_15 a_1_18 a_1_20 a_1_30 a_1_36 a_1_45 a_1_60 a_1_90 a_1_180 : Int}
    (h62 : (¬ (((2 * a_1_1) + ((-2) * a_1_2) + (2 * a_1_3) + (2 * a_1_5) + ((-2) * a_1_6) + (2 * a_1_9) + ((-2) * a_1_10) + (2 * a_1_15) + ((-2) * a_1_18) + ((-2) * a_1_30) + (2 * a_1_45) + ((-2) * a_1_90)) ≤ 0)))
    (d9_pos : (a_0_4 > 0))
    (d9_zero : (((a_1_1 * 2) + (a_1_2 * (-2)) + (a_1_3 * 2) + (a_1_4 * 0) + (a_1_5 * 2) + (a_1_6 * (-2)) + (a_1_9 * 2) + (a_1_10 * (-2)) + (a_1_12 * 0) + (a_1_15 * 2) + (a_1_18 * (-2)) + (a_1_20 * 0) + (a_1_30 * (-2)) + (a_1_36 * 0) + (a_1_45 * 2) + (a_1_60 * 0) + (a_1_90 * (-2)) + (a_1_180 * 0)) = 0))
    : False := by
  linarith only [h62, d9_pos, d9_zero]

#print axioms z180NondivisorK11Leaf9
