-- Generated by fuglede_search/generate_z180_phi5_k10_typed_adapter.py
-- Generator SHA-256: 7a3dd90a892ad8bfffe4c1a4e3b83b2696a333c3384dc4e9197c8517b8fcb111
import Fuglede.Z180ExactOrderTransformThree
import Fuglede.Z180Phi5K10Dpll
import Mathlib.Tactic

set_option maxHeartbeats 0

/-!
# Typed order-five adapter at cardinality ten

Every integer variable in the sealed DPLL(T) theorem is instantiated with an
exact-order inner distribution of a genuine spectral pair.  The unconditional
CRT/Ramanujan theorem supplies nonnegativity, strict prime-power rows, and all
cross-complementarity implications.
-/

namespace Fuglede

private theorem z180_phi5_k10_A_transform_zero
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L) (hcard : A.card = 10) :
    z180ExactOrderTransform A 5 = 0 := by
  have hcardL : L.card = 10 := by
    calc
      L.card = A.card := hSpec.2.1.symm
      _ = 10 := hcard
  have hnot3A : ¬ 3 ∣ A.card := by norm_num [hcard]
  have hnot3L : ¬ 3 ∣ L.card := by norm_num [hcardL]
  have hnonneg := z180ExactOrderTransform_nonneg
    (z180RamanujanIdentity_all A) (e := 5) (by norm_num)
  by_contra hne
  have hpositive : 0 < z180ExactOrderTransform A 5 :=
    lt_of_le_of_ne hnonneg (Ne.symm hne)
  exact z180_phi5_k10_side0_positive_impossible
    (a_0_1 := exactOrderDistributionInt A 1)
    (a_0_2 := exactOrderDistributionInt A 2)
    (a_0_3 := exactOrderDistributionInt A 3)
    (a_0_4 := exactOrderDistributionInt A 4)
    (a_0_5 := exactOrderDistributionInt A 5)
    (a_0_6 := exactOrderDistributionInt A 6)
    (a_0_9 := exactOrderDistributionInt A 9)
    (a_0_10 := exactOrderDistributionInt A 10)
    (a_0_12 := exactOrderDistributionInt A 12)
    (a_0_15 := exactOrderDistributionInt A 15)
    (a_0_18 := exactOrderDistributionInt A 18)
    (a_0_20 := exactOrderDistributionInt A 20)
    (a_0_30 := exactOrderDistributionInt A 30)
    (a_0_36 := exactOrderDistributionInt A 36)
    (a_0_45 := exactOrderDistributionInt A 45)
    (a_0_60 := exactOrderDistributionInt A 60)
    (a_0_90 := exactOrderDistributionInt A 90)
    (a_0_180 := exactOrderDistributionInt A 180)
    (a_1_1 := exactOrderDistributionInt L 1)
    (a_1_2 := exactOrderDistributionInt L 2)
    (a_1_3 := exactOrderDistributionInt L 3)
    (a_1_4 := exactOrderDistributionInt L 4)
    (a_1_5 := exactOrderDistributionInt L 5)
    (a_1_6 := exactOrderDistributionInt L 6)
    (a_1_9 := exactOrderDistributionInt L 9)
    (a_1_10 := exactOrderDistributionInt L 10)
    (a_1_12 := exactOrderDistributionInt L 12)
    (a_1_15 := exactOrderDistributionInt L 15)
    (a_1_18 := exactOrderDistributionInt L 18)
    (a_1_20 := exactOrderDistributionInt L 20)
    (a_1_30 := exactOrderDistributionInt L 30)
    (a_1_36 := exactOrderDistributionInt L 36)
    (a_1_45 := exactOrderDistributionInt L 45)
    (a_1_60 := exactOrderDistributionInt L 60)
    (a_1_90 := exactOrderDistributionInt L 90)
    (a_1_180 := exactOrderDistributionInt L 180)
    (by
      rw [exactOrderDistributionInt_one]
      exact_mod_cast hcard)
    (exactOrderDistributionInt_nonneg A 2)
    (exactOrderDistributionInt_nonneg A 3)
    (exactOrderDistributionInt_nonneg A 4)
    (exactOrderDistributionInt_nonneg A 5)
    (exactOrderDistributionInt_nonneg A 6)
    (exactOrderDistributionInt_nonneg A 9)
    (exactOrderDistributionInt_nonneg A 10)
    (exactOrderDistributionInt_nonneg A 12)
    (exactOrderDistributionInt_nonneg A 15)
    (exactOrderDistributionInt_nonneg A 18)
    (exactOrderDistributionInt_nonneg A 20)
    (exactOrderDistributionInt_nonneg A 30)
    (exactOrderDistributionInt_nonneg A 36)
    (exactOrderDistributionInt_nonneg A 45)
    (exactOrderDistributionInt_nonneg A 60)
    (exactOrderDistributionInt_nonneg A 90)
    (exactOrderDistributionInt_nonneg A 180)
    (by
      simpa [hcard] using z180_sum_exactOrderDistributionInt A)
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 2) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 3) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_pos_three (X := A) hnot3A))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 4) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 5) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 6) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 9) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_pos_nine (X := A) hnot3A))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 10) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 12) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 15) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 18) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 20) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 30) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 36) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 45) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 60) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 90) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all A) (e := 180) (by norm_num)))
    (by
      rw [exactOrderDistributionInt_one]
      exact_mod_cast hcardL)
    (exactOrderDistributionInt_nonneg L 2)
    (exactOrderDistributionInt_nonneg L 3)
    (exactOrderDistributionInt_nonneg L 4)
    (exactOrderDistributionInt_nonneg L 5)
    (exactOrderDistributionInt_nonneg L 6)
    (exactOrderDistributionInt_nonneg L 9)
    (exactOrderDistributionInt_nonneg L 10)
    (exactOrderDistributionInt_nonneg L 12)
    (exactOrderDistributionInt_nonneg L 15)
    (exactOrderDistributionInt_nonneg L 18)
    (exactOrderDistributionInt_nonneg L 20)
    (exactOrderDistributionInt_nonneg L 30)
    (exactOrderDistributionInt_nonneg L 36)
    (exactOrderDistributionInt_nonneg L 45)
    (exactOrderDistributionInt_nonneg L 60)
    (exactOrderDistributionInt_nonneg L 90)
    (exactOrderDistributionInt_nonneg L 180)
    (by
      simpa [hcardL] using z180_sum_exactOrderDistributionInt L)
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 2) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 3) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_pos_three (X := L) hnot3L))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 4) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 5) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 6) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 9) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_pos_nine (X := L) hnot3L))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 10) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 12) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 15) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 18) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 20) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 30) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 36) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 45) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 60) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 90) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using
      (z180ExactOrderTransform_nonneg (z180RamanujanIdentity_all L) (e := 180) (by norm_num)))
    (by simpa [z180ExactOrderTransform, mul_comm] using hpositive)
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 2) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 2) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 3) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 3) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 4) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 4) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 5) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 5) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 6) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 6) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 9) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 9) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 10) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 10) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 12) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 12) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 15) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 15) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 18) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 18) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 20) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 20) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 30) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 30) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 36) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 36) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 45) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 45) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 60) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 60) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 90) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 90) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos hSpec (z180RamanujanIdentity_all L)
          (e := 180) (by norm_num) (by norm_num) hpos))
    (by
      dsimp only
      intro hpos
      simpa [z180ExactOrderTransform, mul_comm] using
        (z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos hSpec (z180RamanujanIdentity_all A)
          (e := 180) (by norm_num) (by norm_num) hpos))

/-- Both masks in a cardinality-ten spectral pair have zero exact-order-five
Fourier energy (represented by the integral Ramanujan transform). -/
theorem z180_phi5_k10_both_transform_zero
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L) (hcard : A.card = 10) :
    z180ExactOrderTransform A 5 = 0 ∧
      z180ExactOrderTransform L 5 = 0 := by
  have hcardL : L.card = 10 := by
    calc
      L.card = A.card := hSpec.2.1.symm
      _ = 10 := hcard
  exact ⟨z180_phi5_k10_A_transform_zero hSpec hcard,
    z180_phi5_k10_A_transform_zero (cyclotomicSpectrum_dual hSpec) hcardL⟩

private theorem z180_order_five_orbit_of_transform_zero
    {X : Finset (ZMod 180)}
    (hzero : z180ExactOrderTransform X 5 = 0) :
    ∀ d, frequencyOrder 180 d = 5 → CyclotomicZero 180 X d := by
  have h := z180RamanujanIdentity_all X 5 (by norm_num)
  rw [hzero] at h
  norm_num at h
  have henergy : exactOrderFourierEnergy X 5 = 0 := h.symm
  exact (exactOrderFourierEnergy_eq_zero_iff_cyclotomicZero X 5).mp henergy

/-- Cyclotomic form of the same conclusion, ready for the structural
`p²q²r` descent argument. -/
theorem z180_phi5_k10_both_cyclotomic_zero
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L) (hcard : A.card = 10) :
    CyclotomicZero 180 A 36 ∧ CyclotomicZero 180 L 36 := by
  obtain ⟨hA, hL⟩ := z180_phi5_k10_both_transform_zero hSpec hcard
  exact ⟨z180_order_five_orbit_of_transform_zero hA 36 (by decide),
    z180_order_five_orbit_of_transform_zero hL 36 (by decide)⟩

end Fuglede
