-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsCore

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_x_010 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((10 : ZMod 180) - y) ↔
        if z180K18M6Fifth (10 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (10 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (10 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_010

theorem z180_k18_m6_allowed_iff_crt_x_011 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((11 : ZMod 180) - y) ↔
        if z180K18M6Fifth (11 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (11 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (11 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_011

theorem z180_k18_m6_allowed_iff_crt_x_012 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((12 : ZMod 180) - y) ↔
        if z180K18M6Fifth (12 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (12 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (12 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_012

theorem z180_k18_m6_allowed_iff_crt_x_013 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((13 : ZMod 180) - y) ↔
        if z180K18M6Fifth (13 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (13 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (13 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_013

theorem z180_k18_m6_allowed_iff_crt_x_014 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((14 : ZMod 180) - y) ↔
        if z180K18M6Fifth (14 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (14 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (14 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_014

theorem z180_k18_m6_allowed_iff_crt_x_015 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((15 : ZMod 180) - y) ↔
        if z180K18M6Fifth (15 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (15 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (15 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_015

theorem z180_k18_m6_allowed_iff_crt_x_016 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((16 : ZMod 180) - y) ↔
        if z180K18M6Fifth (16 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (16 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (16 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_016

theorem z180_k18_m6_allowed_iff_crt_x_017 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((17 : ZMod 180) - y) ↔
        if z180K18M6Fifth (17 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (17 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (17 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_017

theorem z180_k18_m6_allowed_iff_crt_x_018 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((18 : ZMod 180) - y) ↔
        if z180K18M6Fifth (18 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (18 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (18 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_018

theorem z180_k18_m6_allowed_iff_crt_x_019 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((19 : ZMod 180) - y) ↔
        if z180K18M6Fifth (19 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (19 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (19 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_019

end Fuglede
