-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsCore

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_x_080 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((80 : ZMod 180) - y) ↔
        if z180K18M6Fifth (80 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (80 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (80 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_080

theorem z180_k18_m6_allowed_iff_crt_x_081 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((81 : ZMod 180) - y) ↔
        if z180K18M6Fifth (81 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (81 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (81 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_081

theorem z180_k18_m6_allowed_iff_crt_x_082 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((82 : ZMod 180) - y) ↔
        if z180K18M6Fifth (82 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (82 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (82 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_082

theorem z180_k18_m6_allowed_iff_crt_x_083 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((83 : ZMod 180) - y) ↔
        if z180K18M6Fifth (83 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (83 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (83 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_083

theorem z180_k18_m6_allowed_iff_crt_x_084 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((84 : ZMod 180) - y) ↔
        if z180K18M6Fifth (84 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (84 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (84 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_084

theorem z180_k18_m6_allowed_iff_crt_x_085 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((85 : ZMod 180) - y) ↔
        if z180K18M6Fifth (85 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (85 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (85 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_085

theorem z180_k18_m6_allowed_iff_crt_x_086 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((86 : ZMod 180) - y) ↔
        if z180K18M6Fifth (86 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (86 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (86 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_086

theorem z180_k18_m6_allowed_iff_crt_x_087 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((87 : ZMod 180) - y) ↔
        if z180K18M6Fifth (87 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (87 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (87 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_087

theorem z180_k18_m6_allowed_iff_crt_x_088 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((88 : ZMod 180) - y) ↔
        if z180K18M6Fifth (88 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (88 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (88 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_088

theorem z180_k18_m6_allowed_iff_crt_x_089 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((89 : ZMod 180) - y) ↔
        if z180K18M6Fifth (89 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (89 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (89 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_089

end Fuglede
