-- Generated by fuglede_search/generate_z180_exact_order_transform.py
-- Generator SHA-256: dfa773701e30274269836e0c44d8ac8505f7b9de26631673b9ed5445657735c3
import Fuglede.ExactOrderEnergy
import Fuglede.PrimeCyclotomic
import Mathlib.RingTheory.Polynomial.Cyclotomic.Eval
import Mathlib.Tactic

set_option maxHeartbeats 0

/-!
# The exact-order Ramanujan transform for `ZMod 180`

`z180ExactOrderTransform X e` is the integer association-scheme transform
used by the sealed arithmetic certificate.  Its coefficients are
`c_e(180/d)`, generated exactly from the divisor formula for Ramanujan sums.

The predicate `Z180RamanujanIdentity X` deliberately names the remaining
analytic bridge: this integer table equals the manifestly nonnegative sum of
squared Fourier norms in `ExactOrderEnergy`.  All downstream nonnegativity,
strict prime-power rows, and spectral cross-implications are proved here from
that one identity.
-/

namespace Fuglede

open Polynomial

/-- Explicit 18-by-18 exact-order transform at modulus 180. -/
noncomputable def z180ExactOrderTransform
    (X : Finset (ZMod 180)) : Nat -> Int
  | 1 =>
      exactOrderDistributionInt X 1 * 1 +
        exactOrderDistributionInt X 2 * 1 +
        exactOrderDistributionInt X 3 * 1 +
        exactOrderDistributionInt X 4 * 1 +
        exactOrderDistributionInt X 5 * 1 +
        exactOrderDistributionInt X 6 * 1 +
        exactOrderDistributionInt X 9 * 1 +
        exactOrderDistributionInt X 10 * 1 +
        exactOrderDistributionInt X 12 * 1 +
        exactOrderDistributionInt X 15 * 1 +
        exactOrderDistributionInt X 18 * 1 +
        exactOrderDistributionInt X 20 * 1 +
        exactOrderDistributionInt X 30 * 1 +
        exactOrderDistributionInt X 36 * 1 +
        exactOrderDistributionInt X 45 * 1 +
        exactOrderDistributionInt X 60 * 1 +
        exactOrderDistributionInt X 90 * 1 +
        exactOrderDistributionInt X 180 * 1
  | 2 =>
      exactOrderDistributionInt X 1 * 1 +
        exactOrderDistributionInt X 2 * 1 +
        exactOrderDistributionInt X 3 * 1 +
        exactOrderDistributionInt X 4 * (-1) +
        exactOrderDistributionInt X 5 * 1 +
        exactOrderDistributionInt X 6 * 1 +
        exactOrderDistributionInt X 9 * 1 +
        exactOrderDistributionInt X 10 * 1 +
        exactOrderDistributionInt X 12 * (-1) +
        exactOrderDistributionInt X 15 * 1 +
        exactOrderDistributionInt X 18 * 1 +
        exactOrderDistributionInt X 20 * (-1) +
        exactOrderDistributionInt X 30 * 1 +
        exactOrderDistributionInt X 36 * (-1) +
        exactOrderDistributionInt X 45 * 1 +
        exactOrderDistributionInt X 60 * (-1) +
        exactOrderDistributionInt X 90 * 1 +
        exactOrderDistributionInt X 180 * (-1)
  | 3 =>
      exactOrderDistributionInt X 1 * 2 +
        exactOrderDistributionInt X 2 * 2 +
        exactOrderDistributionInt X 3 * 2 +
        exactOrderDistributionInt X 4 * 2 +
        exactOrderDistributionInt X 5 * 2 +
        exactOrderDistributionInt X 6 * 2 +
        exactOrderDistributionInt X 9 * (-1) +
        exactOrderDistributionInt X 10 * 2 +
        exactOrderDistributionInt X 12 * 2 +
        exactOrderDistributionInt X 15 * 2 +
        exactOrderDistributionInt X 18 * (-1) +
        exactOrderDistributionInt X 20 * 2 +
        exactOrderDistributionInt X 30 * 2 +
        exactOrderDistributionInt X 36 * (-1) +
        exactOrderDistributionInt X 45 * (-1) +
        exactOrderDistributionInt X 60 * 2 +
        exactOrderDistributionInt X 90 * (-1) +
        exactOrderDistributionInt X 180 * (-1)
  | 4 =>
      exactOrderDistributionInt X 1 * 2 +
        exactOrderDistributionInt X 2 * (-2) +
        exactOrderDistributionInt X 3 * 2 +
        exactOrderDistributionInt X 4 * 0 +
        exactOrderDistributionInt X 5 * 2 +
        exactOrderDistributionInt X 6 * (-2) +
        exactOrderDistributionInt X 9 * 2 +
        exactOrderDistributionInt X 10 * (-2) +
        exactOrderDistributionInt X 12 * 0 +
        exactOrderDistributionInt X 15 * 2 +
        exactOrderDistributionInt X 18 * (-2) +
        exactOrderDistributionInt X 20 * 0 +
        exactOrderDistributionInt X 30 * (-2) +
        exactOrderDistributionInt X 36 * 0 +
        exactOrderDistributionInt X 45 * 2 +
        exactOrderDistributionInt X 60 * 0 +
        exactOrderDistributionInt X 90 * (-2) +
        exactOrderDistributionInt X 180 * 0
  | 5 =>
      exactOrderDistributionInt X 1 * 4 +
        exactOrderDistributionInt X 2 * 4 +
        exactOrderDistributionInt X 3 * 4 +
        exactOrderDistributionInt X 4 * 4 +
        exactOrderDistributionInt X 5 * (-1) +
        exactOrderDistributionInt X 6 * 4 +
        exactOrderDistributionInt X 9 * 4 +
        exactOrderDistributionInt X 10 * (-1) +
        exactOrderDistributionInt X 12 * 4 +
        exactOrderDistributionInt X 15 * (-1) +
        exactOrderDistributionInt X 18 * 4 +
        exactOrderDistributionInt X 20 * (-1) +
        exactOrderDistributionInt X 30 * (-1) +
        exactOrderDistributionInt X 36 * 4 +
        exactOrderDistributionInt X 45 * (-1) +
        exactOrderDistributionInt X 60 * (-1) +
        exactOrderDistributionInt X 90 * (-1) +
        exactOrderDistributionInt X 180 * (-1)
  | 6 =>
      exactOrderDistributionInt X 1 * 2 +
        exactOrderDistributionInt X 2 * 2 +
        exactOrderDistributionInt X 3 * 2 +
        exactOrderDistributionInt X 4 * (-2) +
        exactOrderDistributionInt X 5 * 2 +
        exactOrderDistributionInt X 6 * 2 +
        exactOrderDistributionInt X 9 * (-1) +
        exactOrderDistributionInt X 10 * 2 +
        exactOrderDistributionInt X 12 * (-2) +
        exactOrderDistributionInt X 15 * 2 +
        exactOrderDistributionInt X 18 * (-1) +
        exactOrderDistributionInt X 20 * (-2) +
        exactOrderDistributionInt X 30 * 2 +
        exactOrderDistributionInt X 36 * 1 +
        exactOrderDistributionInt X 45 * (-1) +
        exactOrderDistributionInt X 60 * (-2) +
        exactOrderDistributionInt X 90 * (-1) +
        exactOrderDistributionInt X 180 * 1
  | 9 =>
      exactOrderDistributionInt X 1 * 6 +
        exactOrderDistributionInt X 2 * 6 +
        exactOrderDistributionInt X 3 * (-3) +
        exactOrderDistributionInt X 4 * 6 +
        exactOrderDistributionInt X 5 * 6 +
        exactOrderDistributionInt X 6 * (-3) +
        exactOrderDistributionInt X 9 * 0 +
        exactOrderDistributionInt X 10 * 6 +
        exactOrderDistributionInt X 12 * (-3) +
        exactOrderDistributionInt X 15 * (-3) +
        exactOrderDistributionInt X 18 * 0 +
        exactOrderDistributionInt X 20 * 6 +
        exactOrderDistributionInt X 30 * (-3) +
        exactOrderDistributionInt X 36 * 0 +
        exactOrderDistributionInt X 45 * 0 +
        exactOrderDistributionInt X 60 * (-3) +
        exactOrderDistributionInt X 90 * 0 +
        exactOrderDistributionInt X 180 * 0
  | 10 =>
      exactOrderDistributionInt X 1 * 4 +
        exactOrderDistributionInt X 2 * 4 +
        exactOrderDistributionInt X 3 * 4 +
        exactOrderDistributionInt X 4 * (-4) +
        exactOrderDistributionInt X 5 * (-1) +
        exactOrderDistributionInt X 6 * 4 +
        exactOrderDistributionInt X 9 * 4 +
        exactOrderDistributionInt X 10 * (-1) +
        exactOrderDistributionInt X 12 * (-4) +
        exactOrderDistributionInt X 15 * (-1) +
        exactOrderDistributionInt X 18 * 4 +
        exactOrderDistributionInt X 20 * 1 +
        exactOrderDistributionInt X 30 * (-1) +
        exactOrderDistributionInt X 36 * (-4) +
        exactOrderDistributionInt X 45 * (-1) +
        exactOrderDistributionInt X 60 * 1 +
        exactOrderDistributionInt X 90 * (-1) +
        exactOrderDistributionInt X 180 * 1
  | 12 =>
      exactOrderDistributionInt X 1 * 4 +
        exactOrderDistributionInt X 2 * (-4) +
        exactOrderDistributionInt X 3 * 4 +
        exactOrderDistributionInt X 4 * 0 +
        exactOrderDistributionInt X 5 * 4 +
        exactOrderDistributionInt X 6 * (-4) +
        exactOrderDistributionInt X 9 * (-2) +
        exactOrderDistributionInt X 10 * (-4) +
        exactOrderDistributionInt X 12 * 0 +
        exactOrderDistributionInt X 15 * 4 +
        exactOrderDistributionInt X 18 * 2 +
        exactOrderDistributionInt X 20 * 0 +
        exactOrderDistributionInt X 30 * (-4) +
        exactOrderDistributionInt X 36 * 0 +
        exactOrderDistributionInt X 45 * (-2) +
        exactOrderDistributionInt X 60 * 0 +
        exactOrderDistributionInt X 90 * 2 +
        exactOrderDistributionInt X 180 * 0
  | 15 =>
      exactOrderDistributionInt X 1 * 8 +
        exactOrderDistributionInt X 2 * 8 +
        exactOrderDistributionInt X 3 * 8 +
        exactOrderDistributionInt X 4 * 8 +
        exactOrderDistributionInt X 5 * (-2) +
        exactOrderDistributionInt X 6 * 8 +
        exactOrderDistributionInt X 9 * (-4) +
        exactOrderDistributionInt X 10 * (-2) +
        exactOrderDistributionInt X 12 * 8 +
        exactOrderDistributionInt X 15 * (-2) +
        exactOrderDistributionInt X 18 * (-4) +
        exactOrderDistributionInt X 20 * (-2) +
        exactOrderDistributionInt X 30 * (-2) +
        exactOrderDistributionInt X 36 * (-4) +
        exactOrderDistributionInt X 45 * 1 +
        exactOrderDistributionInt X 60 * (-2) +
        exactOrderDistributionInt X 90 * 1 +
        exactOrderDistributionInt X 180 * 1
  | 18 =>
      exactOrderDistributionInt X 1 * 6 +
        exactOrderDistributionInt X 2 * 6 +
        exactOrderDistributionInt X 3 * (-3) +
        exactOrderDistributionInt X 4 * (-6) +
        exactOrderDistributionInt X 5 * 6 +
        exactOrderDistributionInt X 6 * (-3) +
        exactOrderDistributionInt X 9 * 0 +
        exactOrderDistributionInt X 10 * 6 +
        exactOrderDistributionInt X 12 * 3 +
        exactOrderDistributionInt X 15 * (-3) +
        exactOrderDistributionInt X 18 * 0 +
        exactOrderDistributionInt X 20 * (-6) +
        exactOrderDistributionInt X 30 * (-3) +
        exactOrderDistributionInt X 36 * 0 +
        exactOrderDistributionInt X 45 * 0 +
        exactOrderDistributionInt X 60 * 3 +
        exactOrderDistributionInt X 90 * 0 +
        exactOrderDistributionInt X 180 * 0
  | 20 =>
      exactOrderDistributionInt X 1 * 8 +
        exactOrderDistributionInt X 2 * (-8) +
        exactOrderDistributionInt X 3 * 8 +
        exactOrderDistributionInt X 4 * 0 +
        exactOrderDistributionInt X 5 * (-2) +
        exactOrderDistributionInt X 6 * (-8) +
        exactOrderDistributionInt X 9 * 8 +
        exactOrderDistributionInt X 10 * 2 +
        exactOrderDistributionInt X 12 * 0 +
        exactOrderDistributionInt X 15 * (-2) +
        exactOrderDistributionInt X 18 * (-8) +
        exactOrderDistributionInt X 20 * 0 +
        exactOrderDistributionInt X 30 * 2 +
        exactOrderDistributionInt X 36 * 0 +
        exactOrderDistributionInt X 45 * (-2) +
        exactOrderDistributionInt X 60 * 0 +
        exactOrderDistributionInt X 90 * 2 +
        exactOrderDistributionInt X 180 * 0
  | 30 =>
      exactOrderDistributionInt X 1 * 8 +
        exactOrderDistributionInt X 2 * 8 +
        exactOrderDistributionInt X 3 * 8 +
        exactOrderDistributionInt X 4 * (-8) +
        exactOrderDistributionInt X 5 * (-2) +
        exactOrderDistributionInt X 6 * 8 +
        exactOrderDistributionInt X 9 * (-4) +
        exactOrderDistributionInt X 10 * (-2) +
        exactOrderDistributionInt X 12 * (-8) +
        exactOrderDistributionInt X 15 * (-2) +
        exactOrderDistributionInt X 18 * (-4) +
        exactOrderDistributionInt X 20 * 2 +
        exactOrderDistributionInt X 30 * (-2) +
        exactOrderDistributionInt X 36 * 4 +
        exactOrderDistributionInt X 45 * 1 +
        exactOrderDistributionInt X 60 * 2 +
        exactOrderDistributionInt X 90 * 1 +
        exactOrderDistributionInt X 180 * (-1)
  | 36 =>
      exactOrderDistributionInt X 1 * 12 +
        exactOrderDistributionInt X 2 * (-12) +
        exactOrderDistributionInt X 3 * (-6) +
        exactOrderDistributionInt X 4 * 0 +
        exactOrderDistributionInt X 5 * 12 +
        exactOrderDistributionInt X 6 * 6 +
        exactOrderDistributionInt X 9 * 0 +
        exactOrderDistributionInt X 10 * (-12) +
        exactOrderDistributionInt X 12 * 0 +
        exactOrderDistributionInt X 15 * (-6) +
        exactOrderDistributionInt X 18 * 0 +
        exactOrderDistributionInt X 20 * 0 +
        exactOrderDistributionInt X 30 * 6 +
        exactOrderDistributionInt X 36 * 0 +
        exactOrderDistributionInt X 45 * 0 +
        exactOrderDistributionInt X 60 * 0 +
        exactOrderDistributionInt X 90 * 0 +
        exactOrderDistributionInt X 180 * 0
  | 45 =>
      exactOrderDistributionInt X 1 * 24 +
        exactOrderDistributionInt X 2 * 24 +
        exactOrderDistributionInt X 3 * (-12) +
        exactOrderDistributionInt X 4 * 24 +
        exactOrderDistributionInt X 5 * (-6) +
        exactOrderDistributionInt X 6 * (-12) +
        exactOrderDistributionInt X 9 * 0 +
        exactOrderDistributionInt X 10 * (-6) +
        exactOrderDistributionInt X 12 * (-12) +
        exactOrderDistributionInt X 15 * 3 +
        exactOrderDistributionInt X 18 * 0 +
        exactOrderDistributionInt X 20 * (-6) +
        exactOrderDistributionInt X 30 * 3 +
        exactOrderDistributionInt X 36 * 0 +
        exactOrderDistributionInt X 45 * 0 +
        exactOrderDistributionInt X 60 * 3 +
        exactOrderDistributionInt X 90 * 0 +
        exactOrderDistributionInt X 180 * 0
  | 60 =>
      exactOrderDistributionInt X 1 * 16 +
        exactOrderDistributionInt X 2 * (-16) +
        exactOrderDistributionInt X 3 * 16 +
        exactOrderDistributionInt X 4 * 0 +
        exactOrderDistributionInt X 5 * (-4) +
        exactOrderDistributionInt X 6 * (-16) +
        exactOrderDistributionInt X 9 * (-8) +
        exactOrderDistributionInt X 10 * 4 +
        exactOrderDistributionInt X 12 * 0 +
        exactOrderDistributionInt X 15 * (-4) +
        exactOrderDistributionInt X 18 * 8 +
        exactOrderDistributionInt X 20 * 0 +
        exactOrderDistributionInt X 30 * 4 +
        exactOrderDistributionInt X 36 * 0 +
        exactOrderDistributionInt X 45 * 2 +
        exactOrderDistributionInt X 60 * 0 +
        exactOrderDistributionInt X 90 * (-2) +
        exactOrderDistributionInt X 180 * 0
  | 90 =>
      exactOrderDistributionInt X 1 * 24 +
        exactOrderDistributionInt X 2 * 24 +
        exactOrderDistributionInt X 3 * (-12) +
        exactOrderDistributionInt X 4 * (-24) +
        exactOrderDistributionInt X 5 * (-6) +
        exactOrderDistributionInt X 6 * (-12) +
        exactOrderDistributionInt X 9 * 0 +
        exactOrderDistributionInt X 10 * (-6) +
        exactOrderDistributionInt X 12 * 12 +
        exactOrderDistributionInt X 15 * 3 +
        exactOrderDistributionInt X 18 * 0 +
        exactOrderDistributionInt X 20 * 6 +
        exactOrderDistributionInt X 30 * 3 +
        exactOrderDistributionInt X 36 * 0 +
        exactOrderDistributionInt X 45 * 0 +
        exactOrderDistributionInt X 60 * (-3) +
        exactOrderDistributionInt X 90 * 0 +
        exactOrderDistributionInt X 180 * 0
  | 180 =>
      exactOrderDistributionInt X 1 * 48 +
        exactOrderDistributionInt X 2 * (-48) +
        exactOrderDistributionInt X 3 * (-24) +
        exactOrderDistributionInt X 4 * 0 +
        exactOrderDistributionInt X 5 * (-12) +
        exactOrderDistributionInt X 6 * 24 +
        exactOrderDistributionInt X 9 * 0 +
        exactOrderDistributionInt X 10 * 12 +
        exactOrderDistributionInt X 12 * 0 +
        exactOrderDistributionInt X 15 * 6 +
        exactOrderDistributionInt X 18 * 0 +
        exactOrderDistributionInt X 20 * 0 +
        exactOrderDistributionInt X 30 * (-6) +
        exactOrderDistributionInt X 36 * 0 +
        exactOrderDistributionInt X 45 * 0 +
        exactOrderDistributionInt X 60 * 0 +
        exactOrderDistributionInt X 90 * 0 +
        exactOrderDistributionInt X 180 * 0
  | _ => 0

/-- The sole Ramanujan trust boundary in the current typed `ZMod 180` bridge. -/
def Z180RamanujanIdentity (X : Finset (ZMod 180)) : Prop :=
  ∀ e : Nat, e ∈ (180).divisors →
    (z180ExactOrderTransform X e : Real) = exactOrderFourierEnergy X e

/-- The generic divisor-fibre identity, normalized to the 18 divisors of
180 in the same order used by the arithmetic certificate. -/
theorem z180_sum_exactOrderDistributionInt (X : Finset (ZMod 180)) :
    exactOrderDistributionInt X 1 +
      exactOrderDistributionInt X 2 +
      exactOrderDistributionInt X 3 +
      exactOrderDistributionInt X 4 +
      exactOrderDistributionInt X 5 +
      exactOrderDistributionInt X 6 +
      exactOrderDistributionInt X 9 +
      exactOrderDistributionInt X 10 +
      exactOrderDistributionInt X 12 +
      exactOrderDistributionInt X 15 +
      exactOrderDistributionInt X 18 +
      exactOrderDistributionInt X 20 +
      exactOrderDistributionInt X 30 +
      exactOrderDistributionInt X 36 +
      exactOrderDistributionInt X 45 +
      exactOrderDistributionInt X 60 +
      exactOrderDistributionInt X 90 +
      exactOrderDistributionInt X 180 = (X.card ^ 2 : Nat) := by
  have hsum := sum_exactOrderDistributionInt (N := 180) X
  have hdivisors : (180).divisors =
      ({1, 2, 3, 4, 5, 6, 9, 10, 12, 15, 18, 20, 30, 36, 45, 60, 90, 180} : Finset Nat) := by decide
  rw [hdivisors] at hsum
  norm_num at hsum ⊢
  simpa only [add_assoc] using hsum

theorem z180ExactOrderTransform_nonneg
    {X : Finset (ZMod 180)}
    (hidentity : Z180RamanujanIdentity X)
    {e : Nat} (he : e ∈ (180).divisors) :
    0 ≤ z180ExactOrderTransform X e := by
  have hnonneg := exactOrderFourierEnergy_nonneg X e
  rw [← hidentity e he] at hnonneg
  exact_mod_cast hnonneg

theorem z180ExactOrderTransform_eq_zero_of_fourierEnergy_eq_zero
    {X : Finset (ZMod 180)}
    (hidentity : Z180RamanujanIdentity X)
    {e : Nat} (he : e ∈ (180).divisors)
    (hzero : exactOrderFourierEnergy X e = 0) :
    z180ExactOrderTransform X e = 0 := by
  have hcast := hidentity e he
  rw [hzero] at hcast
  exact_mod_cast hcast

theorem z180ExactOrderTransform_L_eq_zero_of_distribution_A_pos
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L)
    (hidentity : Z180RamanujanIdentity L)
    {e : Nat} (he : e ∈ (180).divisors) (hene : e ≠ 1)
    (hpos : 0 < exactOrderDistributionInt A e) :
    z180ExactOrderTransform L e = 0 := by
  have hposNat : 0 < exactOrderDistribution A e := by
    change 0 < (exactOrderDistribution A e : Int) at hpos
    exact_mod_cast hpos
  apply z180ExactOrderTransform_eq_zero_of_fourierEnergy_eq_zero hidentity he
  exact exactOrderFourierEnergy_L_eq_zero_of_distribution_A_pos
    hSpec hene hposNat

theorem z180ExactOrderTransform_A_eq_zero_of_distribution_L_pos
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L)
    (hidentity : Z180RamanujanIdentity A)
    {e : Nat} (he : e ∈ (180).divisors) (hene : e ≠ 1)
    (hpos : 0 < exactOrderDistributionInt L e) :
    z180ExactOrderTransform A e = 0 := by
  have hposNat : 0 < exactOrderDistribution L e := by
    change 0 < (exactOrderDistribution L e : Int) at hpos
    exact_mod_cast hpos
  apply z180ExactOrderTransform_eq_zero_of_fourierEnergy_eq_zero hidentity he
  exact exactOrderFourierEnergy_A_eq_zero_of_distribution_L_pos
    hSpec hene hposNat

/-- A prime-power cyclotomic divisor forces divisibility of mask cardinality
by the underlying prime. -/
theorem prime_dvd_card_of_prime_pow_cyclotomic_dvd_mask
    {N p : Nat} (hp : p.Prime) (k : Nat) (X : Finset (ZMod N))
    (hdiv : cyclotomic (p ^ (k + 1)) Int ∣ maskPolynomial N X) :
    p ∣ X.card := by
  letI : Fact p.Prime := ⟨hp⟩
  obtain ⟨Q, hQ⟩ := hdiv
  have heval := congrArg (Polynomial.eval (1 : Int)) hQ
  have hint : (p : Int) ∣ (X.card : Int) := by
    refine ⟨Polynomial.eval 1 Q, ?_⟩
    simpa [eval_one_maskPolynomial, Polynomial.eval_mul] using heval
  exact_mod_cast hint

private theorem z180_transform_ne_zero_two
    {X : Finset (ZMod 180)}
    (hidentity : Z180RamanujanIdentity X) (hnot : ¬ 2 ∣ X.card) :
    z180ExactOrderTransform X 2 ≠ 0 := by
  intro hzero
  have henergy : exactOrderFourierEnergy X 2 = 0 := by
    have h := hidentity 2 (by norm_num)
    rw [hzero] at h
    norm_num at h
    exact h.symm
  have horbit := (exactOrderFourierEnergy_eq_zero_iff_cyclotomicZero X 2).mp henergy
  have horder : frequencyOrder 180 (90 : ZMod 180) = 2 := by
    decide
  exact hnot (prime_dvd_card_of_cyclotomicZero (by norm_num) X 90 horder
    (horbit 90 horder))

private theorem z180_transform_ne_zero_four
    {X : Finset (ZMod 180)}
    (hidentity : Z180RamanujanIdentity X) (hnot : ¬ 2 ∣ X.card) :
    z180ExactOrderTransform X 4 ≠ 0 := by
  intro hzero
  have henergy : exactOrderFourierEnergy X 4 = 0 := by
    have h := hidentity 4 (by norm_num)
    rw [hzero] at h
    norm_num at h
    exact h.symm
  have horbit := (exactOrderFourierEnergy_eq_zero_iff_cyclotomicZero X 4).mp henergy
  have horder : frequencyOrder 180 (45 : ZMod 180) = 4 := by
    decide
  have hcyclo := horbit 45 horder
  have hdiv : cyclotomic (2 ^ (1 + 1)) Int ∣ maskPolynomial 180 X := by
    simpa [CyclotomicZero, horder] using hcyclo
  exact hnot (prime_dvd_card_of_prime_pow_cyclotomic_dvd_mask
    (by norm_num) 1 X hdiv)

private theorem z180_transform_ne_zero_five
    {X : Finset (ZMod 180)}
    (hidentity : Z180RamanujanIdentity X) (hnot : ¬ 5 ∣ X.card) :
    z180ExactOrderTransform X 5 ≠ 0 := by
  intro hzero
  have henergy : exactOrderFourierEnergy X 5 = 0 := by
    have h := hidentity 5 (by norm_num)
    rw [hzero] at h
    norm_num at h
    exact h.symm
  have horbit := (exactOrderFourierEnergy_eq_zero_iff_cyclotomicZero X 5).mp henergy
  have horder : frequencyOrder 180 (36 : ZMod 180) = 5 := by
    decide
  exact hnot (prime_dvd_card_of_cyclotomicZero (by norm_num) X 36 horder
    (horbit 36 horder))

theorem z180ExactOrderTransform_pos_two
    {X : Finset (ZMod 180)}
    (hidentity : Z180RamanujanIdentity X) (hnot : ¬ 2 ∣ X.card) :
    0 < z180ExactOrderTransform X 2 := by
  exact lt_of_le_of_ne
    (z180ExactOrderTransform_nonneg hidentity (by norm_num))
    (Ne.symm (z180_transform_ne_zero_two hidentity hnot))

theorem z180ExactOrderTransform_pos_four
    {X : Finset (ZMod 180)}
    (hidentity : Z180RamanujanIdentity X) (hnot : ¬ 2 ∣ X.card) :
    0 < z180ExactOrderTransform X 4 := by
  exact lt_of_le_of_ne
    (z180ExactOrderTransform_nonneg hidentity (by norm_num))
    (Ne.symm (z180_transform_ne_zero_four hidentity hnot))

theorem z180ExactOrderTransform_pos_five
    {X : Finset (ZMod 180)}
    (hidentity : Z180RamanujanIdentity X) (hnot : ¬ 5 ∣ X.card) :
    0 < z180ExactOrderTransform X 5 := by
  exact lt_of_le_of_ne
    (z180ExactOrderTransform_nonneg hidentity (by norm_num))
    (Ne.symm (z180_transform_ne_zero_five hidentity hnot))

end Fuglede
