-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsCore

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_x_150 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((150 : ZMod 180) - y) ↔
        if z180K18M6Fifth (150 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (150 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (150 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_150

theorem z180_k18_m6_allowed_iff_crt_x_151 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((151 : ZMod 180) - y) ↔
        if z180K18M6Fifth (151 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (151 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (151 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_151

theorem z180_k18_m6_allowed_iff_crt_x_152 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((152 : ZMod 180) - y) ↔
        if z180K18M6Fifth (152 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (152 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (152 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_152

theorem z180_k18_m6_allowed_iff_crt_x_153 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((153 : ZMod 180) - y) ↔
        if z180K18M6Fifth (153 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (153 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (153 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_153

theorem z180_k18_m6_allowed_iff_crt_x_154 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((154 : ZMod 180) - y) ↔
        if z180K18M6Fifth (154 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (154 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (154 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_154

theorem z180_k18_m6_allowed_iff_crt_x_155 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((155 : ZMod 180) - y) ↔
        if z180K18M6Fifth (155 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (155 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (155 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_155

theorem z180_k18_m6_allowed_iff_crt_x_156 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((156 : ZMod 180) - y) ↔
        if z180K18M6Fifth (156 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (156 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (156 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_156

theorem z180_k18_m6_allowed_iff_crt_x_157 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((157 : ZMod 180) - y) ↔
        if z180K18M6Fifth (157 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (157 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (157 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_157

theorem z180_k18_m6_allowed_iff_crt_x_158 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((158 : ZMod 180) - y) ↔
        if z180K18M6Fifth (158 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (158 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (158 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_158

theorem z180_k18_m6_allowed_iff_crt_x_159 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((159 : ZMod 180) - y) ↔
        if z180K18M6Fifth (159 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (159 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (159 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_159

end Fuglede
