-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsCore

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_x_120 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((120 : ZMod 180) - y) ↔
        if z180K18M6Fifth (120 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (120 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (120 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_120

theorem z180_k18_m6_allowed_iff_crt_x_121 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((121 : ZMod 180) - y) ↔
        if z180K18M6Fifth (121 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (121 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (121 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_121

theorem z180_k18_m6_allowed_iff_crt_x_122 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((122 : ZMod 180) - y) ↔
        if z180K18M6Fifth (122 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (122 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (122 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_122

theorem z180_k18_m6_allowed_iff_crt_x_123 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((123 : ZMod 180) - y) ↔
        if z180K18M6Fifth (123 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (123 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (123 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_123

theorem z180_k18_m6_allowed_iff_crt_x_124 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((124 : ZMod 180) - y) ↔
        if z180K18M6Fifth (124 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (124 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (124 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_124

theorem z180_k18_m6_allowed_iff_crt_x_125 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((125 : ZMod 180) - y) ↔
        if z180K18M6Fifth (125 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (125 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (125 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_125

theorem z180_k18_m6_allowed_iff_crt_x_126 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((126 : ZMod 180) - y) ↔
        if z180K18M6Fifth (126 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (126 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (126 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_126

theorem z180_k18_m6_allowed_iff_crt_x_127 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((127 : ZMod 180) - y) ↔
        if z180K18M6Fifth (127 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (127 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (127 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_127

theorem z180_k18_m6_allowed_iff_crt_x_128 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((128 : ZMod 180) - y) ↔
        if z180K18M6Fifth (128 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (128 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (128 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_128

theorem z180_k18_m6_allowed_iff_crt_x_129 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((129 : ZMod 180) - y) ↔
        if z180K18M6Fifth (129 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (129 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (129 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_129

end Fuglede
