import Fuglede.Z180K30ExceptionalSpectrumV62
import Mathlib.LinearAlgebra.Matrix.Rank
import Mathlib.Tactic

/-!
# Rank two in the exceptional K30 block branch

For one fixed dephased column, the exceptional joint spectrum has four zero
eigenvalues in every Gram block.  The corresponding four joint-basis vectors
give a four-dimensional subspace of the kernel, so rank-nullity bounds the
Gram rank by two.  The matrix identity for the Gram operator and invariance of
rank under `Mᴴ * M` transfer this bound to the Fourier block itself.

The final, matrix-only lemma chooses at most two actual rows spanning the row
space.  It is kept separate so later projective arguments need no knowledge of
the spectral construction.
-/

namespace Fuglede

open scoped BigOperators ComplexConjugate

noncomputable section

/-- A complex `6 x 6` matrix of rank at most two is generated by two of its
actual rows (with repetition allowed in the rank-zero and rank-one cases). -/
theorem matrix_rows_span_two_of_rank_le_two_v77
    (M : Z180K30BlockMatrixV19) (hrank : Matrix.rank M ≤ 2) :
    ∃ p q : Fin 6, ∃ alpha beta : Fin 6 → Complex,
      ∀ i j, M i j = alpha i * M p j + beta i * M q j := by
  classical
  by_cases hzero : ∀ i : Fin 6, M.row i = 0
  · refine ⟨0, 0, (fun _ => 0), (fun _ => 0), ?_⟩
    intro i j
    have hij := congrFun (hzero i) j
    simpa using hij
  · push_neg at hzero
    obtain ⟨p, hp⟩ := hzero
    by_cases hone : ∀ i : Fin 6,
        M.row i ∈ Submodule.span Complex ({M.row p} : Set (Fin 6 → Complex))
    · have hcoeff : ∀ i : Fin 6, ∃ a : Complex,
          M.row i = a • M.row p := by
        intro i
        rcases (Submodule.mem_span_singleton.mp (hone i)) with ⟨a, ha⟩
        exact ⟨a, ha.symm⟩
      choose alpha halpha using hcoeff
      refine ⟨p, p, alpha, (fun _ => 0), ?_⟩
      intro i j
      have hij := congrFun (halpha i) j
      simpa [Pi.smul_apply, smul_eq_mul] using hij
    · push_neg at hone
      obtain ⟨q, hq⟩ := hone
      let v : Fin 2 → (Fin 6 → Complex) := ![M.row p, M.row q]
      have hvLI : LinearIndependent Complex v := by
        dsimp only [v]
        rw [LinearIndependent.pair_iff' hp]
        intro a ha
        apply hq
        exact Submodule.mem_span_singleton.mpr ⟨a, ha⟩
      have hvRange : Set.range v = {M.row p, M.row q} := by
        ext x
        constructor
        · rintro ⟨i, rfl⟩
          fin_cases i <;> simp [v]
        · intro hx
          simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
          rcases hx with hx | hx
          · subst x
            exact ⟨0, by simp [v]⟩
          · subst x
            exact ⟨1, by simp [v]⟩
      let P : Submodule Complex (Fin 6 → Complex) :=
        Submodule.span Complex ({M.row p, M.row q} : Set (Fin 6 → Complex))
      let S : Submodule Complex (Fin 6 → Complex) :=
        Submodule.span Complex (Set.range M.row)
      have hPfin : Module.finrank Complex P = 2 := by
        dsimp only [P]
        rw [← hvRange]
        simpa using (finrank_span_eq_card hvLI)
      have hSfin_le : Module.finrank Complex S ≤ 2 := by
        have h := hrank
        rw [Matrix.rank_eq_finrank_span_row] at h
        simpa only [S] using h
      have hPS : P ≤ S := by
        dsimp only [P, S]
        apply Submodule.span_le.mpr
        intro x hx
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
        rcases hx with hx | hx
        · subst x
          exact Submodule.subset_span (Set.mem_range_self p)
        · subst x
          exact Submodule.subset_span (Set.mem_range_self q)
      have hPSfin : Module.finrank Complex P ≤ Module.finrank Complex S :=
        Submodule.finrank_mono hPS
      have hSfin : Module.finrank Complex S = 2 := by
        omega
      have hPS_eq : P = S := by
        apply Submodule.eq_of_le_of_finrank_eq hPS
        omega
      have hcoeff : ∀ i : Fin 6, ∃ a b : Complex,
          M.row i = a • M.row p + b • M.row q := by
        intro i
        have hiS : M.row i ∈ S := by
          dsimp only [S]
          exact Submodule.subset_span (Set.mem_range_self i)
        have hiP : M.row i ∈ P := by
          rw [hPS_eq]
          exact hiS
        change M.row i ∈ Submodule.span Complex
          (Set.insert (M.row p) ({M.row q} : Set (Fin 6 → Complex))) at hiP
        rcases (Submodule.mem_span_insert.mp hiP) with ⟨a, z, hz, haz⟩
        rcases (Submodule.mem_span_singleton.mp hz) with ⟨b, hb⟩
        rw [← hb] at haz
        exact ⟨a, b, haz.symm⟩
      choose alpha beta hab using hcoeff
      refine ⟨p, q, alpha, beta, ?_⟩
      intro i j
      have hij := congrFun (hab i) j
      simpa [Pi.smul_apply, smul_eq_mul] using hij

/-- Every block in an exceptional five-block Gram datum has rank at most two. -/
theorem Z180K30FiveBlockGramDataV20.block_rank_le_two_of_exceptional_v77
    (data : Z180K30FiveBlockGramDataV20)
    (hex : Z180K30ExceptionalGramEigenvalueData
      data.toPositiveFamily.eigenvalue)
    (r : Fin 5) :
    Matrix.rank (data.block r) ≤ 2 := by
  classical
  obtain ⟨k6, k30, hkne, _hk6, _hk30, hzero⟩ :=
    hex.exists_row_normal_spike_zero_v62 r
  let I := {k : Fin 6 // k ≠ k6 ∧ k ≠ k30}
  have hIcard : Fintype.card I = 4 := by
    dsimp only [I]
    fin_cases k6 <;> fin_cases k30 <;> simp_all <;> decide
  let T : Module.End Complex Z180K30JointSpaceV5 :=
    z180K30GramOfMatrixV19 (data.block r)
  have hLI : LinearIndependent Complex
      (fun k : I => data.toPositiveFamily.family.jointBasis k.1) :=
    data.toPositiveFamily.family.jointBasis.toBasis.linearIndependent.comp
      (fun k : I => k.1) Subtype.val_injective
  have hkerBasis (k : I) :
      data.toPositiveFamily.family.jointBasis k.1 ∈ LinearMap.ker T := by
    rw [LinearMap.mem_ker]
    change z180K30GramOfMatrixV19 (data.block r)
      (data.toPositiveFamily.family.jointBasis k.1) = 0
    have happly := data.toPositiveFamily.gram_apply_jointBasis k.1 r
    change z180K30GramOfMatrixV19 (data.block r)
        (data.toPositiveFamily.family.jointBasis k.1) =
      (data.toPositiveFamily.eigenvalue k.1 r : Complex) •
        data.toPositiveFamily.family.jointBasis k.1 at happly
    rw [hzero k.1 k.2.1 k.2.2] at happly
    simpa using happly
  let W : Submodule Complex Z180K30JointSpaceV5 :=
    Submodule.span Complex
      (Set.range fun k : I => data.toPositiveFamily.family.jointBasis k.1)
  have hWker : W ≤ LinearMap.ker T := by
    dsimp only [W]
    apply Submodule.span_le.mpr
    rintro x ⟨k, rfl⟩
    exact hkerBasis k
  have hWfin : Module.finrank Complex W = 4 := by
    dsimp only [W]
    calc
      Module.finrank Complex
          (Submodule.span Complex
            (Set.range fun k : I =>
              data.toPositiveFamily.family.jointBasis k.1)) =
          Fintype.card I := finrank_span_eq_card hLI
      _ = 4 := hIcard
  have hkerFin :
      4 ≤ Module.finrank Complex (LinearMap.ker T) := by
    calc
      4 = Module.finrank Complex W := hWfin.symm
      _ ≤ Module.finrank Complex (LinearMap.ker T) :=
        Submodule.finrank_mono hWker
  have hnullity := LinearMap.finrank_range_add_finrank_ker T
  have hambient : Module.finrank Complex Z180K30JointSpaceV5 = 6 := by
    simp [Z180K30JointSpaceV5]
  have hrange : Module.finrank Complex (LinearMap.range T) ≤ 2 := by
    omega
  let G : Z180K30BlockMatrixV19 :=
    Matrix.conjTranspose (data.block r) * data.block r
  have hbridge : T = Matrix.toEuclideanLin G := by
    dsimp only [T, G]
    exact z180K30GramOfMatrixV19_eq_toEuclideanLin_v39 (data.block r)
  have hGrankRange :
      Matrix.rank G =
        Module.finrank Complex
          (LinearMap.range (Matrix.toEuclideanLin G)) := by
    simpa only [Matrix.toEuclideanLin_eq_toLin_orthonormal] using
      (Matrix.rank_eq_finrank_range_toLin G
        (EuclideanSpace.basisFun (Fin 6) Complex).toBasis
        (EuclideanSpace.basisFun (Fin 6) Complex).toBasis)
  have hGrank : Matrix.rank G ≤ 2 := by
    rw [hGrankRange, ← hbridge]
    exact hrange
  simpa only [G, Matrix.rank_conjTranspose_mul_self] using hGrank

/-- The rank bound immediately gives a two-row formula for every exceptional
abstract Gram block. -/
theorem Z180K30FiveBlockGramDataV20.block_rows_span_two_of_exceptional_v77
    (data : Z180K30FiveBlockGramDataV20)
    (hex : Z180K30ExceptionalGramEigenvalueData
      data.toPositiveFamily.eigenvalue)
    (r : Fin 5) :
    ∃ p q : Fin 6, ∃ alpha beta : Fin 6 → Complex,
      ∀ i j,
        data.block r i j =
          alpha i * data.block r p j + beta i * data.block r q j :=
  matrix_rows_span_two_of_rank_le_two_v77 (data.block r)
    (data.block_rank_le_two_of_exceptional_v77 hex r)

/-- Concrete rank-two statement for every row block in a fixed exceptional
dephased column. -/
theorem z180K30DephasedFourierBlockV51_rank_le_two_of_exceptional_v77
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L) (hcard : A.card = 30)
    (data : Z180K30BalancedFibreDataV22 A L) (s : Fin 5)
    (hex : Z180K30ExceptionalGramEigenvalueData
      (z180K30DephasedFiveBlockGramDataV54
        hSpec hcard data s).toPositiveFamily.eigenvalue)
    (r : Fin 5) :
    Matrix.rank (z180K30DephasedFourierBlockV51 data r s) ≤ 2 := by
  simpa only [z180K30DephasedFiveBlockGramDataV54] using
    (Z180K30FiveBlockGramDataV20.block_rank_le_two_of_exceptional_v77
      (z180K30DephasedFiveBlockGramDataV54 hSpec hcard data s) hex r)

/-- Concrete two-row parametrization for every row block in a fixed
exceptional dephased column. -/
theorem z180K30DephasedFourierBlockV51_rows_span_two_of_exceptional_v77
    {A L : Finset (ZMod 180)}
    (hSpec : CyclotomicSpectrum 180 A L) (hcard : A.card = 30)
    (data : Z180K30BalancedFibreDataV22 A L) (s : Fin 5)
    (hex : Z180K30ExceptionalGramEigenvalueData
      (z180K30DephasedFiveBlockGramDataV54
        hSpec hcard data s).toPositiveFamily.eigenvalue)
    (r : Fin 5) :
    ∃ p q : Fin 6, ∃ alpha beta : Fin 6 → Complex,
      ∀ i j,
        z180K30DephasedFourierBlockV51 data r s i j =
          alpha i * z180K30DephasedFourierBlockV51 data r s p j +
          beta i * z180K30DephasedFourierBlockV51 data r s q j :=
  matrix_rows_span_two_of_rank_le_two_v77
    (z180K30DephasedFourierBlockV51 data r s)
    (z180K30DephasedFourierBlockV51_rank_le_two_of_exceptional_v77
      hSpec hcard data s hex r)

#print axioms matrix_rows_span_two_of_rank_le_two_v77
#print axioms Z180K30FiveBlockGramDataV20.block_rank_le_two_of_exceptional_v77
#print axioms Z180K30FiveBlockGramDataV20.block_rows_span_two_of_exceptional_v77
#print axioms z180K30DephasedFourierBlockV51_rank_le_two_of_exceptional_v77
#print axioms z180K30DephasedFourierBlockV51_rows_span_two_of_exceptional_v77

end
end Fuglede
