-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsCore

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_x_040 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((40 : ZMod 180) - y) ↔
        if z180K18M6Fifth (40 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (40 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (40 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_040

theorem z180_k18_m6_allowed_iff_crt_x_041 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((41 : ZMod 180) - y) ↔
        if z180K18M6Fifth (41 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (41 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (41 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_041

theorem z180_k18_m6_allowed_iff_crt_x_042 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((42 : ZMod 180) - y) ↔
        if z180K18M6Fifth (42 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (42 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (42 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_042

theorem z180_k18_m6_allowed_iff_crt_x_043 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((43 : ZMod 180) - y) ↔
        if z180K18M6Fifth (43 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (43 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (43 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_043

theorem z180_k18_m6_allowed_iff_crt_x_044 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((44 : ZMod 180) - y) ↔
        if z180K18M6Fifth (44 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (44 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (44 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_044

theorem z180_k18_m6_allowed_iff_crt_x_045 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((45 : ZMod 180) - y) ↔
        if z180K18M6Fifth (45 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (45 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (45 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_045

theorem z180_k18_m6_allowed_iff_crt_x_046 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((46 : ZMod 180) - y) ↔
        if z180K18M6Fifth (46 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (46 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (46 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_046

theorem z180_k18_m6_allowed_iff_crt_x_047 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((47 : ZMod 180) - y) ↔
        if z180K18M6Fifth (47 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (47 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (47 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_047

theorem z180_k18_m6_allowed_iff_crt_x_048 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((48 : ZMod 180) - y) ↔
        if z180K18M6Fifth (48 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (48 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (48 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_048

theorem z180_k18_m6_allowed_iff_crt_x_049 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((49 : ZMod 180) - y) ↔
        if z180K18M6Fifth (49 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (49 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (49 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_049

end Fuglede
