-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsCore

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_x_140 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((140 : ZMod 180) - y) ↔
        if z180K18M6Fifth (140 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (140 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (140 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_140

theorem z180_k18_m6_allowed_iff_crt_x_141 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((141 : ZMod 180) - y) ↔
        if z180K18M6Fifth (141 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (141 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (141 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_141

theorem z180_k18_m6_allowed_iff_crt_x_142 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((142 : ZMod 180) - y) ↔
        if z180K18M6Fifth (142 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (142 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (142 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_142

theorem z180_k18_m6_allowed_iff_crt_x_143 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((143 : ZMod 180) - y) ↔
        if z180K18M6Fifth (143 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (143 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (143 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_143

theorem z180_k18_m6_allowed_iff_crt_x_144 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((144 : ZMod 180) - y) ↔
        if z180K18M6Fifth (144 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (144 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (144 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_144

theorem z180_k18_m6_allowed_iff_crt_x_145 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((145 : ZMod 180) - y) ↔
        if z180K18M6Fifth (145 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (145 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (145 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_145

theorem z180_k18_m6_allowed_iff_crt_x_146 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((146 : ZMod 180) - y) ↔
        if z180K18M6Fifth (146 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (146 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (146 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_146

theorem z180_k18_m6_allowed_iff_crt_x_147 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((147 : ZMod 180) - y) ↔
        if z180K18M6Fifth (147 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (147 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (147 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_147

theorem z180_k18_m6_allowed_iff_crt_x_148 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((148 : ZMod 180) - y) ↔
        if z180K18M6Fifth (148 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (148 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (148 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_148

theorem z180_k18_m6_allowed_iff_crt_x_149 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((149 : ZMod 180) - y) ↔
        if z180K18M6Fifth (149 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (149 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (149 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_149

end Fuglede
