-- Generated by generate_z180_k18_m6_graph_defs_shards.py. DO NOT EDIT.
import Fuglede.Z180K18M6GraphDefsCore

namespace Fuglede

theorem z180_k18_m6_allowed_iff_crt_x_000 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((0 : ZMod 180) - y) ↔
        if z180K18M6Fifth (0 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (0 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (0 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_000

theorem z180_k18_m6_allowed_iff_crt_x_001 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((1 : ZMod 180) - y) ↔
        if z180K18M6Fifth (1 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (1 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (1 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_001

theorem z180_k18_m6_allowed_iff_crt_x_002 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((2 : ZMod 180) - y) ↔
        if z180K18M6Fifth (2 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (2 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (2 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_002

theorem z180_k18_m6_allowed_iff_crt_x_003 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((3 : ZMod 180) - y) ↔
        if z180K18M6Fifth (3 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (3 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (3 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_003

theorem z180_k18_m6_allowed_iff_crt_x_004 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((4 : ZMod 180) - y) ↔
        if z180K18M6Fifth (4 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (4 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (4 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_004

theorem z180_k18_m6_allowed_iff_crt_x_005 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((5 : ZMod 180) - y) ↔
        if z180K18M6Fifth (5 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (5 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (5 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_005

theorem z180_k18_m6_allowed_iff_crt_x_006 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((6 : ZMod 180) - y) ↔
        if z180K18M6Fifth (6 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (6 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (6 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_006

theorem z180_k18_m6_allowed_iff_crt_x_007 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((7 : ZMod 180) - y) ↔
        if z180K18M6Fifth (7 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (7 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (7 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_007

theorem z180_k18_m6_allowed_iff_crt_x_008 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((8 : ZMod 180) - y) ↔
        if z180K18M6Fifth (8 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (8 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (8 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_008

theorem z180_k18_m6_allowed_iff_crt_x_009 :
    ∀ y : ZMod 180,
      Z180K18M6AllowedDifference ((9 : ZMod 180) - y) ↔
        if z180K18M6Fifth (9 : ZMod 180) = z180K18M6Fifth y then
          Z180K18M6SameLevelCompatible
            (z180K18M6BaseCoord (9 : ZMod 180))
            (z180K18M6BaseCoord y)
        else
          Z180K18M6CrossLevelCompatible
            (z180K18M6BaseCoord (9 : ZMod 180))
            (z180K18M6BaseCoord y) := by
  set_option maxRecDepth 100000 in
    decide

#print axioms z180_k18_m6_allowed_iff_crt_x_009

end Fuglede
